class AmusementParkRunner {
    public static void main(String[] args) {
        System.out.println("Main Started");

        AmusementPark parkOne = new AmusementPark();
        parkOne.parkId = 1;
        System.out.println("Park ID: " + parkOne.parkId);
        parkOne.name = "Wonder World";
        System.out.println("Name: " + parkOne.name);
        parkOne.location = "Orlando, USA";
        System.out.println("Location: " + parkOne.location);
        parkOne.yearEstablished = 1995;
        System.out.println("Year Established: " + parkOne.yearEstablished);
        parkOne.numberOfRides = 40;
        System.out.println("Number of Rides: " + parkOne.numberOfRides);
        parkOne.hasWaterPark = true;
        System.out.println("Has Water Park: " + parkOne.hasWaterPark);
        System.out.println();

        AmusementPark parkTwo = new AmusementPark();
        parkTwo.parkId = 2;
        System.out.println("Park ID: " + parkTwo.parkId);
        parkTwo.name = "Adventure Kingdom";
        System.out.println("Name: " + parkTwo.name);
        parkTwo.location = "Dubai, UAE";
        System.out.println("Location: " + parkTwo.location);
        parkTwo.yearEstablished = 2003;
        System.out.println("Year Established: " + parkTwo.yearEstablished);
        parkTwo.numberOfRides = 30;
        System.out.println("Number of Rides: " + parkTwo.numberOfRides);
        parkTwo.hasWaterPark = true;
        System.out.println("Has Water Park: " + parkTwo.hasWaterPark);
        System.out.println();

        AmusementPark parkThree = new AmusementPark();
        parkThree.parkId = 3;
        System.out.println("Park ID: " + parkThree.parkId);
        parkThree.name = "Thrill Land";
        System.out.println("Name: " + parkThree.name);
        parkThree.location = "Tokyo, Japan";
        System.out.println("Location: " + parkThree.location);
        parkThree.yearEstablished = 1988;
        System.out.println("Year Established: " + parkThree.yearEstablished);
        parkThree.numberOfRides = 50;
        System.out.println("Number of Rides: " + parkThree.numberOfRides);
        parkThree.hasWaterPark = false;
        System.out.println("Has Water Park: " + parkThree.hasWaterPark);
        System.out.println();

        AmusementPark parkFour = new AmusementPark();
        parkFour.parkId = 4;
        System.out.println("Park ID: " + parkFour.parkId);
        parkFour.name = "Magic Fun Park";
        System.out.println("Name: " + parkFour.name);
        parkFour.location = "Paris, France";
        System.out.println("Location: " + parkFour.location);
        parkFour.yearEstablished = 1990;
        System.out.println("Year Established: " + parkFour.yearEstablished);
        parkFour.numberOfRides = 35;
        System.out.println("Number of Rides: " + parkFour.numberOfRides);
        parkFour.hasWaterPark = false;
        System.out.println("Has Water Park: " + parkFour.hasWaterPark);
        System.out.println();

        AmusementPark parkFive = new AmusementPark();
        parkFive.parkId = 5;
        System.out.println("Park ID: " + parkFive.parkId);
        parkFive.name = "Safari Splash";
        System.out.println("Name: " + parkFive.name);
        parkFive.location = "Cape Town, South Africa";
        System.out.println("Location: " + parkFive.location);
        parkFive.yearEstablished = 2005;
        System.out.println("Year Established: " + parkFive.yearEstablished);
        parkFive.numberOfRides = 25;
        System.out.println("Number of Rides: " + parkFive.numberOfRides);
        parkFive.hasWaterPark = true;
        System.out.println("Has Water Park: " + parkFive.hasWaterPark);
        System.out.println();

        AmusementPark parkSix = new AmusementPark();
        parkSix.parkId = 6;
        System.out.println("Park ID: " + parkSix.parkId);
        parkSix.name = "Ocean Joy";
        System.out.println("Name: " + parkSix.name);
        parkSix.location = "Sydney, Australia";
        System.out.println("Location: " + parkSix.location);
        parkSix.yearEstablished = 2010;
        System.out.println("Year Established: " + parkSix.yearEstablished);
        parkSix.numberOfRides = 20;
        System.out.println("Number of Rides: " + parkSix.numberOfRides);
        parkSix.hasWaterPark = true;
        System.out.println("Has Water Park: " + parkSix.hasWaterPark);
        System.out.println();

        AmusementPark parkSeven = new AmusementPark();
        parkSeven.parkId = 7;
        System.out.println("Park ID: " + parkSeven.parkId);
        parkSeven.name = "Dragon Island";
        System.out.println("Name: " + parkSeven.name);
        parkSeven.location = "Seoul, South Korea";
        System.out.println("Location: " + parkSeven.location);
        parkSeven.yearEstablished = 2001;
        System.out.println("Year Established: " + parkSeven.yearEstablished);
        parkSeven.numberOfRides = 38;
        System.out.println("Number of Rides: " + parkSeven.numberOfRides);
        parkSeven.hasWaterPark = false;
        System.out.println("Has Water Park: " + parkSeven.hasWaterPark);
        System.out.println();

        AmusementPark parkEight = new AmusementPark();
        parkEight.parkId = 8;
        System.out.println("Park ID: " + parkEight.parkId);
        parkEight.name = "Sky High Park";
        System.out.println("Name: " + parkEight.name);
        parkEight.location = "Toronto, Canada";
        System.out.println("Location: " + parkEight.location);
        parkEight.yearEstablished = 1998;
        System.out.println("Year Established: " + parkEight.yearEstablished);
        parkEight.numberOfRides = 45;
        System.out.println("Number of Rides: " + parkEight.numberOfRides);
        parkEight.hasWaterPark = true;
        System.out.println("Has Water Park: " + parkEight.hasWaterPark);
        System.out.println();

        AmusementPark parkNine = new AmusementPark();
        parkNine.parkId = 9;
        System.out.println("Park ID: " + parkNine.parkId);
        parkNine.name = "Roller Nation";
        System.out.println("Name: " + parkNine.name);
        parkNine.location = "Mumbai, India";
        System.out.println("Location: " + parkNine.location);
        parkNine.yearEstablished = 2015;
        System.out.println("Year Established: " + parkNine.yearEstablished);
        parkNine.numberOfRides = 32;
        System.out.println("Number of Rides: " + parkNine.numberOfRides);
        parkNine.hasWaterPark = false;
        System.out.println("Has Water Park: " + parkNine.hasWaterPark);
        System.out.println();

        AmusementPark parkTen = new AmusementPark();
        parkTen.parkId = 10;
        System.out.println("Park ID: " + parkTen.parkId);
        parkTen.name = "Extreme Zone";
        System.out.println("Name: " + parkTen.name);
        parkTen.location = "Berlin, Germany";
        System.out.println("Location: " + parkTen.location);
        parkTen.yearEstablished = 2000;
        System.out.println("Year Established: " + parkTen.yearEstablished);
        parkTen.numberOfRides = 28;
        System.out.println("Number of Rides: " + parkTen.numberOfRides);
        parkTen.hasWaterPark = false;
        System.out.println("Has Water Park: " + parkTen.hasWaterPark);
        System.out.println();

        AmusementPark parkEleven = new AmusementPark();
        parkEleven.parkId = 11;
        System.out.println("Park ID: " + parkEleven.parkId);
        parkEleven.name = "Galaxy Park";
        System.out.println("Name: " + parkEleven.name);
        parkEleven.location = "Bangkok, Thailand";
        System.out.println("Location: " + parkEleven.location);
        parkEleven.yearEstablished = 2009;
        System.out.println("Year Established: " + parkEleven.yearEstablished);
        parkEleven.numberOfRides = 36;
        System.out.println("Number of Rides: " + parkEleven.numberOfRides);
        parkEleven.hasWaterPark = true;
        System.out.println("Has Water Park: " + parkEleven.hasWaterPark);
        System.out.println();

        AmusementPark parkTwelve = new AmusementPark();
        parkTwelve.parkId = 12;
        System.out.println("Park ID: " + parkTwelve.parkId);
        parkTwelve.name = "Jungle Rush";
        System.out.println("Name: " + parkTwelve.name);
        parkTwelve.location = "Nairobi, Kenya";
        System.out.println("Location: " + parkTwelve.location);
        parkTwelve.yearEstablished = 2013;
        System.out.println("Year Established: " + parkTwelve.yearEstablished);
        parkTwelve.numberOfRides = 22;
        System.out.println("Number of Rides: " + parkTwelve.numberOfRides);
        parkTwelve.hasWaterPark = true;
        System.out.println("Has Water Park: " + parkTwelve.hasWaterPark);
        System.out.println();

        AmusementPark parkThirteen = new AmusementPark();
        parkThirteen.parkId = 13;
        System.out.println("Park ID: " + parkThirteen.parkId);
        parkThirteen.name = "Mega Funland";
        System.out.println("Name: " + parkThirteen.name);
        parkThirteen.location = "Rome, Italy";
        System.out.println("Location: " + parkThirteen.location);
        parkThirteen.yearEstablished = 2007;
        System.out.println("Year Established: " + parkThirteen.yearEstablished);
        parkThirteen.numberOfRides = 29;
        System.out.println("Number of Rides: " + parkThirteen.numberOfRides);
        parkThirteen.hasWaterPark = false;
        System.out.println("Has Water Park: " + parkThirteen.hasWaterPark);
        System.out.println();

        AmusementPark parkFourteen = new AmusementPark();
        parkFourteen.parkId = 14;
        System.out.println("Park ID: " + parkFourteen.parkId);
        parkFourteen.name = "River Splash Park";
        System.out.println("Name: " + parkFourteen.name);
        parkFourteen.location = "Shanghai, China";
        System.out.println("Location: " + parkFourteen.location);
        parkFourteen.yearEstablished = 2011;
        System.out.println("Year Established: " + parkFourteen.yearEstablished);
        parkFourteen.numberOfRides = 31;
        System.out.println("Number of Rides: " + parkFourteen.numberOfRides);
        parkFourteen.hasWaterPark = true;
        System.out.println("Has Water Park: " + parkFourteen.hasWaterPark);
        System.out.println();

        AmusementPark parkFifteen = new AmusementPark();
        parkFifteen.parkId = 15;
        System.out.println("Park ID: " + parkFifteen.parkId);
        parkFifteen.name = "Phoenix Land";
        System.out.println("Name: " + parkFifteen.name);
        parkFifteen.location = "Phoenix, USA";
        System.out.println("Location: " + parkFifteen.location);
        parkFifteen.yearEstablished = 2020;
        System.out.println("Year Established: " + parkFifteen.yearEstablished);
        parkFifteen.numberOfRides = 27;
        System.out.println("Number of Rides: " + parkFifteen.numberOfRides);
        parkFifteen.hasWaterPark = true;
        System.out.println("Has Water Park: " + parkFifteen.hasWaterPark);
        System.out.println();

        System.out.println("Main Ended");
    }
}