class BlazzerRunner{
    public static void main(String[] paper){
        System.out.println("Main Started");
        Blazzer blazzerOne=new Blazzer();
        blazzerOne.blazzerId=1;
        System.out.println("The Blazzer ID is:"+blazzerOne.blazzerId);
        blazzerOne.brandName="Raymond";
        System.out.println("Blazzer Brand Name :"+blazzerOne.brandName);
        blazzerOne.blazzerSize="s";
        System.out.println("Blazzer Size Is :"+blazzerOne.blazzerSize);
        blazzerOne.blazzerColour="Red";
        System.out.println("Blazzer Colour Is :"+blazzerOne.blazzerColour);
        blazzerOne.blazzerPrice=2500.00;
        System.out.println("Blazzer Price  :"+blazzerOne.blazzerPrice);
        blazzerOne.paymentMode="online";
        System.out.println("Payment Mode Is :"+blazzerOne.paymentMode);
        System.out.println("");
        System.out.println("");
        
        
        Blazzer blazzerTwo=new Blazzer();
        blazzerTwo.blazzerId=2;
        System.out.println("The Blazzer ID is:"+blazzerTwo.blazzerId);
        blazzerTwo.brandName="Van Heusen";
        System.out.println("Blazzer Brand Name :"+blazzerTwo.brandName);
        blazzerTwo.blazzerSize="m";
        System.out.println("Blazzer Size Is :"+blazzerTwo.blazzerSize);
        blazzerTwo.blazzerColour="Blue";
        System.out.println("Blazzer Colour Is :"+blazzerTwo.blazzerColour);
        blazzerTwo.blazzerPrice=3000.00;
        System.out.println("Blazzer Price  :"+blazzerTwo.blazzerPrice);
        blazzerTwo.paymentMode="online";
        System.out.println("Payment Mode Is :"+blazzerTwo.paymentMode);
        System.out.println("");
        System.out.println("");

        
       Blazzer blazzerThree = new Blazzer();
        blazzerThree.blazzerId = 3;
        System.out.println("The Blazzer ID is:" + blazzerThree.blazzerId);
        blazzerThree.brandName = "Peter England";
        System.out.println("Blazzer Brand Name :" + blazzerThree.brandName);
        blazzerThree.blazzerSize = "l";
        System.out.println("Blazzer Size Is :" + blazzerThree.blazzerSize);
        blazzerThree.blazzerColour = "Black";
        System.out.println("Blazzer Colour Is :" + blazzerThree.blazzerColour);
        blazzerThree.blazzerPrice = 3200.00;
        System.out.println("Blazzer Price  :" + blazzerThree.blazzerPrice);
        blazzerThree.paymentMode = "cash";
        System.out.println("Payment Mode Is :" + blazzerThree.paymentMode);
        System.out.println("");
        System.out.println("");

        Blazzer blazzerFour = new Blazzer();
        blazzerFour.blazzerId = 4;
        System.out.println("The Blazzer ID is:" + blazzerFour.blazzerId);
        blazzerFour.brandName = "Allen Solly";
        System.out.println("Blazzer Brand Name :" + blazzerFour.brandName);
        blazzerFour.blazzerSize = "xl";
        System.out.println("Blazzer Size Is :" + blazzerFour.blazzerSize);
        blazzerFour.blazzerColour = "Grey";
        System.out.println("Blazzer Colour Is :" + blazzerFour.blazzerColour);
        blazzerFour.blazzerPrice = 4000.00;
        System.out.println("Blazzer Price  :" + blazzerFour.blazzerPrice);
        blazzerFour.paymentMode = "card";
        System.out.println("Payment Mode Is :" + blazzerFour.paymentMode);
        System.out.println("");
        System.out.println("");

        Blazzer blazzerFive = new Blazzer();
        blazzerFive.blazzerId = 5;
        System.out.println("The Blazzer ID is:" + blazzerFive.blazzerId);
        blazzerFive.brandName = "Blackberrys";
        System.out.println("Blazzer Brand Name :" + blazzerFive.brandName);
        blazzerFive.blazzerSize = "m";
        System.out.println("Blazzer Size Is :" + blazzerFive.blazzerSize);
        blazzerFive.blazzerColour = "Brown";
        System.out.println("Blazzer Colour Is :" + blazzerFive.blazzerColour);
        blazzerFive.blazzerPrice = 3500.00;
        System.out.println("Blazzer Price  :" + blazzerFive.blazzerPrice);
        blazzerFive.paymentMode = "online";
        System.out.println("Payment Mode Is :" + blazzerFive.paymentMode);
        System.out.println("");
        System.out.println("");

        Blazzer blazzerSix = new Blazzer();
        blazzerSix.blazzerId = 6;
        System.out.println("The Blazzer ID is:" + blazzerSix.blazzerId);
        blazzerSix.brandName = "Louis Philippe";
        System.out.println("Blazzer Brand Name :" + blazzerSix.brandName);
        blazzerSix.blazzerSize = "s";
        System.out.println("Blazzer Size Is :" + blazzerSix.blazzerSize);
        blazzerSix.blazzerColour = "Navy";
        System.out.println("Blazzer Colour Is :" + blazzerSix.blazzerColour);
        blazzerSix.blazzerPrice = 4500.00;
        System.out.println("Blazzer Price  :" + blazzerSix.blazzerPrice);
        blazzerSix.paymentMode = "upi";
        System.out.println("Payment Mode Is :" + blazzerSix.paymentMode);
        System.out.println("");
        System.out.println("");

        Blazzer blazzerSeven = new Blazzer();
        blazzerSeven.blazzerId = 7;
        System.out.println("The Blazzer ID is:" + blazzerSeven.blazzerId);
        blazzerSeven.brandName = "Zara";
        System.out.println("Blazzer Brand Name :" + blazzerSeven.brandName);
        blazzerSeven.blazzerSize = "xs";
        System.out.println("Blazzer Size Is :" + blazzerSeven.blazzerSize);
        blazzerSeven.blazzerColour = "White";
        System.out.println("Blazzer Colour Is :" + blazzerSeven.blazzerColour);
        blazzerSeven.blazzerPrice = 4800.00;
        System.out.println("Blazzer Price  :" + blazzerSeven.blazzerPrice);
        blazzerSeven.paymentMode = "cash";
        System.out.println("Payment Mode Is :" + blazzerSeven.paymentMode);
        System.out.println("");
        System.out.println("");

        Blazzer blazzerEight = new Blazzer();
        blazzerEight.blazzerId = 8;
        System.out.println("The Blazzer ID is:" + blazzerEight.blazzerId);
        blazzerEight.brandName = "H&M";
        System.out.println("Blazzer Brand Name :" + blazzerEight.brandName);
        blazzerEight.blazzerSize = "l";
        System.out.println("Blazzer Size Is :" + blazzerEight.blazzerSize);
        blazzerEight.blazzerColour = "Green";
        System.out.println("Blazzer Colour Is :" + blazzerEight.blazzerColour);
        blazzerEight.blazzerPrice = 3300.00;
        System.out.println("Blazzer Price  :" + blazzerEight.blazzerPrice);
        blazzerEight.paymentMode = "online";
        System.out.println("Payment Mode Is :" + blazzerEight.paymentMode);
        System.out.println("");
        System.out.println("");

        Blazzer blazzerNine = new Blazzer();
        blazzerNine.blazzerId = 9;
        System.out.println("The Blazzer ID is:" + blazzerNine.blazzerId);
        blazzerNine.brandName = "Uniqlo";
        System.out.println("Blazzer Brand Name :" + blazzerNine.brandName);
        blazzerNine.blazzerSize = "m";
        System.out.println("Blazzer Size Is :" + blazzerNine.blazzerSize);
        blazzerNine.blazzerColour = "Maroon";
        System.out.println("Blazzer Colour Is :" + blazzerNine.blazzerColour);
        blazzerNine.blazzerPrice = 3100.00;
        System.out.println("Blazzer Price  :" + blazzerNine.blazzerPrice);
        blazzerNine.paymentMode = "card";
        System.out.println("Payment Mode Is :" + blazzerNine.paymentMode);
        System.out.println("");
        System.out.println("");

        Blazzer blazzerTen = new Blazzer();
        blazzerTen.blazzerId = 10;
        System.out.println("The Blazzer ID is:" + blazzerTen.blazzerId);
        blazzerTen.brandName = "Marks & Spencer";
        System.out.println("Blazzer Brand Name :" + blazzerTen.brandName);
        blazzerTen.blazzerSize = "xxl";
        System.out.println("Blazzer Size Is :" + blazzerTen.blazzerSize);
        blazzerTen.blazzerColour = "Black";
        System.out.println("Blazzer Colour Is :" + blazzerTen.blazzerColour);
        blazzerTen.blazzerPrice = 5000.00;
        System.out.println("Blazzer Price  :" + blazzerTen.blazzerPrice);
        blazzerTen.paymentMode = "upi";
        System.out.println("Payment Mode Is :" + blazzerTen.paymentMode);
        System.out.println("");
        System.out.println("");

        Blazzer blazzerEleven = new Blazzer();
        blazzerEleven.blazzerId = 11;
        System.out.println("The Blazzer ID is:" + blazzerEleven.blazzerId);
        blazzerEleven.brandName = "GAP";
        System.out.println("Blazzer Brand Name :" + blazzerEleven.brandName);
        blazzerEleven.blazzerSize = "s";
        System.out.println("Blazzer Size Is :" + blazzerEleven.blazzerSize);
        blazzerEleven.blazzerColour = "Pink";
        System.out.println("Blazzer Colour Is :" + blazzerEleven.blazzerColour);
        blazzerEleven.blazzerPrice = 3600.00;
        System.out.println("Blazzer Price  :" + blazzerEleven.blazzerPrice);
        blazzerEleven.paymentMode = "cash";
        System.out.println("Payment Mode Is :" + blazzerEleven.paymentMode);
        System.out.println("");

        Blazzer blazzerTwelve = new Blazzer();
        blazzerTwelve.blazzerId = 12;   
        System.out.println("The Blazzer ID is:" + blazzerTwelve.blazzerId);
        blazzerTwelve.brandName = "Tommy Hilfiger";
        System.out.println("Blazzer Brand Name :" + blazzerTwelve.brandName);
        blazzerTwelve.blazzerSize = "m";
        System.out.println("Blazzer Size Is :" + blazzerTwelve.blazzerSize);
        blazzerTwelve.blazzerColour = "Navy Blue";
        System.out.println("Blazzer Colour Is :" + blazzerTwelve.blazzerColour);
        blazzerTwelve.blazzerPrice = 5500.00;
        System.out.println("Blazzer Price  :" + blazzerTwelve.blazzerPrice);
        blazzerTwelve.paymentMode = "online";
        System.out.println("Payment Mode Is :" + blazzerTwelve.paymentMode);
        System.out.println("");

        Blazzer blazzerThirteen = new Blazzer();
        blazzerThirteen.blazzerId = 13;
        System.out.println("The Blazzer ID is:" + blazzerThirteen.blazzerId);
        blazzerThirteen.brandName = "Calvin Klein";
        System.out.println("Blazzer Brand Name :" + blazzerThirteen.brandName);
        blazzerThirteen.blazzerSize = "l";
        System.out.println("Blazzer Size Is :" + blazzerThirteen.blazzerSize);
        blazzerThirteen.blazzerColour = "Charcoal";
        System.out.println("Blazzer Colour Is :" + blazzerThirteen.blazzerColour);
        blazzerThirteen.blazzerPrice = 6000.00;
        System.out.println("Blazzer Price  :" + blazzerThirteen.blazzerPrice);
        blazzerThirteen.paymentMode = "card";
        System.out.println("Payment Mode Is :" + blazzerThirteen.paymentMode);
        System.out.println("");

        Blazzer blazzerFourteen = new Blazzer();
        blazzerFourteen.blazzerId = 14;
        System.out.println("The Blazzer ID is:" + blazzerFourteen.blazzerId);
        blazzerFourteen.brandName = "Diesel";
        System.out.println("Blazzer Brand Name :" + blazzerFourteen.brandName);
        blazzerFourteen.blazzerSize = "xl";
        System.out.println("Blazzer Size Is :" + blazzerFourteen.blazzerSize);
        blazzerFourteen.blazzerColour = "Olive";
        System.out.println("Blazzer Colour Is :" + blazzerFourteen.blazzerColour);
        blazzerFourteen.blazzerPrice = 7000.00;
        System.out.println("Blazzer Price  :" + blazzerFourteen.blazzerPrice);
        blazzerFourteen.paymentMode = "upi";
        System.out.println("Payment Mode Is :" + blazzerFourteen.paymentMode);
        System.out.println("");
       
        Blazzer blazzerFifteen = new Blazzer();
        blazzerFifteen.blazzerId = 15;
        System.out.println("The Blazzer ID is:" + blazzerFifteen.blazzerId);
        blazzerFifteen.brandName = "Arrow";
        System.out.println("Blazzer Brand Name :" + blazzerFifteen.brandName);
        blazzerFifteen.blazzerSize = "m";
        System.out.println("Blazzer Size Is :" + blazzerFifteen.blazzerSize);
        blazzerFifteen.blazzerColour = "Cream";
        System.out.println("Blazzer Colour Is :" + blazzerFifteen.blazzerColour);
        blazzerFifteen.blazzerPrice = 3800.00;
        System.out.println("Blazzer Price  :" + blazzerFifteen.blazzerPrice);
        blazzerFifteen.paymentMode = "cash";
        System.out.println("Payment Mode Is :" + blazzerFifteen.paymentMode);
        System.out.println("");

        Blazzer blazzerSixteen = new Blazzer();
        blazzerSixteen.blazzerId = 16;
        System.out.println("The Blazzer ID is:" + blazzerSixteen.blazzerId);
        blazzerSixteen.brandName = "Superdry";
        System.out.println("Blazzer Brand Name :" + blazzerSixteen.brandName);
        blazzerSixteen.blazzerSize = "s";
        System.out.println("Blazzer Size Is :" + blazzerSixteen.blazzerSize);
        blazzerSixteen.blazzerColour = "Teal";
        System.out.println("Blazzer Colour Is :" + blazzerSixteen.blazzerColour);
        blazzerSixteen.blazzerPrice = 4200.00;
        System.out.println("Blazzer Price  :" + blazzerSixteen.blazzerPrice);
        blazzerSixteen.paymentMode = "online";
        System.out.println("Payment Mode Is :" + blazzerSixteen.paymentMode);
        System.out.println("");

        Blazzer blazzerSeventeen = new Blazzer();
        blazzerSeventeen.blazzerId = 17;
        System.out.println("The Blazzer ID is:" + blazzerSeventeen.blazzerId);
        blazzerSeventeen.brandName = "Gant";
        System.out.println("Blazzer Brand Name :" + blazzerSeventeen.brandName);
        blazzerSeventeen.blazzerSize = "l";
        System.out.println("Blazzer Size Is :" + blazzerSeventeen.blazzerSize);
        blazzerSeventeen.blazzerColour = "Burgundy";
        System.out.println("Blazzer Colour Is :" + blazzerSeventeen.blazzerColour);
        blazzerSeventeen.blazzerPrice = 5200.00;
        System.out.println("Blazzer Price  :" + blazzerSeventeen.blazzerPrice);
        blazzerSeventeen.paymentMode = "card";
        System.out.println("Payment Mode Is :" + blazzerSeventeen.paymentMode);
        System.out.println("");

        Blazzer blazzerEighteen = new Blazzer();
        blazzerEighteen.blazzerId = 18;
        System.out.println("The Blazzer ID is:" + blazzerEighteen.blazzerId);
        blazzerEighteen.brandName = "Ted Baker";
        System.out.println("Blazzer Brand Name :" + blazzerEighteen.brandName);
        blazzerEighteen.blazzerSize = "xl";
        System.out.println("Blazzer Size Is :" + blazzerEighteen.blazzerSize);
        blazzerEighteen.blazzerColour = "Slate";
        System.out.println("Blazzer Colour Is :" + blazzerEighteen.blazzerColour);
        blazzerEighteen.blazzerPrice = 8000.00;
        System.out.println("Blazzer Price  :" + blazzerEighteen.blazzerPrice);
        blazzerEighteen.paymentMode = "upi";
        System.out.println("Payment Mode Is :" + blazzerEighteen.paymentMode);
        System.out.println("");

        Blazzer blazzerNineteen = new Blazzer();
        blazzerNineteen.blazzerId = 19;
        System.out.println("The Blazzer ID is:" + blazzerNineteen.blazzerId);
        blazzerNineteen.brandName = "Reiss";
        System.out.println("Blazzer Brand Name :" + blazzerNineteen.brandName);
        blazzerNineteen.blazzerSize = "xxl";
        System.out.println("Blazzer Size Is :" + blazzerNineteen.blazzerSize);
        blazzerNineteen.blazzerColour = "Ash";
        System.out.println("Blazzer Colour Is :" + blazzerNineteen.blazzerColour);
        blazzerNineteen.blazzerPrice = 9000.00;
        System.out.println("Blazzer Price  :" + blazzerNineteen.blazzerPrice);
        blazzerNineteen.paymentMode = "cash";
        System.out.println("Payment Mode Is :" + blazzerNineteen.paymentMode);
        System.out.println("");

        Blazzer blazzerTwenty = new Blazzer();
        blazzerTwenty.blazzerId = 20;
        System.out.println("The Blazzer ID is:" + blazzerTwenty.blazzerId);
        blazzerTwenty.brandName = "Burberry";
        System.out.println("Blazzer Brand Name :" + blazzerTwenty.brandName);
        blazzerTwenty.blazzerSize = "s";
        System.out.println("Blazzer Size Is :" + blazzerTwenty.blazzerSize);
        blazzerTwenty.blazzerColour = "Cream";
        System.out.println("Blazzer Colour Is :" + blazzerTwenty.blazzerColour);
        blazzerTwenty.blazzerPrice = 12000.00;
        System.out.println("Blazzer Price  :" + blazzerTwenty.blazzerPrice);
        blazzerTwenty.paymentMode = "online";
        System.out.println("Payment Mode Is :" + blazzerTwenty.paymentMode);
        System.out.println("");

        System.out.println("Main Ended");


    }

}