class CasinoRunner {
    public static void main(String[] args) {
        System.out.println("Main Started");

        Casino casinoOne = new Casino();
        casinoOne.casinoId = 1;
        System.out.println("Casino ID: " + casinoOne.casinoId);
        casinoOne.name = "Golden Nugget";
        System.out.println("Name: " + casinoOne.name);
        casinoOne.location = "Las Vegas";
        System.out.println("Location: " + casinoOne.location);
        casinoOne.totalGames = 150;
        System.out.println("Total Games: " + casinoOne.totalGames);
        casinoOne.isOpen24Hours = true;
        System.out.println("Open 24 Hours: " + casinoOne.isOpen24Hours);
        casinoOne.entryFee = 50.0;
        System.out.println("Entry Fee: " + casinoOne.entryFee);
        casinoOne.owner = "John Smith";
        System.out.println("Owner: " + casinoOne.owner);
        casinoOne.paymentMode = "Cash";
        System.out.println("Payment Mode: " + casinoOne.paymentMode);
        System.out.println();

        Casino casinoTwo = new Casino();
        casinoTwo.casinoId = 2;
        System.out.println("Casino ID: " + casinoTwo.casinoId);
        casinoTwo.name = "Bellagio";
        System.out.println("Name: " + casinoTwo.name);
        casinoTwo.location = "Nevada";
        System.out.println("Location: " + casinoTwo.location);
        casinoTwo.totalGames = 300;
        System.out.println("Total Games: " + casinoTwo.totalGames);
        casinoTwo.isOpen24Hours = true;
        System.out.println("Open 24 Hours: " + casinoTwo.isOpen24Hours);
        casinoTwo.entryFee = 70.0;
        System.out.println("Entry Fee: " + casinoTwo.entryFee);
        casinoTwo.owner = "Lynda Cooper";
        System.out.println("Owner: " + casinoTwo.owner);
        casinoTwo.paymentMode = "Card";
        System.out.println("Payment Mode: " + casinoTwo.paymentMode);
        System.out.println();

        Casino casinoThree = new Casino();
        casinoThree.casinoId = 3;
        System.out.println("Casino ID: " + casinoThree.casinoId);
        casinoThree.name = "Caesars Palace";
        System.out.println("Name: " + casinoThree.name);
        casinoThree.location = "Las Vegas";
        System.out.println("Location: " + casinoThree.location);
        casinoThree.totalGames = 280;
        System.out.println("Total Games: " + casinoThree.totalGames);
        casinoThree.isOpen24Hours = false;
        System.out.println("Open 24 Hours: " + casinoThree.isOpen24Hours);
        casinoThree.entryFee = 65.0;
        System.out.println("Entry Fee: " + casinoThree.entryFee);
        casinoThree.owner = "Alan Young";
        System.out.println("Owner: " + casinoThree.owner);
        casinoThree.paymentMode = "Online";
        System.out.println("Payment Mode: " + casinoThree.paymentMode);
        System.out.println();

        Casino casinoFour = new Casino();
        casinoFour.casinoId = 4;
        System.out.println("Casino ID: " + casinoFour.casinoId);
        casinoFour.name = "MGM Grand";
        System.out.println("Name: " + casinoFour.name);
        casinoFour.location = "Las Vegas";
        System.out.println("Location: " + casinoFour.location);
        casinoFour.totalGames = 350;
        System.out.println("Total Games: " + casinoFour.totalGames);
        casinoFour.isOpen24Hours = true;
        System.out.println("Open 24 Hours: " + casinoFour.isOpen24Hours);
        casinoFour.entryFee = 80.0;
        System.out.println("Entry Fee: " + casinoFour.entryFee);
        casinoFour.owner = "Diane Rowe";
        System.out.println("Owner: " + casinoFour.owner);
        casinoFour.paymentMode = "Cash";
        System.out.println("Payment Mode: " + casinoFour.paymentMode);
        System.out.println();

        Casino casinoFive = new Casino();
        casinoFive.casinoId = 5;
        System.out.println("Casino ID: " + casinoFive.casinoId);
        casinoFive.name = "The Mirage";
        System.out.println("Name: " + casinoFive.name);
        casinoFive.location = "Nevada";
        System.out.println("Location: " + casinoFive.location);
        casinoFive.totalGames = 220;
        System.out.println("Total Games: " + casinoFive.totalGames);
        casinoFive.isOpen24Hours = true;
        System.out.println("Open 24 Hours: " + casinoFive.isOpen24Hours);
        casinoFive.entryFee = 55.0;
        System.out.println("Entry Fee: " + casinoFive.entryFee);
        casinoFive.owner = "Carla Dean";
        System.out.println("Owner: " + casinoFive.owner);
        casinoFive.paymentMode = "Card";
        System.out.println("Payment Mode: " + casinoFive.paymentMode);
        System.out.println();

        Casino casinoSix = new Casino();
        casinoSix.casinoId = 6;
        System.out.println("Casino ID: " + casinoSix.casinoId);
        casinoSix.name = "Resorts World";
        System.out.println("Name: " + casinoSix.name);
        casinoSix.location = "Singapore";
        System.out.println("Location: " + casinoSix.location);
        casinoSix.totalGames = 170;
        System.out.println("Total Games: " + casinoSix.totalGames);
        casinoSix.isOpen24Hours = false;
        System.out.println("Open 24 Hours: " + casinoSix.isOpen24Hours);
        casinoSix.entryFee = 90.0;
        System.out.println("Entry Fee: " + casinoSix.entryFee);
        casinoSix.owner = "Lee Kuan";
        System.out.println("Owner: " + casinoSix.owner);
        casinoSix.paymentMode = "Online";
        System.out.println("Payment Mode: " + casinoSix.paymentMode);
        System.out.println();

        Casino casinoSeven = new Casino();
        casinoSeven.casinoId = 7;
        System.out.println("Casino ID: " + casinoSeven.casinoId);
        casinoSeven.name = "Venetian Macao";
        System.out.println("Name: " + casinoSeven.name);
        casinoSeven.location = "Macao";
        System.out.println("Location: " + casinoSeven.location);
        casinoSeven.totalGames = 450;
        System.out.println("Total Games: " + casinoSeven.totalGames);
        casinoSeven.isOpen24Hours = true;
        System.out.println("Open 24 Hours: " + casinoSeven.isOpen24Hours);
        casinoSeven.entryFee = 100.0;
        System.out.println("Entry Fee: " + casinoSeven.entryFee);
        casinoSeven.owner = "Chen Li";
        System.out.println("Owner: " + casinoSeven.owner);
        casinoSeven.paymentMode = "Cash";
        System.out.println("Payment Mode: " + casinoSeven.paymentMode);
        System.out.println();

        Casino casinoEight = new Casino();
        casinoEight.casinoId = 8;
        System.out.println("Casino ID: " + casinoEight.casinoId);
        casinoEight.name = "Marina Bay Sands";
        System.out.println("Name: " + casinoEight.name);
        casinoEight.location = "Singapore";
        System.out.println("Location: " + casinoEight.location);
        casinoEight.totalGames = 390;
        System.out.println("Total Games: " + casinoEight.totalGames);
        casinoEight.isOpen24Hours = false;
        System.out.println("Open 24 Hours: " + casinoEight.isOpen24Hours);
        casinoEight.entryFee = 120.0;
        System.out.println("Entry Fee: " + casinoEight.entryFee);
        casinoEight.owner = "Sands Corp";
        System.out.println("Owner: " + casinoEight.owner);
        casinoEight.paymentMode = "Card";
        System.out.println("Payment Mode: " + casinoEight.paymentMode);
        System.out.println();

        Casino casinoNine = new Casino();
        casinoNine.casinoId = 9;
        System.out.println("Casino ID: " + casinoNine.casinoId);
        casinoNine.name = "Monte Carlo";
        System.out.println("Name: " + casinoNine.name);
        casinoNine.location = "Monaco";
        System.out.println("Location: " + casinoNine.location);
        casinoNine.totalGames = 180;
        System.out.println("Total Games: " + casinoNine.totalGames);
        casinoNine.isOpen24Hours = true;
        System.out.println("Open 24 Hours: " + casinoNine.isOpen24Hours);
        casinoNine.entryFee = 95.0;
        System.out.println("Entry Fee: " + casinoNine.entryFee);
        casinoNine.owner = "Prince Albert";
        System.out.println("Owner: " + casinoNine.owner);
        casinoNine.paymentMode = "Online";
        System.out.println("Payment Mode: " + casinoNine.paymentMode);
        System.out.println();

        Casino casinoTen = new Casino();
        casinoTen.casinoId = 10;
        System.out.println("Casino ID: " + casinoTen.casinoId);
        casinoTen.name = "Galaxy Macau";
        System.out.println("Name: " + casinoTen.name);
        casinoTen.location = "Macao";
        System.out.println("Location: " + casinoTen.location);
        casinoTen.totalGames = 275;
        System.out.println("Total Games: " + casinoTen.totalGames);
        casinoTen.isOpen24Hours = true;
        System.out.println("Open 24 Hours: " + casinoTen.isOpen24Hours);
        casinoTen.entryFee = 85.0;
        System.out.println("Entry Fee: " + casinoTen.entryFee);
        casinoTen.owner = "Galaxy Entertainment";
        System.out.println("Owner: " + casinoTen.owner);
        casinoTen.paymentMode = "Card";
        System.out.println("Payment Mode: " + casinoTen.paymentMode);
        System.out.println();

        System.out.println("Main Ended");
    }
}