class CourtcaseRunner {
    public static void main(String[] args) {
        System.out.println("Main Started");

        Courtcase c1 = new Courtcase();
        c1.caseId = 1;
        System.out.println("Case ID: " + c1.caseId);
        c1.caseName = "Property Dispute";
        System.out.println("Case Name: " + c1.caseName);
        c1.plaintiff = "John Doe";
        System.out.println("Plaintiff: " + c1.plaintiff);
        c1.defendant = "Jane Smith";
        System.out.println("Defendant: " + c1.defendant);
        c1.courtName = "Supreme Court";
        System.out.println("Court Name: " + c1.courtName);
        c1.status = "Pending";
        System.out.println("Status: " + c1.status);
        c1.caseValue = 1000000.00;
        System.out.println("Case Value: $" + c1.caseValue);
        c1.paymentMode = "Online";
        System.out.println("Payment Mode: " + c1.paymentMode);
        System.out.println();

        Courtcase c2 = new Courtcase();
        c2.caseId = 2;
        System.out.println("Case ID: " + c2.caseId);
        c2.caseName = "Contract Breach";
        System.out.println("Case Name: " + c2.caseName);
        c2.plaintiff = "Alice Cooper";
        System.out.println("Plaintiff: " + c2.plaintiff);
        c2.defendant = "Bob Marley";
        System.out.println("Defendant: " + c2.defendant);
        c2.courtName = "District Court";
        System.out.println("Court Name: " + c2.courtName);
        c2.status = "Closed";
        System.out.println("Status: " + c2.status);
        c2.caseValue = 500000.00;
        System.out.println("Case Value: $" + c2.caseValue);
        c2.paymentMode = "Cash";
        System.out.println("Payment Mode: " + c2.paymentMode);
        System.out.println();

        Courtcase c3 = new Courtcase();
        c3.caseId = 3;
        System.out.println("Case ID: " + c3.caseId);
        c3.caseName = "Personal Injury";
        System.out.println("Case Name: " + c3.caseName);
        c3.plaintiff = "Mary Johnson";
        System.out.println("Plaintiff: " + c3.plaintiff);
        c3.defendant = "David Wilson";
        System.out.println("Defendant: " + c3.defendant);
        c3.courtName = "High Court";
        System.out.println("Court Name: " + c3.courtName);
        c3.status = "Ongoing";
        System.out.println("Status: " + c3.status);
        c3.caseValue = 200000.00;
        System.out.println("Case Value: $" + c3.caseValue);
        c3.paymentMode = "Card";
        System.out.println("Payment Mode: " + c3.paymentMode);
        System.out.println();

        Courtcase c4 = new Courtcase();
        c4.caseId = 4;
        System.out.println("Case ID: " + c4.caseId);
        c4.caseName = "Criminal Defense";
        System.out.println("Case Name: " + c4.caseName);
        c4.plaintiff = "State";
        System.out.println("Plaintiff: " + c4.plaintiff);
        c4.defendant = "James Bond";
        System.out.println("Defendant: " + c4.defendant);
        c4.courtName = "Supreme Court";
        System.out.println("Court Name: " + c4.courtName);
        c4.status = "Pending";
        System.out.println("Status: " + c4.status);
        c4.caseValue = 0.00;
        System.out.println("Case Value: $" + c4.caseValue);
        c4.paymentMode = "Online";
        System.out.println("Payment Mode: " + c4.paymentMode);
        System.out.println();

        Courtcase c5 = new Courtcase();
        c5.caseId = 5;
        System.out.println("Case ID: " + c5.caseId);
        c5.caseName = "Divorce Settlement";
        System.out.println("Case Name: " + c5.caseName);
        c5.plaintiff = "Anna Bell";
        System.out.println("Plaintiff: " + c5.plaintiff);
        c5.defendant = "Mark Bell";
        System.out.println("Defendant: " + c5.defendant);
        c5.courtName = "Family Court";
        System.out.println("Court Name: " + c5.courtName);
        c5.status = "Closed";
        System.out.println("Status: " + c5.status);
        c5.caseValue = 250000.00;
        System.out.println("Case Value: $" + c5.caseValue);
        c5.paymentMode = "Cash";
        System.out.println("Payment Mode: " + c5.paymentMode);
        System.out.println();

        Courtcase c6 = new Courtcase();
        c6.caseId = 6;
        System.out.println("Case ID: " + c6.caseId);
        c6.caseName = "Intellectual Property";
        System.out.println("Case Name: " + c6.caseName);
        c6.plaintiff = "TechCorp";
        System.out.println("Plaintiff: " + c6.plaintiff);
        c6.defendant = "InnoSoft";
        System.out.println("Defendant: " + c6.defendant);
        c6.courtName = "District Court";
        System.out.println("Court Name: " + c6.courtName);
        c6.status = "Ongoing";
        System.out.println("Status: " + c6.status);
        c6.caseValue = 1500000.00;
        System.out.println("Case Value: $" + c6.caseValue);
        c6.paymentMode = "Card";
        System.out.println("Payment Mode: " + c6.paymentMode);
        System.out.println();

        Courtcase c7 = new Courtcase();
        c7.caseId = 7;
        System.out.println("Case ID: " + c7.caseId);
        c7.caseName = "Employment Dispute";
        System.out.println("Case Name: " + c7.caseName);
        c7.plaintiff = "Worker Union";
        System.out.println("Plaintiff: " + c7.plaintiff);
        c7.defendant = "Global Industries";
        System.out.println("Defendant: " + c7.defendant);
        c7.courtName = "Labor Court";
        System.out.println("Court Name: " + c7.courtName);
        c7.status = "Pending";
        System.out.println("Status: " + c7.status);
        c7.caseValue = 300000.00;
        System.out.println("Case Value: $" + c7.caseValue);
        c7.paymentMode = "Online";
        System.out.println("Payment Mode: " + c7.paymentMode);
        System.out.println();

        Courtcase c8 = new Courtcase();
        c8.caseId = 8;
        System.out.println("Case ID: " + c8.caseId);
        c8.caseName = "Tax Evasion";
        System.out.println("Case Name: " + c8.caseName);
        c8.plaintiff = "Government";
        System.out.println("Plaintiff: " + c8.plaintiff);
        c8.defendant = "XYZ Corp";
        System.out.println("Defendant: " + c8.defendant);
        c8.courtName = "Supreme Court";
        System.out.println("Court Name: " + c8.courtName);
        c8.status = "Closed";
        System.out.println("Status: " + c8.status);
        c8.caseValue = 2000000.00;
        System.out.println("Case Value: $" + c8.caseValue);
        c8.paymentMode = "Cash";
        System.out.println("Payment Mode: " + c8.paymentMode);
        System.out.println();

        Courtcase c9 = new Courtcase();
        c9.caseId = 9;
        System.out.println("Case ID: " + c9.caseId);
        c9.caseName = "Consumer Rights";
        System.out.println("Case Name: " + c9.caseName);
        c9.plaintiff = "Consumer Union";
        System.out.println("Plaintiff: " + c9.plaintiff);
        c9.defendant = "Retail Corp";
        System.out.println("Defendant: " + c9.defendant);
        c9.courtName = "District Court";
        System.out.println("Court Name: " + c9.courtName);
        c9.status = "Ongoing";
        System.out.println("Status: " + c9.status);
        c9.caseValue = 400000.00;
        System.out.println("Case Value: $" + c9.caseValue);
        c9.paymentMode = "Card";
        System.out.println("Payment Mode: " + c9.paymentMode);
        System.out.println();

        Courtcase c10 = new Courtcase();
        c10.caseId = 10;
        System.out.println("Case ID: " + c10.caseId);
        c10.caseName = "Environmental Violation";
        System.out.println("Case Name: " + c10.caseName);
        c10.plaintiff = "EPA";
        System.out.println("Plaintiff: " + c10.plaintiff);
        c10.defendant = "Factory Inc.";
        System.out.println("Defendant: " + c10.defendant);
        c10.courtName = "High Court";
        System.out.println("Court Name: " + c10.courtName);
        c10.status = "Pending";
        System.out.println("Status: " + c10.status);
        c10.caseValue = 1200000.00;
        System.out.println("Case Value: $" + c10.caseValue);
        c10.paymentMode = "Online";
        System.out.println("Payment Mode: " + c10.paymentMode);
        System.out.println();

        Courtcase c11 = new Courtcase();
        c11.caseId = 11;
        System.out.println("Case ID: " + c11.caseId);
        c11.caseName = "Fraud Case";
        System.out.println("Case Name: " + c11.caseName);
        c11.plaintiff = "State";
        System.out.println("Plaintiff: " + c11.plaintiff);
        c11.defendant = "Michael Scott";
        System.out.println("Defendant: " + c11.defendant);
        c11.courtName = "District Court";
        System.out.println("Court Name: " + c11.courtName);
        c11.status = "Closed";
        System.out.println("Status: " + c11.status);
        c11.caseValue = 800000.00;
        System.out.println("Case Value: $" + c11.caseValue);
        c11.paymentMode = "Cash";
        System.out.println("Payment Mode: " + c11.paymentMode);
        System.out.println();

        Courtcase c12 = new Courtcase();
        c12.caseId = 12;
        System.out.println("Case ID: " + c12.caseId);
        c12.caseName = "Defamation";
        System.out.println("Case Name: " + c12.caseName);
        c12.plaintiff = "Linda Grey";
        System.out.println("Plaintiff: " + c12.plaintiff);
        c12.defendant = "Tom Hanks";
        System.out.println("Defendant: " + c12.defendant);
        c12.courtName = "High Court";
        System.out.println("Court Name: " + c12.courtName);
        c12.status = "Ongoing";
        System.out.println("Status: " + c12.status);
        c12.caseValue = 150000.00;
        System.out.println("Case Value: $" + c12.caseValue);
        c12.paymentMode = "Card";
        System.out.println("Payment Mode: " + c12.paymentMode);
        System.out.println();

        Courtcase c13 = new Courtcase();
        c13.caseId = 13;
        System.out.println("Case ID: " + c13.caseId);
        c13.caseName = "Bankruptcy";
        System.out.println("Case Name: " + c13.caseName);
        c13.plaintiff = "Big Bank";
        System.out.println("Plaintiff: " + c13.plaintiff);
        c13.defendant = "StartUp Ltd";
        System.out.println("Defendant: " + c13.defendant);
        c13.courtName = "District Court";
        System.out.println("Court Name: " + c13.courtName);
        c13.status = "Pending";
        System.out.println("Status: " + c13.status);
        c13.caseValue = 750000.00;
        System.out.println("Case Value: $" + c13.caseValue);
        c13.paymentMode = "Online";
        System.out.println("Payment Mode: " + c13.paymentMode);
        System.out.println();

        Courtcase c14 = new Courtcase();
        c14.caseId = 14;
        System.out.println("Case ID: " + c14.caseId);
        c14.caseName = "Breach of Trust";
        System.out.println("Case Name: " + c14.caseName);
        c14.plaintiff = "Investor Group";
        System.out.println("Plaintiff: " + c14.plaintiff);
        c14.defendant = "Manager X";
        System.out.println("Defendant: " + c14.defendant);
        c14.courtName = "High Court";
        System.out.println("Court Name: " + c14.courtName);
        c14.status = "Closed";
        System.out.println("Status: " + c14.status);
        c14.caseValue = 600000.00;
        System.out.println("Case Value: $" + c14.caseValue);
        c14.paymentMode = "Cash";
        System.out.println("Payment Mode: " + c14.paymentMode);
        System.out.println();

        Courtcase c15 = new Courtcase();
        c15.caseId = 15;
        System.out.println("Case ID: " + c15.caseId);
        c15.caseName = "Patent Infringement";
        System.out.println("Case Name: " + c15.caseName);
        c15.plaintiff = "Innovators Inc.";
        System.out.println("Plaintiff: " + c15.plaintiff);
        c15.defendant = "Competitor Ltd";
        System.out.println("Defendant: " + c15.defendant);
        c15.courtName = "Supreme Court";
        System.out.println("Court Name: " + c15.courtName);
        c15.status = "Ongoing";
        System.out.println("Status: " + c15.status);
        c15.caseValue = 1800000.00;
        System.out.println("Case Value: $" + c15.caseValue);
        c15.paymentMode = "Card";
        System.out.println("Payment Mode: " + c15.paymentMode);
        System.out.println();

        System.out.println("Main Ended");
    }
}