class CrackerRunner {
    public static void main(String[] args) {
        System.out.println("Main Started");

        Cracker c1 = new Cracker();
        c1.crackerId = 1;
        System.out.println("Cracker ID: " + c1.crackerId);
        c1.crackerName = "Sparkler";
        System.out.println("Cracker Name: " + c1.crackerName);
        c1.brand = "FunFire";
        System.out.println("Brand: " + c1.brand);
        c1.crackerType = "Handheld";
        System.out.println("Cracker Type: " + c1.crackerType);
        c1.color = "Multi";
        System.out.println("Color: " + c1.color);
        c1.price = 10.50;
        System.out.println("Price: $" + c1.price);
        c1.paymentMode = "Cash";
        System.out.println("Payment Mode: " + c1.paymentMode);
        System.out.println();

        Cracker c2 = new Cracker();
        c2.crackerId = 2;
        System.out.println("Cracker ID: " + c2.crackerId);
        c2.crackerName = "Chakri";
        System.out.println("Cracker Name: " + c2.crackerName);
        c2.brand = "HappyLights";
        System.out.println("Brand: " + c2.brand);
        c2.crackerType = "Ground Spinner";
        System.out.println("Cracker Type: " + c2.crackerType);
        c2.color = "Red";
        System.out.println("Color: " + c2.color);
        c2.price = 15.00;
        System.out.println("Price: $" + c2.price);
        c2.paymentMode = "Online";
        System.out.println("Payment Mode: " + c2.paymentMode);
        System.out.println();

        Cracker c3 = new Cracker();
        c3.crackerId = 3;
        System.out.println("Cracker ID: " + c3.crackerId);
        c3.crackerName = "Anar";
        System.out.println("Cracker Name: " + c3.crackerName);
        c3.brand = "BrightBlast";
        System.out.println("Brand: " + c3.brand);
        c3.crackerType = "Fountain";
        System.out.println("Cracker Type: " + c3.crackerType);
        c3.color = "Yellow";
        System.out.println("Color: " + c3.color);
        c3.price = 25.00;
        System.out.println("Price: $" + c3.price);
        c3.paymentMode = "Card";
        System.out.println("Payment Mode: " + c3.paymentMode);
        System.out.println();

        Cracker c4 = new Cracker();
        c4.crackerId = 4;
        System.out.println("Cracker ID: " + c4.crackerId);
        c4.crackerName = "Flower Pot";
        System.out.println("Cracker Name: " + c4.crackerName);
        c4.brand = "LightUp";
        System.out.println("Brand: " + c4.brand);
        c4.crackerType = "Fountain";
        System.out.println("Cracker Type: " + c4.crackerType);
        c4.color = "Green";
        System.out.println("Color: " + c4.color);
        c4.price = 30.00;
        System.out.println("Price: $" + c4.price);
        c4.paymentMode = "Cash";
        System.out.println("Payment Mode: " + c4.paymentMode);
        System.out.println();

        Cracker c5 = new Cracker();
        c5.crackerId = 5;
        System.out.println("Cracker ID: " + c5.crackerId);
        c5.crackerName = "Bomb";
        System.out.println("Cracker Name: " + c5.crackerName);
        c5.brand = "FirePower";
        System.out.println("Brand: " + c5.brand);
        c5.crackerType = "Explosive";
        System.out.println("Cracker Type: " + c5.crackerType);
        c5.color = "Black";
        System.out.println("Color: " + c5.color);
        c5.price = 50.00;
        System.out.println("Price: $" + c5.price);
        c5.paymentMode = "Online";
        System.out.println("Payment Mode: " + c5.paymentMode);
        System.out.println();

        Cracker c6 = new Cracker();
        c6.crackerId = 6;
        System.out.println("Cracker ID: " + c6.crackerId);
        c6.crackerName = "Rocket";
        System.out.println("Cracker Name: " + c6.crackerName);
        c6.brand = "SkyFire";
        System.out.println("Brand: " + c6.brand);
        c6.crackerType = "Aerial";
        System.out.println("Cracker Type: " + c6.crackerType);
        c6.color = "Red";
        System.out.println("Color: " + c6.color);
        c6.price = 75.00;
        System.out.println("Price: $" + c6.price);
        c6.paymentMode = "Card";
        System.out.println("Payment Mode: " + c6.paymentMode);
        System.out.println();

        Cracker c7 = new Cracker();
        c7.crackerId = 7;
        System.out.println("Cracker ID: " + c7.crackerId);
        c7.crackerName = "Thunder";
        System.out.println("Cracker Name: " + c7.crackerName);
        c7.brand = "BoomBox";
        System.out.println("Brand: " + c7.brand);
        c7.crackerType = "Explosive";
        System.out.println("Cracker Type: " + c7.crackerType);
        c7.color = "Yellow";
        System.out.println("Color: " + c7.color);
        c7.price = 40.00;
        System.out.println("Price: $" + c7.price);
        c7.paymentMode = "Cash";
        System.out.println("Payment Mode: " + c7.paymentMode);
        System.out.println();

        Cracker c8 = new Cracker();
        c8.crackerId = 8;
        System.out.println("Cracker ID: " + c8.crackerId);
        c8.crackerName = "Snake";
        System.out.println("Cracker Name: " + c8.crackerName);
        c8.brand = "FireDance";
        System.out.println("Brand: " + c8.brand);
        c8.crackerType = "Ground";
        System.out.println("Cracker Type: " + c8.crackerType);
        c8.color = "Grey";
        System.out.println("Color: " + c8.color);
        c8.price = 12.00;
        System.out.println("Price: $" + c8.price);
        c8.paymentMode = "Online";
        System.out.println("Payment Mode: " + c8.paymentMode);
        System.out.println();

        Cracker c9 = new Cracker();
        c9.crackerId = 9;
        System.out.println("Cracker ID: " + c9.crackerId);
        c9.crackerName = "Chakra";
        System.out.println("Cracker Name: " + c9.crackerName);
        c9.brand = "SpinMaster";
        System.out.println("Brand: " + c9.brand);
        c9.crackerType = "Ground Spinner";
        System.out.println("Cracker Type: " + c9.crackerType);
        c9.color = "Orange";
        System.out.println("Color: " + c9.color);
        c9.price = 20.00;
        System.out.println("Price: $" + c9.price);
        c9.paymentMode = "Card";
        System.out.println("Payment Mode: " + c9.paymentMode);
        System.out.println();

        Cracker c10 = new Cracker();
        c10.crackerId = 10;
        System.out.println("Cracker ID: " + c10.crackerId);
        c10.crackerName = "Flower Shower";
        System.out.println("Cracker Name: " + c10.crackerName);
        c10.brand = "LightUp";
        System.out.println("Brand: " + c10.brand);
        c10.crackerType = "Fountain";
        System.out.println("Cracker Type: " + c10.crackerType);
        c10.color = "Pink";
        System.out.println("Color: " + c10.color);
        c10.price = 28.00;
        System.out.println("Price: $" + c10.price);
        c10.paymentMode = "Cash";
        System.out.println("Payment Mode: " + c10.paymentMode);
        System.out.println();

        Cracker c11 = new Cracker();
        c11.crackerId = 11;
        System.out.println("Cracker ID: " + c11.crackerId);
        c11.crackerName = "Chakki";
        System.out.println("Cracker Name: " + c11.crackerName);
        c11.brand = "SpinMaster";
        System.out.println("Brand: " + c11.brand);
        c11.crackerType = "Ground Spinner";
        System.out.println("Cracker Type: " + c11.crackerType);
        c11.color = "Blue";
        System.out.println("Color: " + c11.color);
        c11.price = 18.00;
        System.out.println("Price: $" + c11.price);
        c11.paymentMode = "Online";
        System.out.println("Payment Mode: " + c11.paymentMode);
        System.out.println();

        Cracker c12 = new Cracker();
        c12.crackerId = 12;
        System.out.println("Cracker ID: " + c12.crackerId);
        c12.crackerName = "Chimney";
        System.out.println("Cracker Name: " + c12.crackerName);
        c12.brand = "FirePower";
        System.out.println("Brand: " + c12.brand);
        c12.crackerType = "Fountain";
        System.out.println("Cracker Type: " + c12.crackerType);
        c12.color = "White";
        System.out.println("Color: " + c12.color);
        c12.price = 32.00;
        System.out.println("Price: $" + c12.price);
        c12.paymentMode = "Card";
        System.out.println("Payment Mode: " + c12.paymentMode);
        System.out.println();

        Cracker c13 = new Cracker();
        c13.crackerId = 13;
        System.out.println("Cracker ID: " + c13.crackerId);
        c13.crackerName = "Lakshmi";
        System.out.println("Cracker Name: " + c13.crackerName);
        c13.brand = "HappyLights";
        System.out.println("Brand: " + c13.brand);
        c13.crackerType = "Handheld";
        System.out.println("Cracker Type: " + c13.crackerType);
        c13.color = "Green";
        System.out.println("Color: " + c13.color);
        c13.price = 11.00;
        System.out.println("Price: $" + c13.price);
        c13.paymentMode = "Cash";
        System.out.println("Payment Mode: " + c13.paymentMode);
        System.out.println();

        Cracker c14 = new Cracker();
        c14.crackerId = 14;
        System.out.println("Cracker ID: " + c14.crackerId);
        c14.crackerName = "Tiger";
        System.out.println("Cracker Name: " + c14.crackerName);
        c14.brand = "BoomBox";
        System.out.println("Brand: " + c14.brand);
        c14.crackerType = "Explosive";
        System.out.println("Cracker Type: " + c14.crackerType);
        c14.color = "Orange";
        System.out.println("Color: " + c14.color);
        c14.price = 55.00;
        System.out.println("Price: $" + c14.price);
        c14.paymentMode = "Online";
        System.out.println("Payment Mode: " + c14.paymentMode);
        System.out.println();

        Cracker c15 = new Cracker();
        c15.crackerId = 15;
        System.out.println("Cracker ID: " + c15.crackerId);
        c15.crackerName = "Super Crack";
        System.out.println("Cracker Name: " + c15.crackerName);
        c15.brand = "FunFire";
        System.out.println("Brand: " + c15.brand);
        c15.crackerType = "Explosive";
        System.out.println("Cracker Type: " + c15.crackerType);
        c15.color = "Red";
        System.out.println("Color: " + c15.color);
        c15.price = 60.00;
        System.out.println("Price: $" + c15.price);
        c15.paymentMode = "Card";
        System.out.println("Payment Mode: " + c15.paymentMode);
        System.out.println();

        System.out.println("Main Ended");
    }
}