class FishRunner {
    public static void main(String[] args) {
        System.out.println("Main Started");

        Fish fishOne = new Fish();
        fishOne.fishId = 1;
        System.out.println("Fish ID: " + fishOne.fishId);
        fishOne.species = "Goldfish";
        System.out.println("Species: " + fishOne.species);
        fishOne.color = "Orange";
        System.out.println("Color: " + fishOne.color);
        fishOne.weight = 0.2;
        System.out.println("Weight: " + fishOne.weight + " kg");
        fishOne.length = 5.5;
        System.out.println("Length: " + fishOne.length + " cm");
        fishOne.habitat = "Freshwater";
        System.out.println("Habitat: " + fishOne.habitat);
        System.out.println();

        Fish fishTwo = new Fish();
        fishTwo.fishId = 2;
        System.out.println("Fish ID: " + fishTwo.fishId);
        fishTwo.species = "Clownfish";
        System.out.println("Species: " + fishTwo.species);
        fishTwo.color = "Orange and White";
        System.out.println("Color: " + fishTwo.color);
        fishTwo.weight = 0.25;
        System.out.println("Weight: " + fishTwo.weight + " kg");
        fishTwo.length = 6.0;
        System.out.println("Length: " + fishTwo.length + " cm");
        fishTwo.habitat = "Saltwater";
        System.out.println("Habitat: " + fishTwo.habitat);
        System.out.println();

        Fish fishThree = new Fish();
        fishThree.fishId = 3;
        System.out.println("Fish ID: " + fishThree.fishId);
        fishThree.species = "Betta";
        System.out.println("Species: " + fishThree.species);
        fishThree.color = "Red";
        System.out.println("Color: " + fishThree.color);
        fishThree.weight = 0.15;
        System.out.println("Weight: " + fishThree.weight + " kg");
        fishThree.length = 5.0;
        System.out.println("Length: " + fishThree.length + " cm");
        fishThree.habitat = "Freshwater";
        System.out.println("Habitat: " + fishThree.habitat);
        System.out.println();

        Fish fishFour = new Fish();
        fishFour.fishId = 4;
        System.out.println("Fish ID: " + fishFour.fishId);
        fishFour.species = "Guppy";
        System.out.println("Species: " + fishFour.species);
        fishFour.color = "Multicolor";
        System.out.println("Color: " + fishFour.color);
        fishFour.weight = 0.05;
        System.out.println("Weight: " + fishFour.weight + " kg");
        fishFour.length = 3.5;
        System.out.println("Length: " + fishFour.length + " cm");
        fishFour.habitat = "Freshwater";
        System.out.println("Habitat: " + fishFour.habitat);
        System.out.println();

        Fish fishFive = new Fish();
        fishFive.fishId = 5;
        System.out.println("Fish ID: " + fishFive.fishId);
        fishFive.species = "Angelfish";
        System.out.println("Species: " + fishFive.species);
        fishFive.color = "Silver";
        System.out.println("Color: " + fishFive.color);
        fishFive.weight = 0.3;
        System.out.println("Weight: " + fishFive.weight + " kg");
        fishFive.length = 10.0;
        System.out.println("Length: " + fishFive.length + " cm");
        fishFive.habitat = "Freshwater";
        System.out.println("Habitat: " + fishFive.habitat);
        System.out.println();

        Fish fishSix = new Fish();
        fishSix.fishId = 6;
        System.out.println("Fish ID: " + fishSix.fishId);
        fishSix.species = "Tetra";
        System.out.println("Species: " + fishSix.species);
        fishSix.color = "Neon Blue";
        System.out.println("Color: " + fishSix.color);
        fishSix.weight = 0.1;
        System.out.println("Weight: " + fishSix.weight + " kg");
        fishSix.length = 4.0;
        System.out.println("Length: " + fishSix.length + " cm");
        fishSix.habitat = "Freshwater";
        System.out.println("Habitat: " + fishSix.habitat);
        System.out.println();

        Fish fishSeven = new Fish();
        fishSeven.fishId = 7;
        System.out.println("Fish ID: " + fishSeven.fishId);
        fishSeven.species = "Swordtail";
        System.out.println("Species: " + fishSeven.species);
        fishSeven.color = "Red";
        System.out.println("Color: " + fishSeven.color);
        fishSeven.weight = 0.2;
        System.out.println("Weight: " + fishSeven.weight + " kg");
        fishSeven.length = 8.0;
        System.out.println("Length: " + fishSeven.length + " cm");
        fishSeven.habitat = "Freshwater";
        System.out.println("Habitat: " + fishSeven.habitat);
        System.out.println();

        Fish fishEight = new Fish();
        fishEight.fishId = 8;
        System.out.println("Fish ID: " + fishEight.fishId);
        fishEight.species = "Discus";
        System.out.println("Species: " + fishEight.species);
        fishEight.color = "Blue";
        System.out.println("Color: " + fishEight.color);
        fishEight.weight = 0.6;
        System.out.println("Weight: " + fishEight.weight + " kg");
        fishEight.length = 12.0;
        System.out.println("Length: " + fishEight.length + " cm");
        fishEight.habitat = "Freshwater";
        System.out.println("Habitat: " + fishEight.habitat);
        System.out.println();

        Fish fishNine = new Fish();
        fishNine.fishId = 9;
        System.out.println("Fish ID: " + fishNine.fishId);
        fishNine.species = "Oscar";
        System.out.println("Species: " + fishNine.species);
        fishNine.color = "Black and Orange";
        System.out.println("Color: " + fishNine.color);
        fishNine.weight = 1.0;
        System.out.println("Weight: " + fishNine.weight + " kg");
        fishNine.length = 15.0;
        System.out.println("Length: " + fishNine.length + " cm");
        fishNine.habitat = "Freshwater";
        System.out.println("Habitat: " + fishNine.habitat);
        System.out.println();

        Fish fishTen = new Fish();
        fishTen.fishId = 10;
        System.out.println("Fish ID: " + fishTen.fishId);
        fishTen.species = "Zebrafish";
        System.out.println("Species: " + fishTen.species);
        fishTen.color = "Striped";
        System.out.println("Color: " + fishTen.color);
        fishTen.weight = 0.07;
        System.out.println("Weight: " + fishTen.weight + " kg");
        fishTen.length = 3.0;
        System.out.println("Length: " + fishTen.length + " cm");
        fishTen.habitat = "Freshwater";
        System.out.println("Habitat: " + fishTen.habitat);
        System.out.println();

        Fish fishEleven = new Fish();
        fishEleven.fishId = 11;
        System.out.println("Fish ID: " + fishEleven.fishId);
        fishEleven.species = "Koi";
        System.out.println("Species: " + fishEleven.species);
        fishEleven.color = "Orange and Black";
        System.out.println("Color: " + fishEleven.color);
        fishEleven.weight = 2.0;
        System.out.println("Weight: " + fishEleven.weight + " kg");
        fishEleven.length = 40.0;
        System.out.println("Length: " + fishEleven.length + " cm");
        fishEleven.habitat = "Freshwater";
        System.out.println("Habitat: " + fishEleven.habitat);
        System.out.println();

        Fish fishTwelve = new Fish();
        fishTwelve.fishId = 12;
        System.out.println("Fish ID: " + fishTwelve.fishId);
        fishTwelve.species = "Piranha";
        System.out.println("Species: " + fishTwelve.species);
        fishTwelve.color = "Grey";
        System.out.println("Color: " + fishTwelve.color);
        fishTwelve.weight = 1.5;
        System.out.println("Weight: " + fishTwelve.weight + " kg");
        fishTwelve.length = 30.0;
        System.out.println("Length: " + fishTwelve.length + " cm");
        fishTwelve.habitat = "Freshwater";
        System.out.println("Habitat: " + fishTwelve.habitat);
        System.out.println();

        Fish fishThirteen = new Fish();
        fishThirteen.fishId = 13;
        System.out.println("Fish ID: " + fishThirteen.fishId);
        fishThirteen.species = "Catfish";
        System.out.println("Species: " + fishThirteen.species);
        fishThirteen.color = "Brown";
        System.out.println("Color: " + fishThirteen.color);
        fishThirteen.weight = 1.2;
        System.out.println("Weight: " + fishThirteen.weight + " kg");
        fishThirteen.length = 25.0;
        System.out.println("Length: " + fishThirteen.length + " cm");
        fishThirteen.habitat = "Freshwater";
        System.out.println("Habitat: " + fishThirteen.habitat);
        System.out.println();

        Fish fishFourteen = new Fish();
        fishFourteen.fishId = 14;
        System.out.println("Fish ID: " + fishFourteen.fishId);
        fishFourteen.species = "Snapper";
        System.out.println("Species: " + fishFourteen.species);
        fishFourteen.color = "Red";
        System.out.println("Color: " + fishFourteen.color);
        fishFourteen.weight = 2.5;
        System.out.println("Weight: " + fishFourteen.weight + " kg");
        fishFourteen.length = 60.0;
        System.out.println("Length: " + fishFourteen.length + " cm");
        fishFourteen.habitat = "Saltwater";
        System.out.println("Habitat: " + fishFourteen.habitat);
        System.out.println();

        Fish fishFifteen = new Fish();
        fishFifteen.fishId = 15;
        System.out.println("Fish ID: " + fishFifteen.fishId);
        fishFifteen.species = "Barracuda";
        System.out.println("Species: " + fishFifteen.species);
        fishFifteen.color = "Silver";
        System.out.println("Color: " + fishFifteen.color);
        fishFifteen.weight = 3.5;
        System.out.println("Weight: " + fishFifteen.weight + " kg");
        fishFifteen.length = 85.0;
        System.out.println("Length: " + fishFifteen.length + " cm");
        fishFifteen.habitat = "Saltwater";
        System.out.println("Habitat: " + fishFifteen.habitat);
        System.out.println();

        System.out.println("Main Ended");
    }
}