class FlowersRunner {
    public static void main(String[] args) {
        System.out.println("Main Started");

        Flowers flowerOne = new Flowers();
        flowerOne.flowerId = 1;
        System.out.println("Flower ID: " + flowerOne.flowerId);
        flowerOne.name = "Rose";
        System.out.println("Name: " + flowerOne.name);
        flowerOne.color = "Red";
        System.out.println("Color: " + flowerOne.color);
        flowerOne.type = "Garden";
        System.out.println("Type: " + flowerOne.type);
        flowerOne.price = 50.00;
        System.out.println("Price: " + flowerOne.price);
        flowerOne.fragrance = "Strong";
        System.out.println("Fragrance: " + flowerOne.fragrance);
        flowerOne.quantityAvailable = 100;
        System.out.println("Quantity Available: " + flowerOne.quantityAvailable);
        flowerOne.paymentMode = "Cash";
        System.out.println("Payment Mode: " + flowerOne.paymentMode);
        System.out.println();

        Flowers flowerTwo = new Flowers();
        flowerTwo.flowerId = 2;
        System.out.println("Flower ID: " + flowerTwo.flowerId);
        flowerTwo.name = "Tulip";
        System.out.println("Name: " + flowerTwo.name);
        flowerTwo.color = "Yellow";
        System.out.println("Color: " + flowerTwo.color);
        flowerTwo.type = "Spring";
        System.out.println("Type: " + flowerTwo.type);
        flowerTwo.price = 35.00;
        System.out.println("Price: " + flowerTwo.price);
        flowerTwo.fragrance = "Mild";
        System.out.println("Fragrance: " + flowerTwo.fragrance);
        flowerTwo.quantityAvailable = 75;
        System.out.println("Quantity Available: " + flowerTwo.quantityAvailable);
        flowerTwo.paymentMode = "Card";
        System.out.println("Payment Mode: " + flowerTwo.paymentMode);
        System.out.println();

        Flowers flowerThree = new Flowers();
        flowerThree.flowerId = 3;
        System.out.println("Flower ID: " + flowerThree.flowerId);
        flowerThree.name = "Lily";
        System.out.println("Name: " + flowerThree.name);
        flowerThree.color = "White";
        System.out.println("Color: " + flowerThree.color);
        flowerThree.type = "Water";
        System.out.println("Type: " + flowerThree.type);
        flowerThree.price = 40.00;
        System.out.println("Price: " + flowerThree.price);
        flowerThree.fragrance = "Sweet";
        System.out.println("Fragrance: " + flowerThree.fragrance);
        flowerThree.quantityAvailable = 60;
        System.out.println("Quantity Available: " + flowerThree.quantityAvailable);
        flowerThree.paymentMode = "Online";
        System.out.println("Payment Mode: " + flowerThree.paymentMode);
        System.out.println();

        Flowers flowerFour = new Flowers();
        flowerFour.flowerId = 4;
        System.out.println("Flower ID: " + flowerFour.flowerId);
        flowerFour.name = "Orchid";
        System.out.println("Name: " + flowerFour.name);
        flowerFour.color = "Purple";
        System.out.println("Color: " + flowerFour.color);
        flowerFour.type = "Tropical";
        System.out.println("Type: " + flowerFour.type);
        flowerFour.price = 60.00;
        System.out.println("Price: " + flowerFour.price);
        flowerFour.fragrance = "Mild";
        System.out.println("Fragrance: " + flowerFour.fragrance);
        flowerFour.quantityAvailable = 80;
        System.out.println("Quantity Available: " + flowerFour.quantityAvailable);
        flowerFour.paymentMode = "Cash";
        System.out.println("Payment Mode: " + flowerFour.paymentMode);
        System.out.println();

        Flowers flowerFive = new Flowers();
        flowerFive.flowerId = 5;
        System.out.println("Flower ID: " + flowerFive.flowerId);
        flowerFive.name = "Sunflower";
        System.out.println("Name: " + flowerFive.name);
        flowerFive.color = "Yellow";
        System.out.println("Color: " + flowerFive.color);
        flowerFive.type = "Field";
        System.out.println("Type: " + flowerFive.type);
        flowerFive.price = 25.00;
        System.out.println("Price: " + flowerFive.price);
        flowerFive.fragrance = "None";
        System.out.println("Fragrance: " + flowerFive.fragrance);
        flowerFive.quantityAvailable = 120;
        System.out.println("Quantity Available: " + flowerFive.quantityAvailable);
        flowerFive.paymentMode = "Card";
        System.out.println("Payment Mode: " + flowerFive.paymentMode);
        System.out.println();

        Flowers flowerSix = new Flowers();
        flowerSix.flowerId = 6;
        System.out.println("Flower ID: " + flowerSix.flowerId);
        flowerSix.name = "Jasmine";
        System.out.println("Name: " + flowerSix.name);
        flowerSix.color = "White";
        System.out.println("Color: " + flowerSix.color);
        flowerSix.type = "Climber";
        System.out.println("Type: " + flowerSix.type);
        flowerSix.price = 30.00;
        System.out.println("Price: " + flowerSix.price);
        flowerSix.fragrance = "Strong";
        System.out.println("Fragrance: " + flowerSix.fragrance);
        flowerSix.quantityAvailable = 95;
        System.out.println("Quantity Available: " + flowerSix.quantityAvailable);
        flowerSix.paymentMode = "Online";
        System.out.println("Payment Mode: " + flowerSix.paymentMode);
        System.out.println();

        Flowers flowerSeven = new Flowers();
        flowerSeven.flowerId = 7;
        System.out.println("Flower ID: " + flowerSeven.flowerId);
        flowerSeven.name = "Daisy";
        System.out.println("Name: " + flowerSeven.name);
        flowerSeven.color = "White";
        System.out.println("Color: " + flowerSeven.color);
        flowerSeven.type = "Field";
        System.out.println("Type: " + flowerSeven.type);
        flowerSeven.price = 20.00;
        System.out.println("Price: " + flowerSeven.price);
        flowerSeven.fragrance = "Light";
        System.out.println("Fragrance: " + flowerSeven.fragrance);
        flowerSeven.quantityAvailable = 110;
        System.out.println("Quantity Available: " + flowerSeven.quantityAvailable);
        flowerSeven.paymentMode = "Cash";
        System.out.println("Payment Mode: " + flowerSeven.paymentMode);
        System.out.println();

        Flowers flowerEight = new Flowers();
        flowerEight.flowerId = 8;
        System.out.println("Flower ID: " + flowerEight.flowerId);
        flowerEight.name = "Lavender";
        System.out.println("Name: " + flowerEight.name);
        flowerEight.color = "Purple";
        System.out.println("Color: " + flowerEight.color);
        flowerEight.type = "Herb";
        System.out.println("Type: " + flowerEight.type);
        flowerEight.price = 55.00;
        System.out.println("Price: " + flowerEight.price);
        flowerEight.fragrance = "Strong";
        System.out.println("Fragrance: " + flowerEight.fragrance);
        flowerEight.quantityAvailable = 65;
        System.out.println("Quantity Available: " + flowerEight.quantityAvailable);
        flowerEight.paymentMode = "Card";
        System.out.println("Payment Mode: " + flowerEight.paymentMode);
        System.out.println();

        Flowers flowerNine = new Flowers();
        flowerNine.flowerId = 9;
        System.out.println("Flower ID: " + flowerNine.flowerId);
        flowerNine.name = "Peony";
        System.out.println("Name: " + flowerNine.name);
        flowerNine.color = "Pink";
        System.out.println("Color: " + flowerNine.color);
        flowerNine.type = "Shrub";
        System.out.println("Type: " + flowerNine.type);
        flowerNine.price = 45.00;
        System.out.println("Price: " + flowerNine.price);
        flowerNine.fragrance = "Mild";
        System.out.println("Fragrance: " + flowerNine.fragrance);
        flowerNine.quantityAvailable = 70;
        System.out.println("Quantity Available: " + flowerNine.quantityAvailable);
        flowerNine.paymentMode = "Online";
        System.out.println("Payment Mode: " + flowerNine.paymentMode);
        System.out.println();

        Flowers flowerTen = new Flowers();
        flowerTen.flowerId = 10;
        System.out.println("Flower ID: " + flowerTen.flowerId);
        flowerTen.name = "Daffodil";
        System.out.println("Name: " + flowerTen.name);
        flowerTen.color = "Yellow";
        System.out.println("Color: " + flowerTen.color);
        flowerTen.type = "Spring";
        System.out.println("Type: " + flowerTen.type);
        flowerTen.price = 32.00;
        System.out.println("Price: " + flowerTen.price);
        flowerTen.fragrance = "Light";
        System.out.println("Fragrance: " + flowerTen.fragrance);
        flowerTen.quantityAvailable = 85;
        System.out.println("Quantity Available: " + flowerTen.quantityAvailable);
        flowerTen.paymentMode = "Cash";
        System.out.println("Payment Mode: " + flowerTen.paymentMode);
        System.out.println();

        System.out.println("Main Ended");
    }
}