class ForestSafariRunner {
    public static void main(String[] args) {
        System.out.println("Main Started");

        ForestSafari safariOne = new ForestSafari();
        safariOne.safariId = 1;
        System.out.println("Safari ID: " + safariOne.safariId);
        safariOne.forestName = "Amazon Rainforest";
        System.out.println("Forest Name: " + safariOne.forestName);
        safariOne.country = "Brazil";
        System.out.println("Country: " + safariOne.country);
        safariOne.areaSqKm = 5500.0;
        System.out.println("Area (sq km): " + safariOne.areaSqKm);
        safariOne.animalSpotted = "Jaguar";
        System.out.println("Animal Spotted: " + safariOne.animalSpotted);
        safariOne.isGuided = true;
        System.out.println("Guided Tour: " + safariOne.isGuided);
        System.out.println();

        ForestSafari safariTwo = new ForestSafari();
        safariTwo.safariId = 2;
        System.out.println("Safari ID: " + safariTwo.safariId);
        safariTwo.forestName = "Sundarbans";
        System.out.println("Forest Name: " + safariTwo.forestName);
        safariTwo.country = "India";
        System.out.println("Country: " + safariTwo.country);
        safariTwo.areaSqKm = 4262.0;
        System.out.println("Area (sq km): " + safariTwo.areaSqKm);
        safariTwo.animalSpotted = "Royal Bengal Tiger";
        System.out.println("Animal Spotted: " + safariTwo.animalSpotted);
        safariTwo.isGuided = true;
        System.out.println("Guided Tour: " + safariTwo.isGuided);
        System.out.println();

        ForestSafari safariThree = new ForestSafari();
        safariThree.safariId = 3;
        System.out.println("Safari ID: " + safariThree.safariId);
        safariThree.forestName = "Black Forest";
        System.out.println("Forest Name: " + safariThree.forestName);
        safariThree.country = "Germany";
        System.out.println("Country: " + safariThree.country);
        safariThree.areaSqKm = 6000.0;
        System.out.println("Area (sq km): " + safariThree.areaSqKm);
        safariThree.animalSpotted = "Red Deer";
        System.out.println("Animal Spotted: " + safariThree.animalSpotted);
        safariThree.isGuided = false;
        System.out.println("Guided Tour: " + safariThree.isGuided);
        System.out.println();

        ForestSafari safariFour = new ForestSafari();
        safariFour.safariId = 4;
        System.out.println("Safari ID: " + safariFour.safariId);
        safariFour.forestName = "Congo Rainforest";
        System.out.println("Forest Name: " + safariFour.forestName);
        safariFour.country = "Congo";
        System.out.println("Country: " + safariFour.country);
        safariFour.areaSqKm = 7000.0;
        System.out.println("Area (sq km): " + safariFour.areaSqKm);
        safariFour.animalSpotted = "Gorilla";
        System.out.println("Animal Spotted: " + safariFour.animalSpotted);
        safariFour.isGuided = true;
        System.out.println("Guided Tour: " + safariFour.isGuided);
        System.out.println();

        ForestSafari safariFive = new ForestSafari();
        safariFive.safariId = 5;
        System.out.println("Safari ID: " + safariFive.safariId);
        safariFive.forestName = "Borneo Rainforest";
        System.out.println("Forest Name: " + safariFive.forestName);
        safariFive.country = "Malaysia";
        System.out.println("Country: " + safariFive.country);
        safariFive.areaSqKm = 7430.0;
        System.out.println("Area (sq km): " + safariFive.areaSqKm);
        safariFive.animalSpotted = "Orangutan";
        System.out.println("Animal Spotted: " + safariFive.animalSpotted);
        safariFive.isGuided = true;
        System.out.println("Guided Tour: " + safariFive.isGuided);
        System.out.println();

        ForestSafari safariSix = new ForestSafari();
        safariSix.safariId = 6;
        System.out.println("Safari ID: " + safariSix.safariId);
        safariSix.forestName = "Yosemite";
        System.out.println("Forest Name: " + safariSix.forestName);
        safariSix.country = "USA";
        System.out.println("Country: " + safariSix.country);
        safariSix.areaSqKm = 3027.0;
        System.out.println("Area (sq km): " + safariSix.areaSqKm);
        safariSix.animalSpotted = "Black Bear";
        System.out.println("Animal Spotted: " + safariSix.animalSpotted);
        safariSix.isGuided = false;
        System.out.println("Guided Tour: " + safariSix.isGuided);
        System.out.println();

        ForestSafari safariSeven = new ForestSafari();
        safariSeven.safariId = 7;
        System.out.println("Safari ID: " + safariSeven.safariId);
        safariSeven.forestName = "Tongass National Forest";
        System.out.println("Forest Name: " + safariSeven.forestName);
        safariSeven.country = "USA";
        System.out.println("Country: " + safariSeven.country);
        safariSeven.areaSqKm = 68690.0;
        System.out.println("Area (sq km): " + safariSeven.areaSqKm);
        safariSeven.animalSpotted = "Bald Eagle";
        System.out.println("Animal Spotted: " + safariSeven.animalSpotted);
        safariSeven.isGuided = false;
        System.out.println("Guided Tour: " + safariSeven.isGuided);
        System.out.println();

        ForestSafari safariEight = new ForestSafari();
        safariEight.safariId = 8;
        System.out.println("Safari ID: " + safariEight.safariId);
        safariEight.forestName = "Daintree Rainforest";
        System.out.println("Forest Name: " + safariEight.forestName);
        safariEight.country = "Australia";
        System.out.println("Country: " + safariEight.country);
        safariEight.areaSqKm = 1200.0;
        System.out.println("Area (sq km): " + safariEight.areaSqKm);
        safariEight.animalSpotted = "Cassowary";
        System.out.println("Animal Spotted: " + safariEight.animalSpotted);
        safariEight.isGuided = true;
        System.out.println("Guided Tour: " + safariEight.isGuided);
        System.out.println();

        ForestSafari safariNine = new ForestSafari();
        safariNine.safariId = 9;
        System.out.println("Safari ID: " + safariNine.safariId);
        safariNine.forestName = "Valdivian Temperate Rainforest";
        System.out.println("Forest Name: " + safariNine.forestName);
        safariNine.country = "Chile";
        System.out.println("Country: " + safariNine.country);
        safariNine.areaSqKm = 24800.0;
        System.out.println("Area (sq km): " + safariNine.areaSqKm);
        safariNine.animalSpotted = "Puma";
        System.out.println("Animal Spotted: " + safariNine.animalSpotted);
        safariNine.isGuided = true;
        System.out.println("Guided Tour: " + safariNine.isGuided);
        System.out.println();

        ForestSafari safariTen = new ForestSafari();
        safariTen.safariId = 10;
        System.out.println("Safari ID: " + safariTen.safariId);
        safariTen.forestName = "Tijuca Forest";
        System.out.println("Forest Name: " + safariTen.forestName);
        safariTen.country = "Brazil";
        System.out.println("Country: " + safariTen.country);
        safariTen.areaSqKm = 32.0;
        System.out.println("Area (sq km): " + safariTen.areaSqKm);
        safariTen.animalSpotted = "Capuchin Monkey";
        System.out.println("Animal Spotted: " + safariTen.animalSpotted);
        safariTen.isGuided = true;
        System.out.println("Guided Tour: " + safariTen.isGuided);
        System.out.println();

        ForestSafari safariEleven = new ForestSafari();
        safariEleven.safariId = 11;
        System.out.println("Safari ID: " + safariEleven.safariId);
        safariEleven.forestName = "Sinharaja Forest";
        System.out.println("Forest Name: " + safariEleven.forestName);
        safariEleven.country = "Sri Lanka";
        System.out.println("Country: " + safariEleven.country);
        safariEleven.areaSqKm = 88.6;
        System.out.println("Area (sq km): " + safariEleven.areaSqKm);
        safariEleven.animalSpotted = "Purple-faced Langur";
        System.out.println("Animal Spotted: " + safariEleven.animalSpotted);
        safariEleven.isGuided = true;
        System.out.println("Guided Tour: " + safariEleven.isGuided);
        System.out.println();

        ForestSafari safariTwelve = new ForestSafari();
        safariTwelve.safariId = 12;
        System.out.println("Safari ID: " + safariTwelve.safariId);
        safariTwelve.forestName = "Taiga Forest";
        System.out.println("Forest Name: " + safariTwelve.forestName);
        safariTwelve.country = "Russia";
        System.out.println("Country: " + safariTwelve.country);
        safariTwelve.areaSqKm = 17000000.0;
        System.out.println("Area (sq km): " + safariTwelve.areaSqKm);
        safariTwelve.animalSpotted = "Siberian Tiger";
        System.out.println("Animal Spotted: " + safariTwelve.animalSpotted);
        safariTwelve.isGuided = false;
        System.out.println("Guided Tour: " + safariTwelve.isGuided);
        System.out.println();

        ForestSafari safariThirteen = new ForestSafari();
        safariThirteen.safariId = 13;
        System.out.println("Safari ID: " + safariThirteen.safariId);
        safariThirteen.forestName = "Bwindi Impenetrable Forest";
        System.out.println("Forest Name: " + safariThirteen.forestName);
        safariThirteen.country = "Uganda";
        System.out.println("Country: " + safariThirteen.country);
        safariThirteen.areaSqKm = 321.0;
        System.out.println("Area (sq km): " + safariThirteen.areaSqKm);
        safariThirteen.animalSpotted = "Mountain Gorilla";
        System.out.println("Animal Spotted: " + safariThirteen.animalSpotted);
        safariThirteen.isGuided = true;
        System.out.println("Guided Tour: " + safariThirteen.isGuided);
        System.out.println();

        ForestSafari safariFourteen = new ForestSafari();
        safariFourteen.safariId = 14;
        System.out.println("Safari ID: " + safariFourteen.safariId);
        safariFourteen.forestName = "Kinabalu National Park";
        System.out.println("Forest Name: " + safariFourteen.forestName);
        safariFourteen.country = "Malaysia";
        System.out.println("Country: " + safariFourteen.country);
        safariFourteen.areaSqKm = 754.0;
        System.out.println("Area (sq km): " + safariFourteen.areaSqKm);
        safariFourteen.animalSpotted = "Clouded Leopard";
        System.out.println("Animal Spotted: " + safariFourteen.animalSpotted);
        safariFourteen.isGuided = true;
        System.out.println("Guided Tour: " + safariFourteen.isGuided);
        System.out.println();

        ForestSafari safariFifteen = new ForestSafari();
        safariFifteen.safariId = 15;
        System.out.println("Safari ID: " + safariFifteen.safariId);
        safariFifteen.forestName = "Kruger National Park";
        System.out.println("Forest Name: " + safariFifteen.forestName);
        safariFifteen.country = "South Africa";
        System.out.println("Country: " + safariFifteen.country);
        safariFifteen.areaSqKm = 19485.0;
        System.out.println("Area (sq km): " + safariFifteen.areaSqKm);
        safariFifteen.animalSpotted = "Elephant";
        System.out.println("Animal Spotted: " + safariFifteen.animalSpotted);
        safariFifteen.isGuided = true;
        System.out.println("Guided Tour: " + safariFifteen.isGuided);
        System.out.println();

        System.out.println("Main Ended");
    }
}