class HairClipRunner {
    public static void main(String[] args) {
        System.out.println("Main Started");

        HairClip clipOne = new HairClip();
        clipOne.clipId = 1;
        System.out.println("HairClip ID: " + clipOne.clipId);
        clipOne.brandName = "Claire's";
        System.out.println("HairClip Brand: " + clipOne.brandName);
        clipOne.clipType = "Snap Clip";
        System.out.println("HairClip Type: " + clipOne.clipType);
        clipOne.clipColor = "Pink";
        System.out.println("HairClip Color: " + clipOne.clipColor);
        clipOne.clipPrice = 50.00;
        System.out.println("HairClip Price: " + clipOne.clipPrice);
        clipOne.paymentMode = "Online";
        System.out.println("Payment Mode: " + clipOne.paymentMode);
        System.out.println("");

        HairClip clipTwo = new HairClip();
        clipTwo.clipId = 2;
        System.out.println("HairClip ID: " + clipTwo.clipId);
        clipTwo.brandName = "Scünci";
        System.out.println("HairClip Brand: " + clipTwo.brandName);
        clipTwo.clipType = "Banana Clip";
        System.out.println("HairClip Type: " + clipTwo.clipType);
        clipTwo.clipColor = "Black";
        System.out.println("HairClip Color: " + clipTwo.clipColor);
        clipTwo.clipPrice = 65.00;
        System.out.println("HairClip Price: " + clipTwo.clipPrice);
        clipTwo.paymentMode = "Cash";
        System.out.println("Payment Mode: " + clipTwo.paymentMode);
        System.out.println("");

        HairClip clipThree = new HairClip();
        clipThree.clipId = 3;
        System.out.println("HairClip ID: " + clipThree.clipId);
        clipThree.brandName = "Goody";
        System.out.println("HairClip Brand: " + clipThree.brandName);
        clipThree.clipType = "Alligator Clip";
        System.out.println("HairClip Type: " + clipThree.clipType);
        clipThree.clipColor = "Purple";
        System.out.println("HairClip Color: " + clipThree.clipColor);
        clipThree.clipPrice = 70.00;
        System.out.println("HairClip Price: " + clipThree.clipPrice);
        clipThree.paymentMode = "Card";
        System.out.println("Payment Mode: " + clipThree.paymentMode);
        System.out.println("");

        HairClip clipFour = new HairClip();
        clipFour.clipId = 4;
        System.out.println("HairClip ID: " + clipFour.clipId);
        clipFour.brandName = "H&M";
        System.out.println("HairClip Brand: " + clipFour.brandName);
        clipFour.clipType = "Barrette";
        System.out.println("HairClip Type: " + clipFour.clipType);
        clipFour.clipColor = "Silver";
        System.out.println("HairClip Color: " + clipFour.clipColor);
        clipFour.clipPrice = 55.00;
        System.out.println("HairClip Price: " + clipFour.clipPrice);
        clipFour.paymentMode = "UPI";
        System.out.println("Payment Mode: " + clipFour.paymentMode);
        System.out.println("");

        HairClip clipFive = new HairClip();
        clipFive.clipId = 5;
        System.out.println("HairClip ID: " + clipFive.clipId);
        clipFive.brandName = "Forever 21";
        System.out.println("HairClip Brand: " + clipFive.brandName);
        clipFive.clipType = "Claw Clip";
        System.out.println("HairClip Type: " + clipFive.clipType);
        clipFive.clipColor = "White";
        System.out.println("HairClip Color: " + clipFive.clipColor);
        clipFive.clipPrice = 80.00;
        System.out.println("HairClip Price: " + clipFive.clipPrice);
        clipFive.paymentMode = "Online";
        System.out.println("Payment Mode: " + clipFive.paymentMode);
        System.out.println("");

        HairClip clipSix = new HairClip();
        clipSix.clipId = 6;
        System.out.println("HairClip ID: " + clipSix.clipId);
        clipSix.brandName = "Miniso";
        System.out.println("HairClip Brand: " + clipSix.brandName);
        clipSix.clipType = "Comb Clip";
        System.out.println("HairClip Type: " + clipSix.clipType);
        clipSix.clipColor = "Red";
        System.out.println("HairClip Color: " + clipSix.clipColor);
        clipSix.clipPrice = 90.00;
        System.out.println("HairClip Price: " + clipSix.clipPrice);
        clipSix.paymentMode = "Cash";
        System.out.println("Payment Mode: " + clipSix.paymentMode);
        System.out.println("");

        HairClip clipSeven = new HairClip();
        clipSeven.clipId = 7;
        System.out.println("HairClip ID: " + clipSeven.clipId);
        clipSeven.brandName = "Zara";
        System.out.println("HairClip Brand: " + clipSeven.brandName);
        clipSeven.clipType = "Duckbill Clip";
        System.out.println("HairClip Type: " + clipSeven.clipType);
        clipSeven.clipColor = "Blue";
        System.out.println("HairClip Color: " + clipSeven.clipColor);
        clipSeven.clipPrice = 45.00;
        System.out.println("HairClip Price: " + clipSeven.clipPrice);
        clipSeven.paymentMode = "Card";
        System.out.println("Payment Mode: " + clipSeven.paymentMode);
        System.out.println("");

        HairClip clipEight = new HairClip();
        clipEight.clipId = 8;
        System.out.println("HairClip ID: " + clipEight.clipId);
        clipEight.brandName = "Bershka";
        System.out.println("HairClip Brand: " + clipEight.brandName);
        clipEight.clipType = "Snap Clip";
        System.out.println("HairClip Type: " + clipEight.clipType);
        clipEight.clipColor = "Green";
        System.out.println("HairClip Color: " + clipEight.clipColor);
        clipEight.clipPrice = 35.00;
        System.out.println("HairClip Price: " + clipEight.clipPrice);
        clipEight.paymentMode = "UPI";
        System.out.println("Payment Mode: " + clipEight.paymentMode);
        System.out.println("");

        HairClip clipNine = new HairClip();
        clipNine.clipId = 9;
        System.out.println("HairClip ID: " + clipNine.clipId);
        clipNine.brandName = "Accessorize";
        System.out.println("HairClip Brand: " + clipNine.brandName);
        clipNine.clipType = "Hair Barrettes";
        System.out.println("HairClip Type: " + clipNine.clipType);
        clipNine.clipColor = "Yellow";
        System.out.println("HairClip Color: " + clipNine.clipColor);
        clipNine.clipPrice = 60.00;
        System.out.println("HairClip Price: " + clipNine.clipPrice);
        clipNine.paymentMode = "Online";
        System.out.println("Payment Mode: " + clipNine.paymentMode);
        System.out.println("");

        HairClip clipTen = new HairClip();
        clipTen.clipId = 10;
        System.out.println("HairClip ID: " + clipTen.clipId);
        clipTen.brandName = "Pantene";
        System.out.println("HairClip Brand: " + clipTen.brandName);
        clipTen.clipType = "Comb Clip";
        System.out.println("HairClip Type: " + clipTen.clipType);
        clipTen.clipColor = "Orange";
        System.out.println("HairClip Color: " + clipTen.clipColor);
        clipTen.clipPrice = 85.00;
        System.out.println("HairClip Price: " + clipTen.clipPrice);
        clipTen.paymentMode = "Card";
        System.out.println("Payment Mode: " + clipTen.paymentMode);
        System.out.println("");

        HairClip clipEleven = new HairClip();
        clipEleven.clipId = 11;
        System.out.println("HairClip ID: " + clipEleven.clipId);
        clipEleven.brandName = "Nova";
        System.out.println("HairClip Brand: " + clipEleven.brandName);
        clipEleven.clipType = "Claw Clip";
        System.out.println("HairClip Type: " + clipEleven.clipType);
        clipEleven.clipColor = "Black";
        System.out.println("HairClip Color: " + clipEleven.clipColor);
        clipEleven.clipPrice = 95.00;
        System.out.println("HairClip Price: " + clipEleven.clipPrice);
        clipEleven.paymentMode = "Cash";
        System.out.println("Payment Mode: " + clipEleven.paymentMode);
        System.out.println("");

        HairClip clipTwelve = new HairClip();
        clipTwelve.clipId = 12;
        System.out.println("HairClip ID: " + clipTwelve.clipId);
        clipTwelve.brandName = "Revlon";
        System.out.println("HairClip Brand: " + clipTwelve.brandName);
        clipTwelve.clipType = "Alligator Clip";
        System.out.println("HairClip Type: " + clipTwelve.clipType);
        clipTwelve.clipColor = "White";
        System.out.println("HairClip Color: " + clipTwelve.clipColor);
        clipTwelve.clipPrice = 110.00;
        System.out.println("HairClip Price: " + clipTwelve.clipPrice);
        clipTwelve.paymentMode = "UPI";
        System.out.println("Payment Mode: " + clipTwelve.paymentMode);
        System.out.println("");

        HairClip clipThirteen = new HairClip();
        clipThirteen.clipId = 13;
        System.out.println("HairClip ID: " + clipThirteen.clipId);
        clipThirteen.brandName = "Vega";
        System.out.println("HairClip Brand: " + clipThirteen.brandName);
        clipThirteen.clipType = "Duckbill Clip";
        System.out.println("HairClip Type: " + clipThirteen.clipType);
        clipThirteen.clipColor = "Brown";
        System.out.println("HairClip Color: " + clipThirteen.clipColor);
        clipThirteen.clipPrice = 95.00;
        System.out.println("HairClip Price: " + clipThirteen.clipPrice);
        clipThirteen.paymentMode = "Online";
        System.out.println("Payment Mode: " + clipThirteen.paymentMode);
        System.out.println("");

        HairClip clipFourteen = new HairClip();
        clipFourteen.clipId = 14;
        System.out.println("HairClip ID: " + clipFourteen.clipId);
        clipFourteen.brandName = "Fossil";
        System.out.println("HairClip Brand: " + clipFourteen.brandName);
        clipFourteen.clipType = "Snap Clip";
        System.out.println("HairClip Type: " + clipFourteen.clipType);
        clipFourteen.clipColor = "Beige";
        System.out.println("HairClip Color: " + clipFourteen.clipColor);
        clipFourteen.clipPrice = 105.00;
        System.out.println("HairClip Price: " + clipFourteen.clipPrice);
        clipFourteen.paymentMode = "Card";
        System.out.println("Payment Mode: " + clipFourteen.paymentMode);
        System.out.println("");

        HairClip clipFifteen = new HairClip();
        clipFifteen.clipId = 15;
        System.out.println("HairClip ID: " + clipFifteen.clipId);
        clipFifteen.brandName = "Nykaa";
        System.out.println("HairClip Brand: " + clipFifteen.brandName);
        clipFifteen.clipType = "Banana Clip";
        System.out.println("HairClip Type: " + clipFifteen.clipType);
        clipFifteen.clipColor = "Lavender";
        System.out.println("HairClip Color: " + clipFifteen.clipColor);
        clipFifteen.clipPrice = 130.00;
        System.out.println("HairClip Price: " + clipFifteen.clipPrice);
        clipFifteen.paymentMode = "Online";
        System.out.println("Payment Mode: " + clipFifteen.paymentMode);
        System.out.println("");

        HairClip clipSixteen = new HairClip();
        clipSixteen.clipId = 16;
        System.out.println("HairClip ID: " + clipSixteen.clipId);
        clipSixteen.brandName = "L'Oreal";
        System.out.println("HairClip Brand: " + clipSixteen.brandName);
        clipSixteen.clipType = "Claw Clip";
        System.out.println("HairClip Type: " + clipSixteen.clipType);
        clipSixteen.clipColor = "Gold";
        System.out.println("HairClip Color: " + clipSixteen.clipColor);
        clipSixteen.clipPrice = 140.00;
        System.out.println("HairClip Price: " + clipSixteen.clipPrice);
        clipSixteen.paymentMode = "Cash";
        System.out.println("Payment Mode: " + clipSixteen.paymentMode);
        System.out.println("");

        HairClip clipSeventeen = new HairClip();
        clipSeventeen.clipId = 17;
        System.out.println("HairClip ID: " + clipSeventeen.clipId);
        clipSeventeen.brandName = "Tangle Teezer";
        System.out.println("HairClip Brand: " + clipSeventeen.brandName);
        clipSeventeen.clipType = "Hair Barrettes";
        System.out.println("HairClip Type: " + clipSeventeen.clipType);
        clipSeventeen.clipColor = "Pink";
        System.out.println("HairClip Color: " + clipSeventeen.clipColor);
        clipSeventeen.clipPrice = 150.00;
        System.out.println("HairClip Price: " + clipSeventeen.clipPrice);
        clipSeventeen.paymentMode = "Card";
        System.out.println("Payment Mode: " + clipSeventeen.paymentMode);
        System.out.println("");

        HairClip clipEighteen = new HairClip();
        clipEighteen.clipId = 18;
        System.out.println("HairClip ID: " + clipEighteen.clipId);
        clipEighteen.brandName = "Bumble and Bumble";
        System.out.println("HairClip Brand: " + clipEighteen.brandName);   
        clipEighteen.clipType = "Alligator Clip";
        System.out.println("HairClip Type: " + clipEighteen.clipType);
        clipEighteen.clipColor = "Black";
        System.out.println("HairClip Color: " + clipEighteen.clipColor);
        clipEighteen.clipPrice = 160.00;
        System.out.println("HairClip Price: " + clipEighteen.clipPrice);
        clipEighteen.paymentMode = "Online";
        System.out.println("Payment Mode: " + clipEighteen.paymentMode);
        System.out.println("");

        HairClip clipNineteen = new HairClip();
        clipNineteen.clipId = 19;
        System.out.println("HairClip ID: " + clipNineteen.clipId);
        clipNineteen.brandName = "Paul Mitchell";
        System.out.println("HairClip Brand: " + clipNineteen.brandName);
        clipNineteen.clipType = "Duckbill Clip";
        System.out.println("HairClip Type: " + clipNineteen.clipType);
        clipNineteen.clipColor = "White";
        System.out.println("HairClip Color: " + clipNineteen.clipColor);
        clipNineteen.clipPrice = 175.00;
        System.out.println("HairClip Price: " + clipNineteen.clipPrice);
        clipNineteen.paymentMode = "Cash";
        System.out.println("Payment Mode: " + clipNineteen.paymentMode);
        System.out.println("");

        HairClip clipTwenty = new HairClip();
        clipTwenty.clipId = 20;
        System.out.println("HairClip ID: " + clipTwenty.clipId);
        clipTwenty.brandName = "Tresemme";
        System.out.println("HairClip Brand: " + clipTwenty.brandName);
        clipTwenty.clipType = "Snap Clip";
        System.out.println("HairClip Type: " + clipTwenty.clipType);
        clipTwenty.clipColor = "Blue";
        System.out.println("HairClip Color: " + clipTwenty.clipColor);
        clipTwenty.clipPrice = 190.00;
        System.out.println("HairClip Price: " + clipTwenty.clipPrice);
        clipTwenty.paymentMode = "UPI";
        System.out.println("Payment Mode: " + clipTwenty.paymentMode);
        System.out.println("");

        System.out.println("Main Ended");
    }
}