class HatRunner {
    public static void main(String[] args) {
        System.out.println("Main Started");

        Hat hatOne = new Hat();
        hatOne.hatId = 1;
        System.out.println("Hat ID: " + hatOne.hatId);
        hatOne.brandName = "Nike";
        System.out.println("Brand Name: " + hatOne.brandName);
        hatOne.hatSize = "M";
        System.out.println("Hat Size: " + hatOne.hatSize);
        hatOne.hatColour = "Black";
        System.out.println("Hat Colour: " + hatOne.hatColour);
        hatOne.hatPrice = 1200.00;
        System.out.println("Hat Price: ₹" + hatOne.hatPrice);
        hatOne.paymentMode = "Online";
        System.out.println("Payment Mode: " + hatOne.paymentMode);
        System.out.println("");

        Hat hatTwo = new Hat();
        hatTwo.hatId = 2;
        System.out.println("Hat ID: " + hatTwo.hatId);
        hatTwo.brandName = "Adidas";
        System.out.println("Brand Name: " + hatTwo.brandName);
        hatTwo.hatSize = "L";
        System.out.println("Hat Size: " + hatTwo.hatSize);
        hatTwo.hatColour = "White";
        System.out.println("Hat Colour: " + hatTwo.hatColour);
        hatTwo.hatPrice = 1500.00;
        System.out.println("Hat Price: ₹" + hatTwo.hatPrice);
        hatTwo.paymentMode = "Cash";
        System.out.println("Payment Mode: " + hatTwo.paymentMode);
        System.out.println("");

        Hat hatThree = new Hat();
        hatThree.hatId = 3;
        System.out.println("Hat ID: " + hatThree.hatId);
        hatThree.brandName = "Puma";
        System.out.println("Brand Name: " + hatThree.brandName);
        hatThree.hatSize = "S";
        System.out.println("Hat Size: " + hatThree.hatSize);
        hatThree.hatColour = "Blue";
        System.out.println("Hat Colour: " + hatThree.hatColour);
        hatThree.hatPrice = 1000.00;
        System.out.println("Hat Price: ₹" + hatThree.hatPrice);
        hatThree.paymentMode = "Card";
        System.out.println("Payment Mode: " + hatThree.paymentMode);
        System.out.println("");

        Hat hatFour = new Hat();
        hatFour.hatId = 4;
        System.out.println("Hat ID: " + hatFour.hatId);
        hatFour.brandName = "Reebok";
        System.out.println("Brand Name: " + hatFour.brandName);
        hatFour.hatSize = "M";
        System.out.println("Hat Size: " + hatFour.hatSize);
        hatFour.hatColour = "Red";
        System.out.println("Hat Colour: " + hatFour.hatColour);
        hatFour.hatPrice = 1100.00;
        System.out.println("Hat Price: ₹" + hatFour.hatPrice);
        hatFour.paymentMode = "Online";
        System.out.println("Payment Mode: " + hatFour.paymentMode);
        System.out.println("");

        Hat hatFive = new Hat();
        hatFive.hatId = 5;
        System.out.println("Hat ID: " + hatFive.hatId);
        hatFive.brandName = "Under Armour";
        System.out.println("Brand Name: " + hatFive.brandName);
        hatFive.hatSize = "L";
        System.out.println("Hat Size: " + hatFive.hatSize);
        hatFive.hatColour = "Green";
        System.out.println("Hat Colour: " + hatFive.hatColour);
        hatFive.hatPrice = 1400.00;
        System.out.println("Hat Price: ₹" + hatFive.hatPrice);
        hatFive.paymentMode = "Cash";
        System.out.println("Payment Mode: " + hatFive.paymentMode);
        System.out.println("");

        Hat hatSix = new Hat();
        hatSix.hatId = 6;
        System.out.println("Hat ID: " + hatSix.hatId);
        hatSix.brandName = "Fila";
        System.out.println("Brand Name: " + hatSix.brandName);
        hatSix.hatSize = "S";
        System.out.println("Hat Size: " + hatSix.hatSize);
        hatSix.hatColour = "Yellow";
        System.out.println("Hat Colour: " + hatSix.hatColour);
        hatSix.hatPrice = 900.00;
        System.out.println("Hat Price: ₹" + hatSix.hatPrice);
        hatSix.paymentMode = "Card";
        System.out.println("Payment Mode: " + hatSix.paymentMode);
        System.out.println("");

        Hat hatSeven = new Hat();
        hatSeven.hatId = 7;
        System.out.println("Hat ID: " + hatSeven.hatId);
        hatSeven.brandName = "New Era";
        System.out.println("Brand Name: " + hatSeven.brandName);
        hatSeven.hatSize = "M";
        System.out.println("Hat Size: " + hatSeven.hatSize);
        hatSeven.hatColour = "Orange";
        System.out.println("Hat Colour: " + hatSeven.hatColour);
        hatSeven.hatPrice = 1300.00;
        System.out.println("Hat Price: ₹" + hatSeven.hatPrice);
        hatSeven.paymentMode = "Online";
        System.out.println("Payment Mode: " + hatSeven.paymentMode);
        System.out.println("");

        Hat hatEight = new Hat();
        hatEight.hatId = 8;
        System.out.println("Hat ID: " + hatEight.hatId);
        hatEight.brandName = "Columbia";
        System.out.println("Brand Name: " + hatEight.brandName);
        hatEight.hatSize = "L";
        System.out.println("Hat Size: " + hatEight.hatSize);
        hatEight.hatColour = "Brown";
        System.out.println("Hat Colour: " + hatEight.hatColour);
        hatEight.hatPrice = 1250.00;
        System.out.println("Hat Price: ₹" + hatEight.hatPrice);
        hatEight.paymentMode = "Cash";
        System.out.println("Payment Mode: " + hatEight.paymentMode);
        System.out.println("");

        Hat hatNine = new Hat();
        hatNine.hatId = 9;
        System.out.println("Hat ID: " + hatNine.hatId);
        hatNine.brandName = "The North Face";
        System.out.println("Brand Name: " + hatNine.brandName);
        hatNine.hatSize = "S";
        System.out.println("Hat Size: " + hatNine.hatSize);
        hatNine.hatColour = "Grey";
        System.out.println("Hat Colour: " + hatNine.hatColour);
        hatNine.hatPrice = 1350.00;
        System.out.println("Hat Price: ₹" + hatNine.hatPrice);
        hatNine.paymentMode = "Card";
        System.out.println("Payment Mode: " + hatNine.paymentMode);
        System.out.println("");

        Hat hatTen = new Hat();
        hatTen.hatId = 10;
        System.out.println("Hat ID: " + hatTen.hatId);
        hatTen.brandName = "Carhartt";
        System.out.println("Brand Name: " + hatTen.brandName);
        hatTen.hatSize = "M";
        System.out.println("Hat Size: " + hatTen.hatSize);
        hatTen.hatColour = "Navy";
        System.out.println("Hat Colour: " + hatTen.hatColour);
        hatTen.hatPrice = 1150.00;
        System.out.println("Hat Price: ₹" + hatTen.hatPrice);
        hatTen.paymentMode = "Online";
        System.out.println("Payment Mode: " + hatTen.paymentMode);
        System.out.println("");

        Hat hatEleven = new Hat();
        hatEleven.hatId = 11;
        System.out.println("Hat ID: " + hatEleven.hatId);
        hatEleven.brandName = "Dickies";
        System.out.println("Brand Name: " + hatEleven.brandName);
        hatEleven.hatSize = "L";
        System.out.println("Hat Size: " + hatEleven.hatSize);
        hatEleven.hatColour = "Beige";
        System.out.println("Hat Colour: " + hatEleven.hatColour);
        hatEleven.hatPrice = 1400.00;
        System.out.println("Hat Price: ₹" + hatEleven.hatPrice);
        hatEleven.paymentMode = "Cash";
        System.out.println("Payment Mode: " + hatEleven.paymentMode);
        System.out.println("");

        Hat hatTwelve = new Hat();
        hatTwelve.hatId = 12;
        System.out.println("Hat ID: " + hatTwelve.hatId);
        hatTwelve.brandName = "Quiksilver";
        System.out.println("Brand Name: " + hatTwelve.brandName);
        hatTwelve.hatSize = "S";
        System.out.println("Hat Size: " + hatTwelve.hatSize);
        hatTwelve.hatColour = "Pink";
        System.out.println("Hat Colour: " + hatTwelve.hatColour);
        hatTwelve.hatPrice = 1050.00;
        System.out.println("Hat Price: ₹" + hatTwelve.hatPrice);
        hatTwelve.paymentMode = "Card";
        System.out.println("Payment Mode: " + hatTwelve.paymentMode);
        System.out.println("");

        Hat hatThirteen = new Hat();
        hatThirteen.hatId = 13;
        System.out.println("Hat ID: " + hatThirteen.hatId);
        hatThirteen.brandName = "Brixton";
        System.out.println("Brand Name: " + hatThirteen.brandName);
        hatThirteen.hatSize = "M";
        System.out.println("Hat Size: " + hatThirteen.hatSize);
        hatThirteen.hatColour = "White";
        System.out.println("Hat Colour: " + hatThirteen.hatColour);
        hatThirteen.hatPrice = 1100.00;
        System.out.println("Hat Price: ₹" + hatThirteen.hatPrice);
        hatThirteen.paymentMode = "Online";
        System.out.println("Payment Mode: " + hatThirteen.paymentMode);
        System.out.println("");

        Hat hatFourteen = new Hat();
        hatFourteen.hatId = 14;
        System.out.println("Hat ID: " + hatFourteen.hatId);
        hatFourteen.brandName = "Vans";
        System.out.println("Brand Name: " + hatFourteen.brandName);
        hatFourteen.hatSize = "L";
        System.out.println("Hat Size: " + hatFourteen.hatSize);
        hatFourteen.hatColour = "Black";
        System.out.println("Hat Colour: " + hatFourteen.hatColour);
        hatFourteen.hatPrice = 1200.00;
        System.out.println("Hat Price: ₹" + hatFourteen.hatPrice);
        hatFourteen.paymentMode = "Cash";
        System.out.println("Payment Mode: " + hatFourteen.paymentMode);
        System.out.println("");

        Hat hatFifteen = new Hat();
        hatFifteen.hatId = 15;
        System.out.println("Hat ID: " + hatFifteen.hatId);
        hatFifteen.brandName = "Supreme";
        System.out.println("Brand Name: " + hatFifteen.brandName);
        hatFifteen.hatSize = "S";
        System.out.println("Hat Size: " + hatFifteen.hatSize);
        hatFifteen.hatColour = "Red";
        System.out.println("Hat Colour: " + hatFifteen.hatColour);
        hatFifteen.hatPrice = 1600.00;
        System.out.println("Hat Price: ₹" + hatFifteen.hatPrice);
        hatFifteen.paymentMode = "Card";
        System.out.println("Payment Mode: " + hatFifteen.paymentMode);

        System.out.println("Main Ended");
    }
}

