class InvitationCardRunner {
    public static void main(String[] args) {
        System.out.println("Main Started");

        InvitationCard cardOne = new InvitationCard();
        cardOne.cardId = 1;
        System.out.println("InvitationCard ID: " + cardOne.cardId);
        cardOne.occasion = "Wedding";
        System.out.println("Occasion: " + cardOne.occasion);
        cardOne.cardSize = "A5";
        System.out.println("Card Size: " + cardOne.cardSize);
        cardOne.cardColor = "Ivory";
        System.out.println("Card Color: " + cardOne.cardColor);
        cardOne.price = 50.00;
        System.out.println("Price: ₹" + cardOne.price);
        cardOne.brand = "ElegantPrints";
        System.out.println("Brand: " + cardOne.brand);
        cardOne.paymentMode = "Online";
        System.out.println("Payment Mode: " + cardOne.paymentMode);
        System.out.println("");

        InvitationCard cardTwo = new InvitationCard();
        cardTwo.cardId = 2;
        System.out.println("InvitationCard ID: " + cardTwo.cardId);
        cardTwo.occasion = "Birthday";
        System.out.println("Occasion: " + cardTwo.occasion);
        cardTwo.cardSize = "A6";
        System.out.println("Card Size: " + cardTwo.cardSize);
        cardTwo.cardColor = "Blue";
        System.out.println("Card Color: " + cardTwo.cardColor);
        cardTwo.price = 40.00;
        System.out.println("Price: ₹" + cardTwo.price);
        cardTwo.brand = "FestiveCards";
        System.out.println("Brand: " + cardTwo.brand);
        cardTwo.paymentMode = "Cash";
        System.out.println("Payment Mode: " + cardTwo.paymentMode);
        System.out.println("");

        InvitationCard cardThree = new InvitationCard();
        cardThree.cardId = 3;
        System.out.println("InvitationCard ID: " + cardThree.cardId);
        cardThree.occasion = "Anniversary";
        System.out.println("Occasion: " + cardThree.occasion);
        cardThree.cardSize = "A5";
        System.out.println("Card Size: " + cardThree.cardSize);
        cardThree.cardColor = "Red";
        System.out.println("Card Color: " + cardThree.cardColor);
        cardThree.price = 60.00;
        System.out.println("Price: ₹" + cardThree.price);
        cardThree.brand = "ClassicInvites";
        System.out.println("Brand: " + cardThree.brand);
        cardThree.paymentMode = "Card";
        System.out.println("Payment Mode: " + cardThree.paymentMode);
        System.out.println("");

        InvitationCard cardFour = new InvitationCard();
        cardFour.cardId = 4;
        System.out.println("InvitationCard ID: " + cardFour.cardId);
        cardFour.occasion = "Baby Shower";
        System.out.println("Occasion: " + cardFour.occasion);
        cardFour.cardSize = "A6";
        System.out.println("Card Size: " + cardFour.cardSize);
        cardFour.cardColor = "Pink";
        System.out.println("Card Color: " + cardFour.cardColor);
        cardFour.price = 45.00;
        System.out.println("Price: ₹" + cardFour.price);
        cardFour.brand = "HappyPrints";
        System.out.println("Brand: " + cardFour.brand);
        cardFour.paymentMode = "UPI";
        System.out.println("Payment Mode: " + cardFour.paymentMode);
        System.out.println("");

        InvitationCard cardFive = new InvitationCard();
        cardFive.cardId = 5;
        System.out.println("InvitationCard ID: " + cardFive.cardId);
        cardFive.occasion = "Graduation";
        System.out.println("Occasion: " + cardFive.occasion);
        cardFive.cardSize = "A5";
        System.out.println("Card Size: " + cardFive.cardSize);
        cardFive.cardColor = "Green";
        System.out.println("Card Color: " + cardFive.cardColor);
        cardFive.price = 55.00;
        System.out.println("Price: ₹" + cardFive.price);
        cardFive.brand = "EliteCards";
        System.out.println("Brand: " + cardFive.brand);
        cardFive.paymentMode = "Online";
        System.out.println("Payment Mode: " + cardFive.paymentMode);
        System.out.println("");

        InvitationCard cardSix = new InvitationCard();
        cardSix.cardId = 6;
        System.out.println("InvitationCard ID: " + cardSix.cardId);
        cardSix.occasion = "Farewell";
        System.out.println("Occasion: " + cardSix.occasion);
        cardSix.cardSize = "A6";
        System.out.println("Card Size: " + cardSix.cardSize);
        cardSix.cardColor = "Yellow";
        System.out.println("Card Color: " + cardSix.cardColor);
        cardSix.price = 42.00;
        System.out.println("Price: ₹" + cardSix.price);
        cardSix.brand = "FarewellCards";
        System.out.println("Brand: " + cardSix.brand);
        cardSix.paymentMode = "Cash";
        System.out.println("Payment Mode: " + cardSix.paymentMode);
        System.out.println("");

        InvitationCard cardSeven = new InvitationCard();
        cardSeven.cardId = 7;
        System.out.println("InvitationCard ID: " + cardSeven.cardId);
        cardSeven.occasion = "Wedding";
        System.out.println("Occasion: " + cardSeven.occasion);
        cardSeven.cardSize = "A4";
        System.out.println("Card Size: " + cardSeven.cardSize);
        cardSeven.cardColor = "Gold";
        System.out.println("Card Color: " + cardSeven.cardColor);
        cardSeven.price = 80.00;
        System.out.println("Price: ₹" + cardSeven.price);
        cardSeven.brand = "RoyalInvites";
        System.out.println("Brand: " + cardSeven.brand);
        cardSeven.paymentMode = "Card";
        System.out.println("Payment Mode: " + cardSeven.paymentMode);
        System.out.println("");

        InvitationCard cardEight = new InvitationCard();
        cardEight.cardId = 8;
        System.out.println("InvitationCard ID: " + cardEight.cardId);
        cardEight.occasion = "Birthday";
        System.out.println("Occasion: " + cardEight.occasion);
        cardEight.cardSize = "A6";
        System.out.println("Card Size: " + cardEight.cardSize);
        cardEight.cardColor = "Purple";
        System.out.println("Card Color: " + cardEight.cardColor);
        cardEight.price = 43.00;
        System.out.println("Price: ₹" + cardEight.price);
        cardEight.brand = "FestiveCards";
        System.out.println("Brand: " + cardEight.brand);
        cardEight.paymentMode = "UPI";
        System.out.println("Payment Mode: " + cardEight.paymentMode);
        System.out.println("");

        InvitationCard cardNine = new InvitationCard();
        cardNine.cardId = 9;
        System.out.println("InvitationCard ID: " + cardNine.cardId);
        cardNine.occasion = "Anniversary";
        System.out.println("Occasion: " + cardNine.occasion);
        cardNine.cardSize = "A5";
        System.out.println("Card Size: " + cardNine.cardSize);
        cardNine.cardColor = "Silver";
        System.out.println("Card Color: " + cardNine.cardColor);
        cardNine.price = 65.00;
        System.out.println("Price: ₹" + cardNine.price);
        cardNine.brand = "ClassicInvites";
        System.out.println("Brand: " + cardNine.brand);
        cardNine.paymentMode = "Online";
        System.out.println("Payment Mode: " + cardNine.paymentMode);
        System.out.println("");

        InvitationCard cardTen = new InvitationCard();
        cardTen.cardId = 10;
        System.out.println("InvitationCard ID: " + cardTen.cardId);
        cardTen.occasion = "Baby Shower";
        System.out.println("Occasion: " + cardTen.occasion);
        cardTen.cardSize = "A6";
        System.out.println("Card Size: " + cardTen.cardSize);
        cardTen.cardColor = "Light Pink";
        System.out.println("Card Color: " + cardTen.cardColor);
        cardTen.price = 48.00;
        System.out.println("Price: ₹" + cardTen.price);
        cardTen.brand = "HappyPrints";
        System.out.println("Brand: " + cardTen.brand);
        cardTen.paymentMode = "Cash";
        System.out.println("Payment Mode: " + cardTen.paymentMode);
        System.out.println("");

        InvitationCard cardEleven = new InvitationCard();
        cardEleven.cardId = 11;
        System.out.println("InvitationCard ID: " + cardEleven.cardId);
        cardEleven.occasion = "Graduation";
        System.out.println("Occasion: " + cardEleven.occasion);
        cardEleven.cardSize = "A5";
        System.out.println("Card Size: " + cardEleven.cardSize);
        cardEleven.cardColor = "Orange";
        System.out.println("Card Color: " + cardEleven.cardColor);
        cardEleven.price = 58.00;
        System.out.println("Price: ₹" + cardEleven.price);
        cardEleven.brand = "EliteCards";
        System.out.println("Brand: " + cardEleven.brand);
        cardEleven.paymentMode = "Online";
        System.out.println("Payment Mode: " + cardEleven.paymentMode);
        System.out.println("");

        InvitationCard cardTwelve = new InvitationCard();
        cardTwelve.cardId = 12;
        System.out.println("InvitationCard ID: " + cardTwelve.cardId);
        cardTwelve.occasion = "Farewell";
        System.out.println("Occasion: " + cardTwelve.occasion);
        cardTwelve.cardSize = "A6";
        System.out.println("Card Size: " + cardTwelve.cardSize);
        cardTwelve.cardColor = "Brown";
        System.out.println("Card Color: " + cardTwelve.cardColor);
        cardTwelve.price = 44.00;
        System.out.println("Price: ₹" + cardTwelve.price);
        cardTwelve.brand = "FarewellCards";
        System.out.println("Brand: " + cardTwelve.brand);
        cardTwelve.paymentMode = "Card";
        System.out.println("Payment Mode: " + cardTwelve.paymentMode);
        System.out.println("");

        InvitationCard cardThirteen = new InvitationCard();
        cardThirteen.cardId = 13;
        System.out.println("InvitationCard ID: " + cardThirteen.cardId);
        cardThirteen.occasion = "Wedding";
        System.out.println("Occasion: " + cardThirteen.occasion);
        cardThirteen.cardSize = "A4";
        System.out.println("Card Size: " + cardThirteen.cardSize);
        cardThirteen.cardColor = "White";
        System.out.println("Card Color: " + cardThirteen.cardColor);
        cardThirteen.price = 75.00;
        System.out.println("Price: ₹" + cardThirteen.price);
        cardThirteen.brand = "RoyalInvites";
        System.out.println("Brand: " + cardThirteen.brand);
        cardThirteen.paymentMode = "UPI";
        System.out.println("Payment Mode: " + cardThirteen.paymentMode);
        System.out.println("");

        InvitationCard cardFourteen = new InvitationCard();
        cardFourteen.cardId = 14;
        System.out.println("InvitationCard ID: " + cardFourteen.cardId);
        cardFourteen.occasion = "Birthday";
        System.out.println("Occasion: " + cardFourteen.occasion);
        cardFourteen.cardSize = "A6";
        System.out.println("Card Size: " + cardFourteen.cardSize);
        cardFourteen.cardColor = "Cyan";
        System.out.println("Card Color: " + cardFourteen.cardColor);
        cardFourteen.price = 41.00;
        System.out.println("Price: ₹" + cardFourteen.price);
        cardFourteen.brand = "FestiveCards";
        System.out.println("Brand: " + cardFourteen.brand);
        cardFourteen.paymentMode = "Cash";
        System.out.println("Payment Mode: " + cardFourteen.paymentMode);
        System.out.println("");

        InvitationCard cardFifteen = new InvitationCard();
        cardFifteen.cardId = 15;
        System.out.println("InvitationCard ID: " + cardFifteen.cardId);
        cardFifteen.occasion = "Anniversary";
        System.out.println("Occasion: " + cardFifteen.occasion);
        cardFifteen.cardSize = "A5";
        System.out.println("Card Size: " + cardFifteen.cardSize);
        cardFifteen.cardColor = "Maroon";
        System.out.println("Card Color: " + cardFifteen.cardColor);
        cardFifteen.price = 62.00;
        System.out.println("Price: ₹" + cardFifteen.price);
        cardFifteen.brand = "ClassicInvites";
        System.out.println("Brand: " + cardFifteen.brand);
        cardFifteen.paymentMode = "Online";
        System.out.println("Payment Mode: " + cardFifteen.paymentMode);

        System.out.println("Main Ended");
    }
}