class JwelleryRunner {
    public static void main(String[] args) {
        System.out.println("Main Started");

        Jwellery jwelleryOne = new Jwellery();
        jwelleryOne.jwelleryId = 1;
        System.out.println("Jwellery ID: " + jwelleryOne.jwelleryId);
        jwelleryOne.type = "Necklace";
        System.out.println("Type: " + jwelleryOne.type);
        jwelleryOne.material = "Gold";
        System.out.println("Material: " + jwelleryOne.material);
        jwelleryOne.brand = "Tanishq";
        System.out.println("Brand: " + jwelleryOne.brand);
        jwelleryOne.price = 75000.00;
        System.out.println("Price: ₹" + jwelleryOne.price);
        jwelleryOne.paymentMode = "Online";
        System.out.println("Payment Mode: " + jwelleryOne.paymentMode);
        System.out.println("");

        Jwellery jwelleryTwo = new Jwellery();
        jwelleryTwo.jwelleryId = 2;
        System.out.println("Jwellery ID: " + jwelleryTwo.jwelleryId);
        jwelleryTwo.type = "Ring";
        System.out.println("Type: " + jwelleryTwo.type);
        jwelleryTwo.material = "Platinum";
        System.out.println("Material: " + jwelleryTwo.material);
        jwelleryTwo.brand = "CaratLane";
        System.out.println("Brand: " + jwelleryTwo.brand);
        jwelleryTwo.price = 22000.00;
        System.out.println("Price: ₹" + jwelleryTwo.price);
        jwelleryTwo.paymentMode = "Card";
        System.out.println("Payment Mode: " + jwelleryTwo.paymentMode);
        System.out.println("");

        Jwellery jwelleryThree = new Jwellery();
        jwelleryThree.jwelleryId = 3;
        System.out.println("Jwellery ID: " + jwelleryThree.jwelleryId);
        jwelleryThree.type = "Earrings";
        System.out.println("Type: " + jwelleryThree.type);
        jwelleryThree.material = "Silver";
        System.out.println("Material: " + jwelleryThree.material);
        jwelleryThree.brand = "Bluestone";
        System.out.println("Brand: " + jwelleryThree.brand);
        jwelleryThree.price = 4500.00;
        System.out.println("Price: ₹" + jwelleryThree.price);
        jwelleryThree.paymentMode = "UPI";
        System.out.println("Payment Mode: " + jwelleryThree.paymentMode);
        System.out.println("");

        Jwellery jwelleryFour = new Jwellery();
        jwelleryFour.jwelleryId = 4;
        System.out.println("Jwellery ID: " + jwelleryFour.jwelleryId);
        jwelleryFour.type = "Bracelet";
        System.out.println("Type: " + jwelleryFour.type);
        jwelleryFour.material = "Gold";
        System.out.println("Material: " + jwelleryFour.material);
        jwelleryFour.brand = "Malabar Gold";
        System.out.println("Brand: " + jwelleryFour.brand);
        jwelleryFour.price = 18500.00;
        System.out.println("Price: ₹" + jwelleryFour.price);
        jwelleryFour.paymentMode = "Cash";
        System.out.println("Payment Mode: " + jwelleryFour.paymentMode);
        System.out.println("");

        Jwellery jwelleryFive = new Jwellery();
        jwelleryFive.jwelleryId = 5;
        System.out.println("Jwellery ID: " + jwelleryFive.jwelleryId);
        jwelleryFive.type = "Anklet";
        System.out.println("Type: " + jwelleryFive.type);
        jwelleryFive.material = "Silver";
        System.out.println("Material: " + jwelleryFive.material);
        jwelleryFive.brand = "Tribes India";
        System.out.println("Brand: " + jwelleryFive.brand);
        jwelleryFive.price = 3200.00;
        System.out.println("Price: ₹" + jwelleryFive.price);
        jwelleryFive.paymentMode = "UPI";
        System.out.println("Payment Mode: " + jwelleryFive.paymentMode);
        System.out.println("");

        Jwellery jwellerySix = new Jwellery();
        jwellerySix.jwelleryId = 6;
        System.out.println("Jwellery ID: " + jwellerySix.jwelleryId);
        jwellerySix.type = "Pendant";
        System.out.println("Type: " + jwellerySix.type);
        jwellerySix.material = "Gold";
        System.out.println("Material: " + jwellerySix.material);
        jwellerySix.brand = "Kalyan Jewellers";
        System.out.println("Brand: " + jwellerySix.brand);
        jwellerySix.price = 15800.00;
        System.out.println("Price: ₹" + jwellerySix.price);
        jwellerySix.paymentMode = "Card";
        System.out.println("Payment Mode: " + jwellerySix.paymentMode);
        System.out.println("");

        Jwellery jwellerySeven = new Jwellery();
        jwellerySeven.jwelleryId = 7;
        System.out.println("Jwellery ID: " + jwellerySeven.jwelleryId);
        jwellerySeven.type = "Bangle";
        System.out.println("Type: " + jwellerySeven.type);
        jwellerySeven.material = "Platinum";
        System.out.println("Material: " + jwellerySeven.material);
        jwellerySeven.brand = "Joyalukkas";
        System.out.println("Brand: " + jwellerySeven.brand);
        jwellerySeven.price = 30000.00;
        System.out.println("Price: ₹" + jwellerySeven.price);
        jwellerySeven.paymentMode = "Online";
        System.out.println("Payment Mode: " + jwellerySeven.paymentMode);
        System.out.println("");

        Jwellery jwelleryEight = new Jwellery();
        jwelleryEight.jwelleryId = 8;
        System.out.println("Jwellery ID: " + jwelleryEight.jwelleryId);
        jwelleryEight.type = "Toe Ring";
        System.out.println("Type: " + jwelleryEight.type);
        jwelleryEight.material = "Silver";
        System.out.println("Material: " + jwelleryEight.material);
        jwelleryEight.brand = "Zaveri Pearls";
        System.out.println("Brand: " + jwelleryEight.brand);
        jwelleryEight.price = 600.00;
        System.out.println("Price: ₹" + jwelleryEight.price);
        jwelleryEight.paymentMode = "Cash";
        System.out.println("Payment Mode: " + jwelleryEight.paymentMode);
        System.out.println("");

        Jwellery jwelleryNine = new Jwellery();
        jwelleryNine.jwelleryId = 9;
        System.out.println("Jwellery ID: " + jwelleryNine.jwelleryId);
        jwelleryNine.type = "Nose Pin";
        System.out.println("Type: " + jwelleryNine.type);
        jwelleryNine.material = "Gold";
        System.out.println("Material: " + jwelleryNine.material);
        jwelleryNine.brand = "Tanishq";
        System.out.println("Brand: " + jwelleryNine.brand);
        jwelleryNine.price = 2100.00;
        System.out.println("Price: ₹" + jwelleryNine.price);
        jwelleryNine.paymentMode = "UPI";
        System.out.println("Payment Mode: " + jwelleryNine.paymentMode);
        System.out.println("");

        Jwellery jwelleryTen = new Jwellery();
        jwelleryTen.jwelleryId = 10;
        System.out.println("Jwellery ID: " + jwelleryTen.jwelleryId);
        jwelleryTen.type = "Brooch";
        System.out.println("Type: " + jwelleryTen.type);
        jwelleryTen.material = "Diamond";
        System.out.println("Material: " + jwelleryTen.material);
        jwelleryTen.brand = "Bluestone";
        System.out.println("Brand: " + jwelleryTen.brand);
        jwelleryTen.price = 12000.00;
        System.out.println("Price: ₹" + jwelleryTen.price);
        jwelleryTen.paymentMode = "Online";
        System.out.println("Payment Mode: " + jwelleryTen.paymentMode);
        System.out.println("");

        Jwellery jwelleryEleven = new Jwellery();
        jwelleryEleven.jwelleryId = 11;
        System.out.println("Jwellery ID: " + jwelleryEleven.jwelleryId);
        jwelleryEleven.type = "Chain";
        System.out.println("Type: " + jwelleryEleven.type);
        jwelleryEleven.material = "Gold";
        System.out.println("Material: " + jwelleryEleven.material);
        jwelleryEleven.brand = "Malabar Gold";
        System.out.println("Brand: " + jwelleryEleven.brand);
        jwelleryEleven.price = 55000.00;
        System.out.println("Price: ₹" + jwelleryEleven.price);
        jwelleryEleven.paymentMode = "Card";
        System.out.println("Payment Mode: " + jwelleryEleven.paymentMode);
        System.out.println("");
    }
}
