class KarateRunner {
    public static void main(String[] args) {
        System.out.println("Main Started");

        Karate karateOne = new Karate();
        karateOne.karateId = 1;
        System.out.println("Karate ID: " + karateOne.karateId);
        karateOne.style = "Shotokan";
        System.out.println("Style: " + karateOne.style);
        karateOne.beltColor = "White";
        System.out.println("Belt Color: " + karateOne.beltColor);
        karateOne.experienceYears = 1;
        System.out.println("Experience Years: " + karateOne.experienceYears);
        karateOne.dojoName = "Dojo A";
        System.out.println("Dojo Name: " + karateOne.dojoName);
        karateOne.competition = false;
        System.out.println("Competition: " + karateOne.competition);
        karateOne.rating = 4.0;
        System.out.println("Rating: " + karateOne.rating);
        karateOne.paymentMode = "Cash";
        System.out.println("Payment Mode: " + karateOne.paymentMode);
        System.out.println();

        Karate karateTwo = new Karate();
        karateTwo.karateId = 2;
        System.out.println("Karate ID: " + karateTwo.karateId);
        karateTwo.style = "Goju‑ryu";
        System.out.println("Style: " + karateTwo.style);
        karateTwo.beltColor = "Yellow";
        System.out.println("Belt Color: " + karateTwo.beltColor);
        karateTwo.experienceYears = 2;
        System.out.println("Experience Years: " + karateTwo.experienceYears);
        karateTwo.dojoName = "Dojo B";
        System.out.println("Dojo Name: " + karateTwo.dojoName);
        karateTwo.competition = true;
        System.out.println("Competition: " + karateTwo.competition);
        karateTwo.rating = 4.2;
        System.out.println("Rating: " + karateTwo.rating);
        karateTwo.paymentMode = "Card";
        System.out.println("Payment Mode: " + karateTwo.paymentMode);
        System.out.println();

        Karate karateThree = new Karate();
        karateThree.karateId = 3;
        System.out.println("Karate ID: " + karateThree.karateId);
        karateThree.style = "Shito‑ryu";
        System.out.println("Style: " + karateThree.style);
        karateThree.beltColor = "Orange";
        System.out.println("Belt Color: " + karateThree.beltColor);
        karateThree.experienceYears = 3;
        System.out.println("Experience Years: " + karateThree.experienceYears);
        karateThree.dojoName = "Dojo C";
        System.out.println("Dojo Name: " + karateThree.dojoName);
        karateThree.competition = false;
        System.out.println("Competition: " + karateThree.competition);
        karateThree.rating = 4.5;
        System.out.println("Rating: " + karateThree.rating);
        karateThree.paymentMode = "Online";
        System.out.println("Payment Mode: " + karateThree.paymentMode);
        System.out.println();

        Karate karateFour = new Karate();
        karateFour.karateId = 4;
        System.out.println("Karate ID: " + karateFour.karateId);
        karateFour.style = "Wado‑ryu";
        System.out.println("Style: " + karateFour.style);
        karateFour.beltColor = "Green";
        System.out.println("Belt Color: " + karateFour.beltColor);
        karateFour.experienceYears = 4;
        System.out.println("Experience Years: " + karateFour.experienceYears);
        karateFour.dojoName = "Dojo D";
        System.out.println("Dojo Name: " + karateFour.dojoName);
        karateFour.competition = true;
        System.out.println("Competition: " + karateFour.competition);
        karateFour.rating = 4.6;
        System.out.println("Rating: " + karateFour.rating);
        karateFour.paymentMode = "Cash";
        System.out.println("Payment Mode: " + karateFour.paymentMode);
        System.out.println();

        Karate karateFive = new Karate();
        karateFive.karateId = 5;
        System.out.println("Karate ID: " + karateFive.karateId);
        karateFive.style = "Kyokushin";
        System.out.println("Style: " + karateFive.style);
        karateFive.beltColor = "Blue";
        System.out.println("Belt Color: " + karateFive.beltColor);
        karateFive.experienceYears = 5;
        System.out.println("Experience Years: " + karateFive.experienceYears);
        karateFive.dojoName = "Dojo E";
        System.out.println("Dojo Name: " + karateFive.dojoName);
        karateFive.competition = false;
        System.out.println("Competition: " + karateFive.competition);
        karateFive.rating = 4.7;
        System.out.println("Rating: " + karateFive.rating);
        karateFive.paymentMode = "Card";
        System.out.println("Payment Mode: " + karateFive.paymentMode);
        System.out.println();

        Karate karateSix = new Karate();
        karateSix.karateId = 6;
        System.out.println("Karate ID: " + karateSix.karateId);
        karateSix.style = "Uechi‑ryu";
        System.out.println("Style: " + karateSix.style);
        karateSix.beltColor = "Purple";
        System.out.println("Belt Color: " + karateSix.beltColor);
        karateSix.experienceYears = 6;
        System.out.println("Experience Years: " + karateSix.experienceYears);
        karateSix.dojoName = "Dojo F";
        System.out.println("Dojo Name: " + karateSix.dojoName);
        karateSix.competition = true;
        System.out.println("Competition: " + karateSix.competition);
        karateSix.rating = 4.8;
        System.out.println("Rating: " + karateSix.rating);
        karateSix.paymentMode = "Online";
        System.out.println("Payment Mode: " + karateSix.paymentMode);
        System.out.println();

        Karate karateSeven = new Karate();
        karateSeven.karateId = 7;
        System.out.println("Karate ID: " + karateSeven.karateId);
        karateSeven.style = "Enshin‑ryu";
        System.out.println("Style: " + karateSeven.style);
        karateSeven.beltColor = "Brown";
        System.out.println("Belt Color: " + karateSeven.beltColor);
        karateSeven.experienceYears = 7;
        System.out.println("Experience Years: " + karateSeven.experienceYears);
        karateSeven.dojoName = "Dojo G";
        System.out.println("Dojo Name: " + karateSeven.dojoName);
        karateSeven.competition = false;
        System.out.println("Competition: " + karateSeven.competition);
        karateSeven.rating = 4.9;
        System.out.println("Rating: " + karateSeven.rating);
        karateSeven.paymentMode = "Cash";
        System.out.println("Payment Mode: " + karateSeven.paymentMode);
        System.out.println();

        Karate karateEight = new Karate();
        karateEight.karateId = 8;
        System.out.println("Karate ID: " + karateEight.karateId);
        karateEight.style = "Shorin‑ryu";
        System.out.println("Style: " + karateEight.style);
        karateEight.beltColor = "Black";
        System.out.println("Belt Color: " + karateEight.beltColor);
        karateEight.experienceYears = 8;
        System.out.println("Experience Years: " + karateEight.experienceYears);
        karateEight.dojoName = "Dojo H";
        System.out.println("Dojo Name: " + karateEight.dojoName);
        karateEight.competition = true;
        System.out.println("Competition: " + karateEight.competition);
        karateEight.rating = 5.0;
        System.out.println("Rating: " + karateEight.rating);
        karateEight.paymentMode = "Card";
        System.out.println("Payment Mode: " + karateEight.paymentMode);
        System.out.println();

        Karate karateNine = new Karate();
        karateNine.karateId = 9;
        System.out.println("Karate ID: " + karateNine.karateId);
        karateNine.style = "Isshin‑ryu";
        System.out.println("Style: " + karateNine.style);
        karateNine.beltColor = "Red";
        System.out.println("Belt Color: " + karateNine.beltColor);
        karateNine.experienceYears = 9;
        System.out.println("Experience Years: " + karateNine.experienceYears);
        karateNine.dojoName = "Dojo I";
        System.out.println("Dojo Name: " + karateNine.dojoName);
        karateNine.competition = false;
        System.out.println("Competition: " + karateNine.competition);
        karateNine.rating = 4.6;
        System.out.println("Rating: " + karateNine.rating);
        karateNine.paymentMode = "Online";
        System.out.println("Payment Mode: " + karateNine.paymentMode);
        System.out.println();

        Karate karateTen = new Karate();
        karateTen.karateId = 10;
        System.out.println("Karate ID: " + karateTen.karateId);
        karateTen.style = "Goju‑ryu";
        System.out.println("Style: " + karateTen.style);
        karateTen.beltColor = "Blue";
        System.out.println("Belt Color: " + karateTen.beltColor);
        karateTen.experienceYears = 10;
        System.out.println("Experience Years: " + karateTen.experienceYears);
        karateTen.dojoName = "Dojo J";
        System.out.println("Dojo Name: " + karateTen.dojoName);
        karateTen.competition = true;
        System.out.println("Competition: " + karateTen.competition);
        karateTen.rating = 4.7;
        System.out.println("Rating: " + karateTen.rating);
        karateTen.paymentMode = "Cash";
        System.out.println("Payment Mode: " + karateTen.paymentMode);
        System.out.println();

        Karate karateEleven = new Karate();
        karateEleven.karateId = 11;
        System.out.println("Karate ID: " + karateEleven.karateId);
        karateEleven.style = "Shotokan";
        System.out.println("Style: " + karateEleven.style);
        karateEleven.beltColor = "Green";
        System.out.println("Belt Color: " + karateEleven.beltColor);
        karateEleven.experienceYears = 11;
        System.out.println("Experience Years: " + karateEleven.experienceYears);
        karateEleven.dojoName = "Dojo K";
        System.out.println("Dojo Name: " + karateEleven.dojoName);
        karateEleven.competition = false;
        System.out.println("Competition: " + karateEleven.competition);
        karateEleven.rating = 4.8;
        System.out.println("Rating: " + karateEleven.rating);
        karateEleven.paymentMode = "Online";
        System.out.println("Payment Mode: " + karateEleven.paymentMode);
        System.out.println();

        Karate karateTwelve = new Karate();
        karateTwelve.karateId = 12;
        System.out.println("Karate ID: " + karateTwelve.karateId);
        karateTwelve.style = "Wado‑ryu";
        System.out.println("Style: " + karateTwelve.style);
        karateTwelve.beltColor = "Purple";
        System.out.println("Belt Color: " + karateTwelve.beltColor);
        karateTwelve.experienceYears = 12;
        System.out.println("Experience Years: " + karateTwelve.experienceYears);
        karateTwelve.dojoName = "Dojo L";
        System.out.println("Dojo Name: " + karateTwelve.dojoName);
        karateTwelve.competition = true;
        System.out.println("Competition: " + karateTwelve.competition);
        karateTwelve.rating = 4.9;
        System.out.println("Rating: " + karateTwelve.rating);
        karateTwelve.paymentMode = "Card";
        System.out.println("Payment Mode: " + karateTwelve.paymentMode);
        System.out.println();

        Karate karateThirteen = new Karate();
        karateThirteen.karateId = 13;
        System.out.println("Karate ID: " + karateThirteen.karateId);
        karateThirteen.style = "Shito‑ryu";
        System.out.println("Style: " + karateThirteen.style);
        karateThirteen.beltColor = "Brown";
        System.out.println("Belt Color: " + karateThirteen.beltColor);
        karateThirteen.experienceYears = 13;
        System.out.println("Experience Years: " + karateThirteen.experienceYears);
        karateThirteen.dojoName = "Dojo M";
        System.out.println("Dojo Name: " + karateThirteen.dojoName);
        karateThirteen.competition = false;
        System.out.println("Competition: " + karateThirteen.competition);
        karateThirteen.rating = 5.0;
        System.out.println("Rating: " + karateThirteen.rating);
        karateThirteen.paymentMode = "Online";
        System.out.println("Payment Mode: " + karateThirteen.paymentMode);
        System.out.println();

        Karate karateFourteen = new Karate();
        karateFourteen.karateId = 14;
        System.out.println("Karate ID: " + karateFourteen.karateId);
        karateFourteen.style = "Kyokushin";
        System.out.println("Style: " + karateFourteen.style);
        karateFourteen.beltColor = "Black";
        System.out.println("Belt Color: " + karateFourteen.beltColor);
        karateFourteen.experienceYears = 14;
        System.out.println("Experience Years: " + karateFourteen.experienceYears);
        karateFourteen.dojoName = "Dojo N";
        System.out.println("Dojo Name: " + karateFourteen.dojoName);
        karateFourteen.competition = true;
        System.out.println("Competition: " + karateFourteen.competition);
        karateFourteen.rating = 4.4;
        System.out.println("Rating: " + karateFourteen.rating);
        karateFourteen.paymentMode = "Card";
        System.out.println("Payment Mode: " + karateFourteen.paymentMode);
        System.out.println();

        Karate karateFifteen = new Karate();
        karateFifteen.karateId = 15;
        System.out.println("Karate ID: " + karateFifteen.karateId);
        karateFifteen.style = "Uechi‑ryu";
        System.out.println("Style: " + karateFifteen.style);
        karateFifteen.beltColor = "Red";
        System.out.println("Belt Color: " + karateFifteen.beltColor);
        karateFifteen.experienceYears = 15;
        System.out.println("Experience Years: " + karateFifteen.experienceYears);
        karateFifteen.dojoName = "Dojo O";
        System.out.println("Dojo Name: " + karateFifteen.dojoName);
        karateFifteen.competition = false;
        System.out.println("Competition: " + karateFifteen.competition);
        karateFifteen.rating = 4.2;
        System.out.println("Rating: " + karateFifteen.rating);
        karateFifteen.paymentMode = "Online";
        System.out.println("Payment Mode: " + karateFifteen.paymentMode);
        System.out.println();

        System.out.println("Main Ended");
    }
}
