class KingRunner {
    public static void main(String[] args) {
        System.out.println("Main Started");

        King kingOne = new King();
        kingOne.kingId = 1;
        System.out.println("King ID: " + kingOne.kingId);
        kingOne.name = "Arthur";
        System.out.println("Name: " + kingOne.name);
        kingOne.kingdom = "Camelot";
        System.out.println("Kingdom: " + kingOne.kingdom);
        kingOne.reignYears = 35;
        System.out.println("Reign Years: " + kingOne.reignYears);
        kingOne.capitalCity = "Camelot City";
        System.out.println("Capital City: " + kingOne.capitalCity);
        kingOne.religion = "Christianity";
        System.out.println("Religion: " + kingOne.religion);
        kingOne.wealth = 1000000.00;
        System.out.println("Wealth: $" + kingOne.wealth);
        kingOne.paymentMode = "Royal Treasury";
        System.out.println("Payment Mode: " + kingOne.paymentMode);
        System.out.println();

        King kingTwo = new King();
        kingTwo.kingId = 2;
        System.out.println("King ID: " + kingTwo.kingId);
        kingTwo.name = "Louis XIV";
        System.out.println("Name: " + kingTwo.name);
        kingTwo.kingdom = "France";
        System.out.println("Kingdom: " + kingTwo.kingdom);
        kingTwo.reignYears = 72;
        System.out.println("Reign Years: " + kingTwo.reignYears);
        kingTwo.capitalCity = "Paris";
        System.out.println("Capital City: " + kingTwo.capitalCity);
        kingTwo.religion = "Catholicism";
        System.out.println("Religion: " + kingTwo.religion);
        kingTwo.wealth = 2500000.00;
        System.out.println("Wealth: $" + kingTwo.wealth);
        kingTwo.paymentMode = "Royal Treasury";
        System.out.println("Payment Mode: " + kingTwo.paymentMode);
        System.out.println();

        King kingThree = new King();
        kingThree.kingId = 3;
        System.out.println("King ID: " + kingThree.kingId);
        kingThree.name = "Henry VIII";
        System.out.println("Name: " + kingThree.name);
        kingThree.kingdom = "England";
        System.out.println("Kingdom: " + kingThree.kingdom);
        kingThree.reignYears = 38;
        System.out.println("Reign Years: " + kingThree.reignYears);
        kingThree.capitalCity = "London";
        System.out.println("Capital City: " + kingThree.capitalCity);
        kingThree.religion = "Church of England";
        System.out.println("Religion: " + kingThree.religion);
        kingThree.wealth = 1800000.00;
        System.out.println("Wealth: $" + kingThree.wealth);
        kingThree.paymentMode = "Royal Treasury";
        System.out.println("Payment Mode: " + kingThree.paymentMode);
        System.out.println();

        // … Continue same pattern for kingFour to kingFifteen

        King kingFour = new King();
        kingFour.kingId = 4;
        System.out.println("King ID: " + kingFour.kingId);
        kingFour.name = "Akbar";
        System.out.println("Name: " + kingFour.name);
        kingFour.kingdom = "Mughal Empire";
        System.out.println("Kingdom: " + kingFour.kingdom);
        kingFour.reignYears = 49;
        System.out.println("Reign Years: " + kingFour.reignYears);
        kingFour.capitalCity = "Fatehpur Sikri";
        System.out.println("Capital City: " + kingFour.capitalCity);
        kingFour.religion = "Islam";
        System.out.println("Religion: " + kingFour.religion);
        kingFour.wealth = 3000000.00;
        System.out.println("Wealth: $" + kingFour.wealth);
        kingFour.paymentMode = "Royal Treasury";
        System.out.println("Payment Mode: " + kingFour.paymentMode);
        System.out.println();

        King kingFive = new King();
        kingFive.kingId = 5;
        System.out.println("King ID: " + kingFive.kingId);
        kingFive.name = "Ramses II";
        System.out.println("Name: " + kingFive.name);
        kingFive.kingdom = "Ancient Egypt";
        System.out.println("Kingdom: " + kingFive.kingdom);
        kingFive.reignYears = 66;
        System.out.println("Reign Years: " + kingFive.reignYears);
        kingFive.capitalCity = "Thebes";
        System.out.println("Capital City: " + kingFive.capitalCity);
        kingFive.religion = "Ancient Egyptian Religion";
        System.out.println("Religion: " + kingFive.religion);
        kingFive.wealth = 2200000.00;
        System.out.println("Wealth: $" + kingFive.wealth);
        kingFive.paymentMode = "Royal Treasury";
        System.out.println("Payment Mode: " + kingFive.paymentMode);
        System.out.println();

        King kingSix = new King();
        kingSix.kingId = 6;
        System.out.println("King ID: " + kingSix.kingId);
        kingSix.name = "Charlemagne";
        System.out.println("Name: " + kingSix.name);
        kingSix.kingdom = "Holy Roman Empire";
        System.out.println("Kingdom: " + kingSix.kingdom);
        kingSix.reignYears = 46;
        System.out.println("Reign Years: " + kingSix.reignYears);
        kingSix.capitalCity = "Aachen";
        System.out.println("Capital City: " + kingSix.capitalCity);
        kingSix.religion = "Christianity";
        System.out.println("Religion: " + kingSix.religion);
        kingSix.wealth = 2100000.00;
        System.out.println("Wealth: $" + kingSix.wealth);
        kingSix.paymentMode = "Royal Treasury";
        System.out.println("Payment Mode: " + kingSix.paymentMode);
        System.out.println();

        King kingSeven = new King();
        kingSeven.kingId = 7;
        System.out.println("King ID: " + kingSeven.kingId);
        kingSeven.name = "Saladin";
        System.out.println("Name: " + kingSeven.name);
        kingSeven.kingdom = "Ayyubid Sultanate";
        System.out.println("Kingdom: " + kingSeven.kingdom);
        kingSeven.reignYears = 16;
        System.out.println("Reign Years: " + kingSeven.reignYears);
        kingSeven.capitalCity = "Cairo";
        System.out.println("Capital City: " + kingSeven.capitalCity);
        kingSeven.religion = "Islam";
        System.out.println("Religion: " + kingSeven.religion);
        kingSeven.wealth = 1500000.00;
        System.out.println("Wealth: $" + kingSeven.wealth);
        kingSeven.paymentMode = "Royal Treasury";
        System.out.println("Payment Mode: " + kingSeven.paymentMode);
        System.out.println();

        King kingEight = new King();
        kingEight.kingId = 8;
        System.out.println("King ID: " + kingEight.kingId);
        kingEight.name = "Louis IX";
        System.out.println("Name: " + kingEight.name);
        kingEight.kingdom = "France";
        System.out.println("Kingdom: " + kingEight.kingdom);
        kingEight.reignYears = 44;
        System.out.println("Reign Years: " + kingEight.reignYears);
        kingEight.capitalCity = "Paris";
        System.out.println("Capital City: " + kingEight.capitalCity);
        kingEight.religion = "Catholicism";
        System.out.println("Religion: " + kingEight.religion);
        kingEight.wealth = 2400000.00;
        System.out.println("Wealth: $" + kingEight.wealth);
        kingEight.paymentMode = "Royal Treasury";
        System.out.println("Payment Mode: " + kingEight.paymentMode);
        System.out.println();

        King kingNine = new King();
        kingNine.kingId = 9;
        System.out.println("King ID: " + kingNine.kingId);
        kingNine.name = "Peter the Great";
        System.out.println("Name: " + kingNine.name);
        kingNine.kingdom = "Russia";
        System.out.println("Kingdom: " + kingNine.kingdom);
        kingNine.reignYears = 43;
        System.out.println("Reign Years: " + kingNine.reignYears);
        kingNine.capitalCity = "Saint Petersburg";
        System.out.println("Capital City: " + kingNine.capitalCity);
        kingNine.religion = "Eastern Orthodoxy";
        System.out.println("Religion: " + kingNine.religion);
        kingNine.wealth = 2800000.00;
        System.out.println("Wealth: $" + kingNine.wealth);
        kingNine.paymentMode = "Royal Treasury";
        System.out.println("Payment Mode: " + kingNine.paymentMode);
        System.out.println();

        King kingTen = new King();
        kingTen.kingId = 10;
        System.out.println("King ID: " + kingTen.kingId);
        kingTen.name = "David";
        System.out.println("Name: " + kingTen.name);
        kingTen.kingdom = "Israel";
        System.out.println("Kingdom: " + kingTen.kingdom);
        kingTen.reignYears = 40;
        System.out.println("Reign Years: " + kingTen.reignYears);
        kingTen.capitalCity = "Jerusalem";
        System.out.println("Capital City: " + kingTen.capitalCity);
        kingTen.religion = "Judaism";
        System.out.println("Religion: " + kingTen.religion);
        kingTen.wealth = 1700000.00;
        System.out.println("Wealth: $" + kingTen.wealth);
        kingTen.paymentMode = "Royal Treasury";
        System.out.println("Payment Mode: " + kingTen.paymentMode);
        System.out.println();

        King kingEleven = new King();
        kingEleven.kingId = 11;
        System.out.println("King ID: " + kingEleven.kingId);
        kingEleven.name = "Julius Caesar";
        System.out.println("Name: " + kingEleven.name);
        kingEleven.kingdom = "Roman Republic";
        System.out.println("Kingdom: " + kingEleven.kingdom);
        kingEleven.reignYears = 10;
        System.out.println("Reign Years: " + kingEleven.reignYears);
        kingEleven.capitalCity = "Rome";
        System.out.println("Capital City: " + kingEleven.capitalCity);
        kingEleven.religion = "Roman Religion";
        System.out.println("Religion: " + kingEleven.religion);
        kingEleven.wealth = 2000000.00;
        System.out.println("Wealth: $" + kingEleven.wealth);
        kingEleven.paymentMode = "Royal Treasury";
        System.out.println("Payment Mode: " + kingEleven.paymentMode);
        System.out.println();

        King kingTwelve = new King();
        kingTwelve.kingId = 12;
        System.out.println("King ID: " + kingTwelve.kingId);
        kingTwelve.name = "Solomon";
        System.out.println("Name: " + kingTwelve.name);
        kingTwelve.kingdom = "Israel";
        System.out.println("Kingdom: " + kingTwelve.kingdom);
        kingTwelve.reignYears = 40;
        System.out.println("Reign Years: " + kingTwelve.reignYears);
        kingTwelve.capitalCity = "Jerusalem";
        System.out.println("Capital City: " + kingTwelve.capitalCity);
        kingTwelve.religion = "Judaism";
        System.out.println("Religion: " + kingTwelve.religion);
        kingTwelve.wealth = 2600000.00;
        System.out.println("Wealth: $" + kingTwelve.wealth);
        kingTwelve.paymentMode = "Royal Treasury";
        System.out.println("Payment Mode: " + kingTwelve.paymentMode);
        System.out.println();

        King kingThirteen = new King();
        kingThirteen.kingId = 13;
        System.out.println("King ID: " + kingThirteen.kingId);
        kingThirteen.name = "Ashoka";
        System.out.println("Name: " + kingThirteen.name);
        kingThirteen.kingdom = "Maurya Empire";
        System.out.println("Kingdom: " + kingThirteen.kingdom);
        kingThirteen.reignYears = 37;
        System.out.println("Reign Years: " + kingThirteen.reignYears);
        kingThirteen.capitalCity = "Pataliputra";
        System.out.println("Capital City: " + kingThirteen.capitalCity);
        kingThirteen.religion = "Buddhism";
        System.out.println("Religion: " + kingThirteen.religion);
        kingThirteen.wealth = 2300000.00;
        System.out.println("Wealth: $" + kingThirteen.wealth);
        kingThirteen.paymentMode = "Royal Treasury";
        System.out.println("Payment Mode: " + kingThirteen.paymentMode);
        System.out.println();

        King kingFourteen = new King();
        kingFourteen.kingId = 14;
        System.out.println("King ID: " + kingFourteen.kingId);
        kingFourteen.name = "Philip II";
        System.out.println("Name: " + kingFourteen.name);
        kingFourteen.kingdom = "Spain";
        System.out.println("Kingdom: " + kingFourteen.kingdom);
        kingFourteen.reignYears = 42;
        System.out.println("Reign Years: " + kingFourteen.reignYears);
        kingFourteen.capitalCity = "Madrid";
        System.out.println("Capital City: " + kingFourteen.capitalCity);
        kingFourteen.religion = "Catholicism";
        System.out.println("Religion: " + kingFourteen.religion);
        kingFourteen.wealth = 2700000.00;
        System.out.println("Wealth: $" + kingFourteen.wealth);
        kingFourteen.paymentMode = "Royal Treasury";
        System.out.println("Payment Mode: " + kingFourteen.paymentMode);
        System.out.println();

        King kingFifteen = new King();
        kingFifteen.kingId = 15;
        System.out.println("King ID: " + kingFifteen.kingId);
        kingFifteen.name = "Genghis Khan";
        System.out.println("Name: " + kingFifteen.name);
        kingFifteen.kingdom = "Mongol Empire";
        System.out.println("Kingdom: " + kingFifteen.kingdom);
        kingFifteen.reignYears = 21;
        System.out.println("Reign Years: " + kingFifteen.reignYears);
        kingFifteen.capitalCity = "Karakorum";
        System.out.println("Capital City: " + kingFifteen.capitalCity);
        kingFifteen.religion = "Tengrism";
        System.out.println("Religion: " + kingFifteen.religion);
        kingFifteen.wealth = 3500000.00;
        System.out.println("Wealth: $" + kingFifteen.wealth);
        kingFifteen.paymentMode = "Royal Treasury";
        System.out.println("Payment Mode: " + kingFifteen.paymentMode);
        System.out.println();

        System.out.println("Main Ended");
    }
}