class MarbleRunner {
    public static void main(String[] args) {
        System.out.println("Main Started");

        Marble marbleOne = new Marble();
        marbleOne.marbleId = 1;
        System.out.println("Marble ID: " + marbleOne.marbleId);
        marbleOne.color = "White";
        System.out.println("Color: " + marbleOne.color);
        marbleOne.material = "Carrara";
        System.out.println("Material: " + marbleOne.material);
        marbleOne.diameter = 2.5;
        System.out.println("Diameter: " + marbleOne.diameter);
        marbleOne.weight = 0.3;
        System.out.println("Weight: " + marbleOne.weight);
        marbleOne.finishType = "Polished";
        System.out.println("Finish Type: " + marbleOne.finishType);
        marbleOne.origin = "Italy";
        System.out.println("Origin: " + marbleOne.origin);
        System.out.println();

        Marble marbleTwo = new Marble();
        marbleTwo.marbleId = 2;
        System.out.println("Marble ID: " + marbleTwo.marbleId);
        marbleTwo.color = "Black";
        System.out.println("Color: " + marbleTwo.color);
        marbleTwo.material = "Nero Marquina";
        System.out.println("Material: " + marbleTwo.material);
        marbleTwo.diameter = 2.0;
        System.out.println("Diameter: " + marbleTwo.diameter);
        marbleTwo.weight = 0.25;
        System.out.println("Weight: " + marbleTwo.weight);
        marbleTwo.finishType = "Glossy";
        System.out.println("Finish Type: " + marbleTwo.finishType);
        marbleTwo.origin = "Spain";
        System.out.println("Origin: " + marbleTwo.origin);
        System.out.println();

        Marble marbleThree = new Marble();
        marbleThree.marbleId = 3;
        System.out.println("Marble ID: " + marbleThree.marbleId);
        marbleThree.color = "Green";
        System.out.println("Color: " + marbleThree.color);
        marbleThree.material = "Verde Alpi";
        System.out.println("Material: " + marbleThree.material);
        marbleThree.diameter = 3.0;
        System.out.println("Diameter: " + marbleThree.diameter);
        marbleThree.weight = 0.4;
        System.out.println("Weight: " + marbleThree.weight);
        marbleThree.finishType = "Matte";
        System.out.println("Finish Type: " + marbleThree.finishType);
        marbleThree.origin = "India";
        System.out.println("Origin: " + marbleThree.origin);
        System.out.println();

        Marble marbleFour = new Marble();
        marbleFour.marbleId = 4;
        System.out.println("Marble ID: " + marbleFour.marbleId);
        marbleFour.color = "Pink";
        System.out.println("Color: " + marbleFour.color);
        marbleFour.material = "Rosa Portugal";
        System.out.println("Material: " + marbleFour.material);
        marbleFour.diameter = 2.7;
        System.out.println("Diameter: " + marbleFour.diameter);
        marbleFour.weight = 0.35;
        System.out.println("Weight: " + marbleFour.weight);
        marbleFour.finishType = "Textured";
        System.out.println("Finish Type: " + marbleFour.finishType);
        marbleFour.origin = "Portugal";
        System.out.println("Origin: " + marbleFour.origin);
        System.out.println();

        Marble marbleFive = new Marble();
        marbleFive.marbleId = 5;
        System.out.println("Marble ID: " + marbleFive.marbleId);
        marbleFive.color = "Blue";
        System.out.println("Color: " + marbleFive.color);
        marbleFive.material = "Azul Macaubas";
        System.out.println("Material: " + marbleFive.material);
        marbleFive.diameter = 2.3;
        System.out.println("Diameter: " + marbleFive.diameter);
        marbleFive.weight = 0.28;
        System.out.println("Weight: " + marbleFive.weight);
        marbleFive.finishType = "Polished";
        System.out.println("Finish Type: " + marbleFive.finishType);
        marbleFive.origin = "Brazil";
        System.out.println("Origin: " + marbleFive.origin);
        System.out.println();

        Marble marbleSix = new Marble();
        marbleSix.marbleId = 6;
        System.out.println("Marble ID: " + marbleSix.marbleId);
        marbleSix.color = "Grey";
        System.out.println("Color: " + marbleSix.color);
        marbleSix.material = "Pietra Grey";
        System.out.println("Material: " + marbleSix.material);
        marbleSix.diameter = 2.8;
        System.out.println("Diameter: " + marbleSix.diameter);
        marbleSix.weight = 0.32;
        System.out.println("Weight: " + marbleSix.weight);
        marbleSix.finishType = "Matte";
        System.out.println("Finish Type: " + marbleSix.finishType);
        marbleSix.origin = "Iran";
        System.out.println("Origin: " + marbleSix.origin);
        System.out.println();

        Marble marbleSeven = new Marble();
        marbleSeven.marbleId = 7;
        System.out.println("Marble ID: " + marbleSeven.marbleId);
        marbleSeven.color = "Brown";
        System.out.println("Color: " + marbleSeven.color);
        marbleSeven.material = "Emperador";
        System.out.println("Material: " + marbleSeven.material);
        marbleSeven.diameter = 3.1;
        System.out.println("Diameter: " + marbleSeven.diameter);
        marbleSeven.weight = 0.45;
        System.out.println("Weight: " + marbleSeven.weight);
        marbleSeven.finishType = "Glossy";
        System.out.println("Finish Type: " + marbleSeven.finishType);
        marbleSeven.origin = "Turkey";
        System.out.println("Origin: " + marbleSeven.origin);
        System.out.println();

        Marble marbleEight = new Marble();
        marbleEight.marbleId = 8;
        System.out.println("Marble ID: " + marbleEight.marbleId);
        marbleEight.color = "Red";
        System.out.println("Color: " + marbleEight.color);
        marbleEight.material = "Rosso Levanto";
        System.out.println("Material: " + marbleEight.material);
        marbleEight.diameter = 2.9;
        System.out.println("Diameter: " + marbleEight.diameter);
        marbleEight.weight = 0.38;
        System.out.println("Weight: " + marbleEight.weight);
        marbleEight.finishType = "Polished";
        System.out.println("Finish Type: " + marbleEight.finishType);
        marbleEight.origin = "Italy";
        System.out.println("Origin: " + marbleEight.origin);
        System.out.println();

        Marble marbleNine = new Marble();
        marbleNine.marbleId = 9;
        System.out.println("Marble ID: " + marbleNine.marbleId);
        marbleNine.color = "Beige";
        System.out.println("Color: " + marbleNine.color);
        marbleNine.material = "Crema Marfil";
        System.out.println("Material: " + marbleNine.material);
        marbleNine.diameter = 2.4;
        System.out.println("Diameter: " + marbleNine.diameter);
        marbleNine.weight = 0.29;
        System.out.println("Weight: " + marbleNine.weight);
        marbleNine.finishType = "Glossy";
        System.out.println("Finish Type: " + marbleNine.finishType);
        marbleNine.origin = "Spain";
        System.out.println("Origin: " + marbleNine.origin);
        System.out.println();

        Marble marbleTen = new Marble();
        marbleTen.marbleId = 10;
        System.out.println("Marble ID: " + marbleTen.marbleId);
        marbleTen.color = "Purple";
        System.out.println("Color: " + marbleTen.color);
        marbleTen.material = "Purple Marble";
        System.out.println("Material: " + marbleTen.material);
        marbleTen.diameter = 2.6;
        System.out.println("Diameter: " + marbleTen.diameter);
        marbleTen.weight = 0.33;
        System.out.println("Weight: " + marbleTen.weight);
        marbleTen.finishType = "Textured";
        System.out.println("Finish Type: " + marbleTen.finishType);
        marbleTen.origin = "Egypt";
        System.out.println("Origin: " + marbleTen.origin);
        System.out.println();

        System.out.println("Main Ended");
    }
}