class NetworkRunner {
    public static void main(String[] args) {
        System.out.println("Main Started");

        Network networkOne = new Network();
        networkOne.networkId = 1;
        System.out.println("Network ID: " + networkOne.networkId);
        networkOne.networkName = "AlphaNet";
        System.out.println("Network Name: " + networkOne.networkName);
        networkOne.networkType = "LAN";
        System.out.println("Network Type: " + networkOne.networkType);
        networkOne.numberOfNodes = 50;
        System.out.println("Number of Nodes: " + networkOne.numberOfNodes);
        networkOne.protocol = "Ethernet";
        System.out.println("Protocol: " + networkOne.protocol);
        networkOne.paymentMode = "Online";
        System.out.println("Payment Mode: " + networkOne.paymentMode);
        System.out.println();

        Network networkTwo = new Network();
        networkTwo.networkId = 2;
        System.out.println("Network ID: " + networkTwo.networkId);
        networkTwo.networkName = "BetaNet";
        System.out.println("Network Name: " + networkTwo.networkName);
        networkTwo.networkType = "WAN";
        System.out.println("Network Type: " + networkTwo.networkType);
        networkTwo.numberOfNodes = 200;
        System.out.println("Number of Nodes: " + networkTwo.numberOfNodes);
        networkTwo.protocol = "TCP/IP";
        System.out.println("Protocol: " + networkTwo.protocol);
        networkTwo.paymentMode = "Cash";
        System.out.println("Payment Mode: " + networkTwo.paymentMode);
        System.out.println();

        Network networkThree = new Network();
        networkThree.networkId = 3;
        System.out.println("Network ID: " + networkThree.networkId);
        networkThree.networkName = "GammaNet";
        System.out.println("Network Name: " + networkThree.networkName);
        networkThree.networkType = "MAN";
        System.out.println("Network Type: " + networkThree.networkType);
        networkThree.numberOfNodes = 100;
        System.out.println("Number of Nodes: " + networkThree.numberOfNodes);
        networkThree.protocol = "MPLS";
        System.out.println("Protocol: " + networkThree.protocol);
        networkThree.paymentMode = "Card";
        System.out.println("Payment Mode: " + networkThree.paymentMode);
        System.out.println();

        Network networkFour = new Network();
        networkFour.networkId = 4;
        System.out.println("Network ID: " + networkFour.networkId);
        networkFour.networkName = "DeltaNet";
        System.out.println("Network Name: " + networkFour.networkName);
        networkFour.networkType = "PAN";
        System.out.println("Network Type: " + networkFour.networkType);
        networkFour.numberOfNodes = 20;
        System.out.println("Number of Nodes: " + networkFour.numberOfNodes);
        networkFour.protocol = "Bluetooth";
        System.out.println("Protocol: " + networkFour.protocol);
        networkFour.paymentMode = "Online";
        System.out.println("Payment Mode: " + networkFour.paymentMode);
        System.out.println();

        Network networkFive = new Network();
        networkFive.networkId = 5;
        System.out.println("Network ID: " + networkFive.networkId);
        networkFive.networkName = "EpsilonNet";
        System.out.println("Network Name: " + networkFive.networkName);
        networkFive.networkType = "VPN";
        System.out.println("Network Type: " + networkFive.networkType);
        networkFive.numberOfNodes = 150;
        System.out.println("Number of Nodes: " + networkFive.numberOfNodes);
        networkFive.protocol = "IPSec";
        System.out.println("Protocol: " + networkFive.protocol);
        networkFive.paymentMode = "Cash";
        System.out.println("Payment Mode: " + networkFive.paymentMode);
        System.out.println();

        Network networkSix = new Network();
        networkSix.networkId = 6;
        System.out.println("Network ID: " + networkSix.networkId);
        networkSix.networkName = "ZetaNet";
        System.out.println("Network Name: " + networkSix.networkName);
        networkSix.networkType = "LAN";
        System.out.println("Network Type: " + networkSix.networkType);
        networkSix.numberOfNodes = 75;
        System.out.println("Number of Nodes: " + networkSix.numberOfNodes);
        networkSix.protocol = "Wi-Fi";
        System.out.println("Protocol: " + networkSix.protocol);
        networkSix.paymentMode = "Card";
        System.out.println("Payment Mode: " + networkSix.paymentMode);
        System.out.println();

        Network networkSeven = new Network();
        networkSeven.networkId = 7;
        System.out.println("Network ID: " + networkSeven.networkId);
        networkSeven.networkName = "EtaNet";
        System.out.println("Network Name: " + networkSeven.networkName);
        networkSeven.networkType = "WAN";
        System.out.println("Network Type: " + networkSeven.networkType);
        networkSeven.numberOfNodes = 300;
        System.out.println("Number of Nodes: " + networkSeven.numberOfNodes);
        networkSeven.protocol = "Frame Relay";
        System.out.println("Protocol: " + networkSeven.protocol);
        networkSeven.paymentMode = "Online";
        System.out.println("Payment Mode: " + networkSeven.paymentMode);
        System.out.println();

        Network networkEight = new Network();
        networkEight.networkId = 8;
        System.out.println("Network ID: " + networkEight.networkId);
        networkEight.networkName = "ThetaNet";
        System.out.println("Network Name: " + networkEight.networkName);
        networkEight.networkType = "MAN";
        System.out.println("Network Type: " + networkEight.networkType);
        networkEight.numberOfNodes = 120;
        System.out.println("Number of Nodes: " + networkEight.numberOfNodes);
        networkEight.protocol = "ATM";
        System.out.println("Protocol: " + networkEight.protocol);
        networkEight.paymentMode = "Cash";
        System.out.println("Payment Mode: " + networkEight.paymentMode);
        System.out.println();

        Network networkNine = new Network();
        networkNine.networkId = 9;
        System.out.println("Network ID: " + networkNine.networkId);
        networkNine.networkName = "IotaNet";
        System.out.println("Network Name: " + networkNine.networkName);
        networkNine.networkType = "PAN";
        System.out.println("Network Type: " + networkNine.networkType);
        networkNine.numberOfNodes = 30;
        System.out.println("Number of Nodes: " + networkNine.numberOfNodes);
        networkNine.protocol = "ZigBee";
        System.out.println("Protocol: " + networkNine.protocol);
        networkNine.paymentMode = "Card";
        System.out.println("Payment Mode: " + networkNine.paymentMode);
        System.out.println();

        Network networkTen = new Network();
        networkTen.networkId = 10;
        System.out.println("Network ID: " + networkTen.networkId);
        networkTen.networkName = "KappaNet";
        System.out.println("Network Name: " + networkTen.networkName);
        networkTen.networkType = "VPN";
        System.out.println("Network Type: " + networkTen.networkType);
        networkTen.numberOfNodes = 180;
        System.out.println("Number of Nodes: " + networkTen.numberOfNodes);
        networkTen.protocol = "SSL";
        System.out.println("Protocol: " + networkTen.protocol);
        networkTen.paymentMode = "Online";
        System.out.println("Payment Mode: " + networkTen.paymentMode);
        System.out.println();

        Network networkEleven = new Network();
        networkEleven.networkId = 11;
        System.out.println("Network ID: " + networkEleven.networkId);
        networkEleven.networkName = "LambdaNet";
        System.out.println("Network Name: " + networkEleven.networkName);
        networkEleven.networkType = "LAN";
        System.out.println("Network Type: " + networkEleven.networkType);
        networkEleven.numberOfNodes = 60;
        System.out.println("Number of Nodes: " + networkEleven.numberOfNodes);
        networkEleven.protocol = "Ethernet";
        System.out.println("Protocol: " + networkEleven.protocol);
        networkEleven.paymentMode = "Cash";
        System.out.println("Payment Mode: " + networkEleven.paymentMode);
        System.out.println();

        Network networkTwelve = new Network();
        networkTwelve.networkId = 12;
        System.out.println("Network ID: " + networkTwelve.networkId);
        networkTwelve.networkName = "MuNet";
        System.out.println("Network Name: " + networkTwelve.networkName);
        networkTwelve.networkType = "WAN";
        System.out.println("Network Type: " + networkTwelve.networkType);
        networkTwelve.numberOfNodes = 250;
        System.out.println("Number of Nodes: " + networkTwelve.numberOfNodes);
        networkTwelve.protocol = "TCP/IP";
        System.out.println("Protocol: " + networkTwelve.protocol);
        networkTwelve.paymentMode = "Card";
        System.out.println("Payment Mode: " + networkTwelve.paymentMode);
        System.out.println();

        Network networkThirteen = new Network();
        networkThirteen.networkId = 13;
        System.out.println("Network ID: " + networkThirteen.networkId);
        networkThirteen.networkName = "NuNet";
        System.out.println("Network Name: " + networkThirteen.networkName);
        networkThirteen.networkType = "MAN";
        System.out.println("Network Type: " + networkThirteen.networkType);
        networkThirteen.numberOfNodes = 110;
        System.out.println("Number of Nodes: " + networkThirteen.numberOfNodes);
        networkThirteen.protocol = "MPLS";
        System.out.println("Protocol: " + networkThirteen.protocol);
        networkThirteen.paymentMode = "Online";
        System.out.println("Payment Mode: " + networkThirteen.paymentMode);
        System.out.println();

        Network networkFourteen = new Network();
        networkFourteen.networkId = 14;
        System.out.println("Network ID: " + networkFourteen.networkId);
        networkFourteen.networkName = "XiNet";
        System.out.println("Network Name: " + networkFourteen.networkName);
        networkFourteen.networkType = "PAN";
        System.out.println("Network Type: " + networkFourteen.networkType);
        networkFourteen.numberOfNodes = 25;
        System.out.println("Number of Nodes: " + networkFourteen.numberOfNodes);
        networkFourteen.protocol = "Bluetooth";
        System.out.println("Protocol: " + networkFourteen.protocol);
        networkFourteen.paymentMode = "Cash";
        System.out.println("Payment Mode: " + networkFourteen.paymentMode);
        System.out.println();

        Network networkFifteen = new Network();
        networkFifteen.networkId = 15;
        System.out.println("Network ID: " + networkFifteen.networkId);
        networkFifteen.networkName = "OmicronNet";
        System.out.println("Network Name: " + networkFifteen.networkName);
        networkFifteen.networkType = "VPN";
        System.out.println("Network Type: " + networkFifteen.networkType);
        networkFifteen.numberOfNodes = 160;
        System.out.println("Number of Nodes: " + networkFifteen.numberOfNodes);
        networkFifteen.protocol = "IPSec";
        System.out.println("Protocol: " + networkFifteen.protocol);
        networkFifteen.paymentMode = "Card";
        System.out.println("Payment Mode: " + networkFifteen.paymentMode);

        System.out.println("Main Ended");
    }
}