class PipeRunner {
    public static void main(String[] args) {
        System.out.println("Main Started");

        Pipe pipeOne = new Pipe();
        pipeOne.pipeId = 1;
        System.out.println("Pipe ID: " + pipeOne.pipeId);
        pipeOne.pipeMaterial = "PVC";
        System.out.println("Pipe Material: " + pipeOne.pipeMaterial);
        pipeOne.pipeLengthMeters = 5.0;
        System.out.println("Pipe Length (meters): " + pipeOne.pipeLengthMeters);
        pipeOne.pipeDiameterInches = 2.0;
        System.out.println("Pipe Diameter (inches): " + pipeOne.pipeDiameterInches);
        pipeOne.pipeType = "Water";
        System.out.println("Pipe Type: " + pipeOne.pipeType);
        pipeOne.paymentMode = "Online";
        System.out.println("Payment Mode: " + pipeOne.paymentMode);
        System.out.println();

        Pipe pipeTwo = new Pipe();
        pipeTwo.pipeId = 2;
        System.out.println("Pipe ID: " + pipeTwo.pipeId);
        pipeTwo.pipeMaterial = "Steel";
        System.out.println("Pipe Material: " + pipeTwo.pipeMaterial);
        pipeTwo.pipeLengthMeters = 10.0;
        System.out.println("Pipe Length (meters): " + pipeTwo.pipeLengthMeters);
        pipeTwo.pipeDiameterInches = 4.0;
        System.out.println("Pipe Diameter (inches): " + pipeTwo.pipeDiameterInches);
        pipeTwo.pipeType = "Gas";
        System.out.println("Pipe Type: " + pipeTwo.pipeType);
        pipeTwo.paymentMode = "Cash";
        System.out.println("Payment Mode: " + pipeTwo.paymentMode);
        System.out.println();

        Pipe pipeThree = new Pipe();
        pipeThree.pipeId = 3;
        System.out.println("Pipe ID: " + pipeThree.pipeId);
        pipeThree.pipeMaterial = "Copper";
        System.out.println("Pipe Material: " + pipeThree.pipeMaterial);
        pipeThree.pipeLengthMeters = 8.5;
        System.out.println("Pipe Length (meters): " + pipeThree.pipeLengthMeters);
        pipeThree.pipeDiameterInches = 1.5;
        System.out.println("Pipe Diameter (inches): " + pipeThree.pipeDiameterInches);
        pipeThree.pipeType = "Heating";
        System.out.println("Pipe Type: " + pipeThree.pipeType);
        pipeThree.paymentMode = "Card";
        System.out.println("Payment Mode: " + pipeThree.paymentMode);
        System.out.println();

        Pipe pipeFour = new Pipe();
        pipeFour.pipeId = 4;
        System.out.println("Pipe ID: " + pipeFour.pipeId);
        pipeFour.pipeMaterial = "PVC";
        System.out.println("Pipe Material: " + pipeFour.pipeMaterial);
        pipeFour.pipeLengthMeters = 12.0;
        System.out.println("Pipe Length (meters): " + pipeFour.pipeLengthMeters);
        pipeFour.pipeDiameterInches = 3.0;
        System.out.println("Pipe Diameter (inches): " + pipeFour.pipeDiameterInches);
        pipeFour.pipeType = "Drainage";
        System.out.println("Pipe Type: " + pipeFour.pipeType);
        pipeFour.paymentMode = "Online";
        System.out.println("Payment Mode: " + pipeFour.paymentMode);
        System.out.println();

        Pipe pipeFive = new Pipe();
        pipeFive.pipeId = 5;
        System.out.println("Pipe ID: " + pipeFive.pipeId);
        pipeFive.pipeMaterial = "Galvanized Steel";
        System.out.println("Pipe Material: " + pipeFive.pipeMaterial);
        pipeFive.pipeLengthMeters = 15.0;
        System.out.println("Pipe Length (meters): " + pipeFive.pipeLengthMeters);
        pipeFive.pipeDiameterInches = 6.0;
        System.out.println("Pipe Diameter (inches): " + pipeFive.pipeDiameterInches);
        pipeFive.pipeType = "Water";
        System.out.println("Pipe Type: " + pipeFive.pipeType);
        pipeFive.paymentMode = "Cash";
        System.out.println("Payment Mode: " + pipeFive.paymentMode);
        System.out.println();

        Pipe pipeSix = new Pipe();
        pipeSix.pipeId = 6;
        System.out.println("Pipe ID: " + pipeSix.pipeId);
        pipeSix.pipeMaterial = "HDPE";
        System.out.println("Pipe Material: " + pipeSix.pipeMaterial);
        pipeSix.pipeLengthMeters = 7.5;
        System.out.println("Pipe Length (meters): " + pipeSix.pipeLengthMeters);
        pipeSix.pipeDiameterInches = 2.5;
        System.out.println("Pipe Diameter (inches): " + pipeSix.pipeDiameterInches);
        pipeSix.pipeType = "Irrigation";
        System.out.println("Pipe Type: " + pipeSix.pipeType);
        pipeSix.paymentMode = "Card";
        System.out.println("Payment Mode: " + pipeSix.paymentMode);
        System.out.println();

        Pipe pipeSeven = new Pipe();
        pipeSeven.pipeId = 7;
        System.out.println("Pipe ID: " + pipeSeven.pipeId);
        pipeSeven.pipeMaterial = "Cast Iron";
        System.out.println("Pipe Material: " + pipeSeven.pipeMaterial);
        pipeSeven.pipeLengthMeters = 9.0;
        System.out.println("Pipe Length (meters): " + pipeSeven.pipeLengthMeters);
        pipeSeven.pipeDiameterInches = 5.0;
        System.out.println("Pipe Diameter (inches): " + pipeSeven.pipeDiameterInches);
        pipeSeven.pipeType = "Sewer";
        System.out.println("Pipe Type: " + pipeSeven.pipeType);
        pipeSeven.paymentMode = "Online";
        System.out.println("Payment Mode: " + pipeSeven.paymentMode);
        System.out.println();

        Pipe pipeEight = new Pipe();
        pipeEight.pipeId = 8;
        System.out.println("Pipe ID: " + pipeEight.pipeId);
        pipeEight.pipeMaterial = "Aluminum";
        System.out.println("Pipe Material: " + pipeEight.pipeMaterial);
        pipeEight.pipeLengthMeters = 6.0;
        System.out.println("Pipe Length (meters): " + pipeEight.pipeLengthMeters);
        pipeEight.pipeDiameterInches = 2.0;
        System.out.println("Pipe Diameter (inches): " + pipeEight.pipeDiameterInches);
        pipeEight.pipeType = "Gas";
        System.out.println("Pipe Type: " + pipeEight.pipeType);
        pipeEight.paymentMode = "Cash";
        System.out.println("Payment Mode: " + pipeEight.paymentMode);
        System.out.println();

        Pipe pipeNine = new Pipe();
        pipeNine.pipeId = 9;
        System.out.println("Pipe ID: " + pipeNine.pipeId);
        pipeNine.pipeMaterial = "Steel";
        System.out.println("Pipe Material: " + pipeNine.pipeMaterial);
        pipeNine.pipeLengthMeters = 20.0;
        System.out.println("Pipe Length (meters): " + pipeNine.pipeLengthMeters);
        pipeNine.pipeDiameterInches = 8.0;
        System.out.println("Pipe Diameter (inches): " + pipeNine.pipeDiameterInches);
        pipeNine.pipeType = "Oil";
        System.out.println("Pipe Type: " + pipeNine.pipeType);
        pipeNine.paymentMode = "Card";
        System.out.println("Payment Mode: " + pipeNine.paymentMode);
        System.out.println();

        Pipe pipeTen = new Pipe();
        pipeTen.pipeId = 10;
        System.out.println("Pipe ID: " + pipeTen.pipeId);
        pipeTen.pipeMaterial = "PVC";
        System.out.println("Pipe Material: " + pipeTen.pipeMaterial);
        pipeTen.pipeLengthMeters = 25.0;
        System.out.println("Pipe Length (meters): " + pipeTen.pipeLengthMeters);
        pipeTen.pipeDiameterInches = 3.5;
        System.out.println("Pipe Diameter (inches): " + pipeTen.pipeDiameterInches);
        pipeTen.pipeType = "Water";
        System.out.println("Pipe Type: " + pipeTen.pipeType);
        pipeTen.paymentMode = "Online";
        System.out.println("Payment Mode: " + pipeTen.paymentMode);
        System.out.println();

        Pipe pipeEleven = new Pipe();
        pipeEleven.pipeId = 11;
        System.out.println("Pipe ID: " + pipeEleven.pipeId);
        pipeEleven.pipeMaterial = "Copper";
        System.out.println("Pipe Material: " + pipeEleven.pipeMaterial);
        pipeEleven.pipeLengthMeters = 3.5;
        System.out.println("Pipe Length (meters): " + pipeEleven.pipeLengthMeters);
        pipeEleven.pipeDiameterInches = 1.0;
        System.out.println("Pipe Diameter (inches): " + pipeEleven.pipeDiameterInches);
        pipeEleven.pipeType = "Heating";
        System.out.println("Pipe Type: " + pipeEleven.pipeType);
        pipeEleven.paymentMode = "Cash";
        System.out.println("Payment Mode: " + pipeEleven.paymentMode);
        System.out.println();

        Pipe pipeTwelve = new Pipe();
        pipeTwelve.pipeId = 12;
        System.out.println("Pipe ID: " + pipeTwelve.pipeId);
        pipeTwelve.pipeMaterial = "HDPE";
        System.out.println("Pipe Material: " + pipeTwelve.pipeMaterial);
        pipeTwelve.pipeLengthMeters = 13.0;
        System.out.println("Pipe Length (meters): " + pipeTwelve.pipeLengthMeters);
        pipeTwelve.pipeDiameterInches = 4.0;
        System.out.println("Pipe Diameter (inches): " + pipeTwelve.pipeDiameterInches);
        pipeTwelve.pipeType = "Irrigation";
        System.out.println("Pipe Type: " + pipeTwelve.pipeType);
        pipeTwelve.paymentMode = "Online";
        System.out.println("Payment Mode: " + pipeTwelve.paymentMode);
        System.out.println();

        Pipe pipeThirteen = new Pipe();
        pipeThirteen.pipeId = 13;
        System.out.println("Pipe ID: " + pipeThirteen.pipeId);
        pipeThirteen.pipeMaterial = "Cast Iron";
        System.out.println("Pipe Material: " + pipeThirteen.pipeMaterial);
        pipeThirteen.pipeLengthMeters = 11.0;
        System.out.println("Pipe Length (meters): " + pipeThirteen.pipeLengthMeters);
        pipeThirteen.pipeDiameterInches = 5.5;
        System.out.println("Pipe Diameter (inches): " + pipeThirteen.pipeDiameterInches);
        pipeThirteen.pipeType = "Sewer";
        System.out.println("Pipe Type: " + pipeThirteen.pipeType);
        pipeThirteen.paymentMode = "Card";
        System.out.println("Payment Mode: " + pipeThirteen.paymentMode);
        System.out.println();

        Pipe pipeFourteen = new Pipe();
        pipeFourteen.pipeId = 14;
        System.out.println("Pipe ID: " + pipeFourteen.pipeId);
        pipeFourteen.pipeMaterial = "Aluminum";
        System.out.println("Pipe Material: " + pipeFourteen.pipeMaterial);
        pipeFourteen.pipeLengthMeters = 4.5;
        System.out.println("Pipe Length (meters): " + pipeFourteen.pipeLengthMeters);
        pipeFourteen.pipeDiameterInches = 1.8;
        System.out.println("Pipe Diameter (inches): " + pipeFourteen.pipeDiameterInches);
        pipeFourteen.pipeType = "Gas";
        System.out.println("Pipe Type: " + pipeFourteen.pipeType);
        pipeFourteen.paymentMode = "Cash";
        System.out.println("Payment Mode: " + pipeFourteen.paymentMode);
        System.out.println();

        Pipe pipeFifteen = new Pipe();
        pipeFifteen.pipeId = 15;
        System.out.println("Pipe ID: " + pipeFifteen.pipeId);
        pipeFifteen.pipeMaterial = "Galvanized Steel";
        System.out.println("Pipe Material: " + pipeFifteen.pipeMaterial);
        pipeFifteen.pipeLengthMeters = 18.0;
        System.out.println("Pipe Length (meters): " + pipeFifteen.pipeLengthMeters);
        pipeFifteen.pipeDiameterInches = 7.0;
        System.out.println("Pipe Diameter (inches): " + pipeFifteen.pipeDiameterInches);
        pipeFifteen.pipeType = "Water";
        System.out.println("Pipe Type: " + pipeFifteen.pipeType);
        pipeFifteen.paymentMode = "Online";
        System.out.println("Payment Mode: " + pipeFifteen.paymentMode);

        System.out.println("Main Ended");
    }
}