class PoliticianRunner {
    public static void main(String[] args) {
        System.out.println("Main Started");

        Politician p1 = new Politician();
        p1.politicianId = 1;
        System.out.println("Politician ID: " + p1.politicianId);
        p1.name = "John Smith";
        System.out.println("Name: " + p1.name);
        p1.party = "Democratic";
        System.out.println("Party: " + p1.party);
        p1.constituency = "California";
        System.out.println("Constituency: " + p1.constituency);
        p1.age = 52;
        System.out.println("Age: " + p1.age);
        p1.yearsInOffice = 10;
        System.out.println("Years in Office: " + p1.yearsInOffice);
        p1.paymentMode = "Online";
        System.out.println("Payment Mode: " + p1.paymentMode);
        System.out.println();

        Politician p2 = new Politician();
        p2.politicianId = 2;
        System.out.println("Politician ID: " + p2.politicianId);
        p2.name = "Linda Brown";
        System.out.println("Name: " + p2.name);
        p2.party = "Republican";
        System.out.println("Party: " + p2.party);
        p2.constituency = "Texas";
        System.out.println("Constituency: " + p2.constituency);
        p2.age = 60;
        System.out.println("Age: " + p2.age);
        p2.yearsInOffice = 15;
        System.out.println("Years in Office: " + p2.yearsInOffice);
        p2.paymentMode = "Cash";
        System.out.println("Payment Mode: " + p2.paymentMode);
        System.out.println();

        Politician p3 = new Politician();
        p3.politicianId = 3;
        System.out.println("Politician ID: " + p3.politicianId);
        p3.name = "Raj Patel";
        System.out.println("Name: " + p3.name);
        p3.party = "Independent";
        System.out.println("Party: " + p3.party);
        p3.constituency = "New York";
        System.out.println("Constituency: " + p3.constituency);
        p3.age = 45;
        System.out.println("Age: " + p3.age);
        p3.yearsInOffice = 8;
        System.out.println("Years in Office: " + p3.yearsInOffice);
        p3.paymentMode = "Card";
        System.out.println("Payment Mode: " + p3.paymentMode);
        System.out.println();

        Politician p4 = new Politician();
        p4.politicianId = 4;
        System.out.println("Politician ID: " + p4.politicianId);
        p4.name = "Emily Davis";
        System.out.println("Name: " + p4.name);
        p4.party = "Democratic";
        System.out.println("Party: " + p4.party);
        p4.constituency = "Florida";
        System.out.println("Constituency: " + p4.constituency);
        p4.age = 50;
        System.out.println("Age: " + p4.age);
        p4.yearsInOffice = 12;
        System.out.println("Years in Office: " + p4.yearsInOffice);
        p4.paymentMode = "Online";
        System.out.println("Payment Mode: " + p4.paymentMode);
        System.out.println();

        Politician p5 = new Politician();
        p5.politicianId = 5;
        System.out.println("Politician ID: " + p5.politicianId);
        p5.name = "Mohammed Ali";
        System.out.println("Name: " + p5.name);
        p5.party = "Republican";
        System.out.println("Party: " + p5.party);
        p5.constituency = "Illinois";
        System.out.println("Constituency: " + p5.constituency);
        p5.age = 58;
        System.out.println("Age: " + p5.age);
        p5.yearsInOffice = 20;
        System.out.println("Years in Office: " + p5.yearsInOffice);
        p5.paymentMode = "Cash";
        System.out.println("Payment Mode: " + p5.paymentMode);
        System.out.println();

        Politician p6 = new Politician();
        p6.politicianId = 6;
        System.out.println("Politician ID: " + p6.politicianId);
        p6.name = "Sarah Lee";
        System.out.println("Name: " + p6.name);
        p6.party = "Independent";
        System.out.println("Party: " + p6.party);
        p6.constituency = "Washington";
        System.out.println("Constituency: " + p6.constituency);
        p6.age = 48;
        System.out.println("Age: " + p6.age);
        p6.yearsInOffice = 5;
        System.out.println("Years in Office: " + p6.yearsInOffice);
        p6.paymentMode = "Card";
        System.out.println("Payment Mode: " + p6.paymentMode);
        System.out.println();

        Politician p7 = new Politician();
        p7.politicianId = 7;
        System.out.println("Politician ID: " + p7.politicianId);
        p7.name = "Carlos Gomez";
        System.out.println("Name: " + p7.name);
        p7.party = "Democratic";
        System.out.println("Party: " + p7.party);
        p7.constituency = "New Mexico";
        System.out.println("Constituency: " + p7.constituency);
        p7.age = 55;
        System.out.println("Age: " + p7.age);
        p7.yearsInOffice = 9;
        System.out.println("Years in Office: " + p7.yearsInOffice);
        p7.paymentMode = "Online";
        System.out.println("Payment Mode: " + p7.paymentMode);
        System.out.println();

        Politician p8 = new Politician();
        p8.politicianId = 8;
        System.out.println("Politician ID: " + p8.politicianId);
        p8.name = "Anna Kim";
        System.out.println("Name: " + p8.name);
        p8.party = "Republican";
        System.out.println("Party: " + p8.party);
        p8.constituency = "Oregon";
        System.out.println("Constituency: " + p8.constituency);
        p8.age = 53;
        System.out.println("Age: " + p8.age);
        p8.yearsInOffice = 11;
        System.out.println("Years in Office: " + p8.yearsInOffice);
        p8.paymentMode = "Cash";
        System.out.println("Payment Mode: " + p8.paymentMode);
        System.out.println();

        Politician p9 = new Politician();
        p9.politicianId = 9;
        System.out.println("Politician ID: " + p9.politicianId);
        p9.name = "David Johnson";
        System.out.println("Name: " + p9.name);
        p9.party = "Independent";
        System.out.println("Party: " + p9.party);
        p9.constituency = "Nevada";
        System.out.println("Constituency: " + p9.constituency);
        p9.age = 47;
        System.out.println("Age: " + p9.age);
        p9.yearsInOffice = 7;
        System.out.println("Years in Office: " + p9.yearsInOffice);
        p9.paymentMode = "Card";
        System.out.println("Payment Mode: " + p9.paymentMode);
        System.out.println();

        Politician p10 = new Politician();
        p10.politicianId = 10;
        System.out.println("Politician ID: " + p10.politicianId);
        p10.name = "Grace Wilson";
        System.out.println("Name: " + p10.name);
        p10.party = "Democratic";
        System.out.println("Party: " + p10.party);
        p10.constituency = "Colorado";
        System.out.println("Constituency: " + p10.constituency);
        p10.age = 49;
        System.out.println("Age: " + p10.age);
        p10.yearsInOffice = 13;
        System.out.println("Years in Office: " + p10.yearsInOffice);
        p10.paymentMode = "Online";
        System.out.println("Payment Mode: " + p10.paymentMode);
        System.out.println();

        Politician p11 = new Politician();
        p11.politicianId = 11;
        System.out.println("Politician ID: " + p11.politicianId);
        p11.name = "Henry Adams";
        System.out.println("Name: " + p11.name);
        p11.party = "Republican";
        System.out.println("Party: " + p11.party);
        p11.constituency = "Arizona";
        System.out.println("Constituency: " + p11.constituency);
        p11.age = 62;
        System.out.println("Age: " + p11.age);
        p11.yearsInOffice = 18;
        System.out.println("Years in Office: " + p11.yearsInOffice);
        p11.paymentMode = "Cash";
        System.out.println("Payment Mode: " + p11.paymentMode);
        System.out.println();

        Politician p12 = new Politician();
        p12.politicianId = 12;
        System.out.println("Politician ID: " + p12.politicianId);
        p12.name = "Irene Chen";
        System.out.println("Name: " + p12.name);
        p12.party = "Independent";
        System.out.println("Party: " + p12.party);
        p12.constituency = "Nevada";
        System.out.println("Constituency: " + p12.constituency);
        p12.age = 44;
        System.out.println("Age: " + p12.age);
        p12.yearsInOffice = 6;
        System.out.println("Years in Office: " + p12.yearsInOffice);
        p12.paymentMode = "Card";
        System.out.println("Payment Mode: " + p12.paymentMode);
        System.out.println();

        Politician p13 = new Politician();
        p13.politicianId = 13;
        System.out.println("Politician ID: " + p13.politicianId);
        p13.name = "Jack Turner";
        System.out.println("Name: " + p13.name);
        p13.party = "Democratic";
        System.out.println("Party: " + p13.party);
        p13.constituency = "Georgia";
        System.out.println("Constituency: " + p13.constituency);
        p13.age = 54;
        System.out.println("Age: " + p13.age);
        p13.yearsInOffice = 14;
        System.out.println("Years in Office: " + p13.yearsInOffice);
        p13.paymentMode = "Online";
        System.out.println("Payment Mode: " + p13.paymentMode);
        System.out.println();

        Politician p14 = new Politician();
        p14.politicianId = 14;
        System.out.println("Politician ID: " + p14.politicianId);
        p14.name = "Karen Scott";
        System.out.println("Name: " + p14.name);
        p14.party = "Republican";
        System.out.println("Party: " + p14.party);
        p14.constituency = "Alaska";
        System.out.println("Constituency: " + p14.constituency);
        p14.age = 59;
        System.out.println("Age: " + p14.age);
        p14.yearsInOffice = 17;
        System.out.println("Years in Office: " + p14.yearsInOffice);
        p14.paymentMode = "Cash";
        System.out.println("Payment Mode: " + p14.paymentMode);
        System.out.println();

        Politician p15 = new Politician();
        p15.politicianId = 15;
        System.out.println("Politician ID: " + p15.politicianId);
        p15.name = "Leo Martinez";
        System.out.println("Name: " + p15.name);
        p15.party = "Independent";
        System.out.println("Party: " + p15.party);
        p15.constituency = "Ohio";
        System.out.println("Constituency: " + p15.constituency);
        p15.age = 46;
        System.out.println("Age: " + p15.age);
        p15.yearsInOffice = 9;
        System.out.println("Years in Office: " + p15.yearsInOffice);
        p15.paymentMode = "Card";
        System.out.println("Payment Mode: " + p15.paymentMode);
        System.out.println();

        System.out.println("Main Ended");
    }
}