class WeaponRunner {
    public static void main(String[] args) {
        System.out.println("Main Started");

        Weapon weaponOne = new Weapon();
        weaponOne.weaponId = 1;
        System.out.println("Weapon ID: " + weaponOne.weaponId);
        weaponOne.weaponName = "Katana";
        System.out.println("Weapon Name: " + weaponOne.weaponName);
        weaponOne.weaponType = "Sword";
        System.out.println("Weapon Type: " + weaponOne.weaponType);
        weaponOne.weaponMaterial = "Steel";
        System.out.println("Weapon Material: " + weaponOne.weaponMaterial);
        weaponOne.weaponPrice = 5000.00;
        System.out.println("Weapon Price: ₹" + weaponOne.weaponPrice);
        weaponOne.paymentMode = "Online";
        System.out.println("Payment Mode: " + weaponOne.paymentMode);
        System.out.println("");

        Weapon weaponTwo = new Weapon();
        weaponTwo.weaponId = 2;
        System.out.println("Weapon ID: " + weaponTwo.weaponId);
        weaponTwo.weaponName = "Crossbow";
        System.out.println("Weapon Name: " + weaponTwo.weaponName);
        weaponTwo.weaponType = "Ranged";
        System.out.println("Weapon Type: " + weaponTwo.weaponType);
        weaponTwo.weaponMaterial = "Wood and Steel";
        System.out.println("Weapon Material: " + weaponTwo.weaponMaterial);
        weaponTwo.weaponPrice = 7000.00;
        System.out.println("Weapon Price: ₹" + weaponTwo.weaponPrice);
        weaponTwo.paymentMode = "Cash";
        System.out.println("Payment Mode: " + weaponTwo.paymentMode);
        System.out.println("");

        Weapon weaponThree = new Weapon();
        weaponThree.weaponId = 3;
        System.out.println("Weapon ID: " + weaponThree.weaponId);
        weaponThree.weaponName = "Dagger";
        System.out.println("Weapon Name: " + weaponThree.weaponName);
        weaponThree.weaponType = "Knife";
        System.out.println("Weapon Type: " + weaponThree.weaponType);
        weaponThree.weaponMaterial = "Carbon Steel";
        System.out.println("Weapon Material: " + weaponThree.weaponMaterial);
        weaponThree.weaponPrice = 2000.00;
        System.out.println("Weapon Price: ₹" + weaponThree.weaponPrice);
        weaponThree.paymentMode = "Card";
        System.out.println("Payment Mode: " + weaponThree.paymentMode);
        System.out.println("");

        Weapon weaponFour = new Weapon();
        weaponFour.weaponId = 4;
        System.out.println("Weapon ID: " + weaponFour.weaponId);
        weaponFour.weaponName = "Mace";
        System.out.println("Weapon Name: " + weaponFour.weaponName);
        weaponFour.weaponType = "Blunt";
        System.out.println("Weapon Type: " + weaponFour.weaponType);
        weaponFour.weaponMaterial = "Iron";
        System.out.println("Weapon Material: " + weaponFour.weaponMaterial);
        weaponFour.weaponPrice = 3500.00;
        System.out.println("Weapon Price: ₹" + weaponFour.weaponPrice);
        weaponFour.paymentMode = "Online";
        System.out.println("Payment Mode: " + weaponFour.paymentMode);
        System.out.println("");

        Weapon weaponFive = new Weapon();
        weaponFive.weaponId = 5;
        System.out.println("Weapon ID: " + weaponFive.weaponId);
        weaponFive.weaponName = "Bow";
        System.out.println("Weapon Name: " + weaponFive.weaponName);
        weaponFive.weaponType = "Ranged";
        System.out.println("Weapon Type: " + weaponFive.weaponType);
        weaponFive.weaponMaterial = "Wood";
        System.out.println("Weapon Material: " + weaponFive.weaponMaterial);
        weaponFive.weaponPrice = 4500.00;
        System.out.println("Weapon Price: ₹" + weaponFive.weaponPrice);
        weaponFive.paymentMode = "Cash";
        System.out.println("Payment Mode: " + weaponFive.paymentMode);
        System.out.println("");

        Weapon weaponSix = new Weapon();
        weaponSix.weaponId = 6;
        System.out.println("Weapon ID: " + weaponSix.weaponId);
        weaponSix.weaponName = "Spear";
        System.out.println("Weapon Name: " + weaponSix.weaponName);
        weaponSix.weaponType = "Polearm";
        System.out.println("Weapon Type: " + weaponSix.weaponType);
        weaponSix.weaponMaterial = "Steel and Wood";
        System.out.println("Weapon Material: " + weaponSix.weaponMaterial);
        weaponSix.weaponPrice = 4000.00;
        System.out.println("Weapon Price: ₹" + weaponSix.weaponPrice);
        weaponSix.paymentMode = "Card";
        System.out.println("Payment Mode: " + weaponSix.paymentMode);
        System.out.println("");

        Weapon weaponSeven = new Weapon();
        weaponSeven.weaponId = 7;
        System.out.println("Weapon ID: " + weaponSeven.weaponId);
        weaponSeven.weaponName = "Axe";
        System.out.println("Weapon Name: " + weaponSeven.weaponName);
        weaponSeven.weaponType = "Bladed";
        System.out.println("Weapon Type: " + weaponSeven.weaponType);
        weaponSeven.weaponMaterial = "Steel";
        System.out.println("Weapon Material: " + weaponSeven.weaponMaterial);
        weaponSeven.weaponPrice = 3000.00;
        System.out.println("Weapon Price: ₹" + weaponSeven.weaponPrice);
        weaponSeven.paymentMode = "Online";
        System.out.println("Payment Mode: " + weaponSeven.paymentMode);
        System.out.println("");

        Weapon weaponEight = new Weapon();
        weaponEight.weaponId = 8;
        System.out.println("Weapon ID: " + weaponEight.weaponId);
        weaponEight.weaponName = "Halberd";
        System.out.println("Weapon Name: " + weaponEight.weaponName);
        weaponEight.weaponType = "Polearm";
        System.out.println("Weapon Type: " + weaponEight.weaponType);
        weaponEight.weaponMaterial = "Steel";
        System.out.println("Weapon Material: " + weaponEight.weaponMaterial);
        weaponEight.weaponPrice = 6000.00;
        System.out.println("Weapon Price: ₹" + weaponEight.weaponPrice);
        weaponEight.paymentMode = "Cash";
        System.out.println("Payment Mode: " + weaponEight.paymentMode);
        System.out.println("");

        Weapon weaponNine = new Weapon();
        weaponNine.weaponId = 9;
        System.out.println("Weapon ID: " + weaponNine.weaponId);
        weaponNine.weaponName = "Flail";
        System.out.println("Weapon Name: " + weaponNine.weaponName);
        weaponNine.weaponType = "Blunt";
        System.out.println("Weapon Type: " + weaponNine.weaponType);
        weaponNine.weaponMaterial = "Iron";
        System.out.println("Weapon Material: " + weaponNine.weaponMaterial);
        weaponNine.weaponPrice = 3200.00;
        System.out.println("Weapon Price: ₹" + weaponNine.weaponPrice);
        weaponNine.paymentMode = "Card";
        System.out.println("Payment Mode: " + weaponNine.paymentMode);
        System.out.println("");

        Weapon weaponTen = new Weapon();
        weaponTen.weaponId = 10;
        System.out.println("Weapon ID: " + weaponTen.weaponId);
        weaponTen.weaponName = "Scimitar";
        System.out.println("Weapon Name: " + weaponTen.weaponName);
        weaponTen.weaponType = "Sword";
        System.out.println("Weapon Type: " + weaponTen.weaponType);
        weaponTen.weaponMaterial = "Steel";
        System.out.println("Weapon Material: " + weaponTen.weaponMaterial);
        weaponTen.weaponPrice = 5500.00;
        System.out.println("Weapon Price: ₹" + weaponTen.weaponPrice);
        weaponTen.paymentMode = "Online";
        System.out.println("Payment Mode: " + weaponTen.paymentMode);
        System.out.println("");

        Weapon weaponEleven = new Weapon();
        weaponEleven.weaponId = 11;
        System.out.println("Weapon ID: " + weaponEleven.weaponId);
        weaponEleven.weaponName = "Trident";
        System.out.println("Weapon Name: " + weaponEleven.weaponName);
        weaponEleven.weaponType = "Polearm";
        System.out.println("Weapon Type: " + weaponEleven.weaponType);
        weaponEleven.weaponMaterial = "Steel";
        System.out.println("Weapon Material: " + weaponEleven.weaponMaterial);
        weaponEleven.weaponPrice = 4800.00;
        System.out.println("Weapon Price: ₹" + weaponEleven.weaponPrice);
        weaponEleven.paymentMode = "Cash";
        System.out.println("Payment Mode: " + weaponEleven.paymentMode);
        System.out.println("");

        Weapon weaponTwelve = new Weapon();
        weaponTwelve.weaponId = 12;
        System.out.println("Weapon ID: " + weaponTwelve.weaponId);
        weaponTwelve.weaponName = "Halberd";
        System.out.println("Weapon Name: " + weaponTwelve.weaponName);
        weaponTwelve.weaponType = "Polearm";
        System.out.println("Weapon Type: " + weaponTwelve.weaponType);
        weaponTwelve.weaponMaterial = "Steel";
        System.out.println("Weapon Material: " + weaponTwelve.weaponMaterial);
        weaponTwelve.weaponPrice = 6100.00;
        System.out.println("Weapon Price: ₹" + weaponTwelve.weaponPrice);
        weaponTwelve.paymentMode = "Card";
        System.out.println("Payment Mode: " + weaponTwelve.paymentMode);
        System.out.println("");

        Weapon weaponThirteen = new Weapon();
        weaponThirteen.weaponId = 13;
        System.out.println("Weapon ID: " + weaponThirteen.weaponId);
        weaponThirteen.weaponName = "Rapier";
        System.out.println("Weapon Name: " + weaponThirteen.weaponName);
        weaponThirteen.weaponType = "Sword";
        System.out.println("Weapon Type: " + weaponThirteen.weaponType);
        weaponThirteen.weaponMaterial = "Steel";
        System.out.println("Weapon Material: " + weaponThirteen.weaponMaterial);
        weaponThirteen.weaponPrice = 5200.00;
        System.out.println("Weapon Price: ₹" + weaponThirteen.weaponPrice);
        weaponThirteen.paymentMode = "Online";
        System.out.println("Payment Mode: " + weaponThirteen.paymentMode);
        System.out.println("");

        Weapon weaponFourteen = new Weapon();
        weaponFourteen.weaponId = 14;
        System.out.println("Weapon ID: " + weaponFourteen.weaponId);
        weaponFourteen.weaponName = "Throwing Axe";
        System.out.println("Weapon Name: " + weaponFourteen.weaponName);
        weaponFourteen.weaponType = "Bladed";
        System.out.println("Weapon Type: " + weaponFourteen.weaponType);
        weaponFourteen.weaponMaterial = "Steel";
        System.out.println("Weapon Material: " + weaponFourteen.weaponMaterial);
        weaponFourteen.weaponPrice = 2900.00;
        System.out.println("Weapon Price: ₹" + weaponFourteen.weaponPrice);
        weaponFourteen.paymentMode = "Cash";
        System.out.println("Payment Mode: " + weaponFourteen.paymentMode);
        System.out.println("");

        Weapon weaponFifteen = new Weapon();
        weaponFifteen.weaponId = 15;
        System.out.println("Weapon ID: " + weaponFifteen.weaponId);
        weaponFifteen.weaponName = "Blunderbuss";
        System.out.println("Weapon Name: " + weaponFifteen.weaponName);
        weaponFifteen.weaponType = "Firearm";
        System.out.println("Weapon Type: " + weaponFifteen.weaponType);
        weaponFifteen.weaponMaterial = "Steel and Wood";
        System.out.println("Weapon Material: " + weaponFifteen.weaponMaterial);
        weaponFifteen.weaponPrice = 8500.00;
        System.out.println("Weapon Price: ₹" + weaponFifteen.weaponPrice);
        weaponFifteen.paymentMode = "Card";
        System.out.println("Payment Mode: " + weaponFifteen.paymentMode);

        System.out.println("Main Ended");
    }
}