package com.xworkz.inheritance;

import com.xworkz.inheritance.example1.Dolo;
import com.xworkz.inheritance.example1.Medicine;
import com.xworkz.inheritance.example10.SriHari;
import com.xworkz.inheritance.example10.Stationary;
import com.xworkz.inheritance.example11.PodCast;
import com.xworkz.inheritance.example11.Show;
import com.xworkz.inheritance.example12.Spoon;
import com.xworkz.inheritance.example12.Utensil;
import com.xworkz.inheritance.example13.Apollo;
import com.xworkz.inheritance.example13.Hospital;
import com.xworkz.inheritance.example14.Carrot;
import com.xworkz.inheritance.example14.Vegetable;
import com.xworkz.inheritance.example15.Flower;
import com.xworkz.inheritance.example15.Lotus;
import com.xworkz.inheritance.example16.Firefox;
import com.xworkz.inheritance.example16.WebBrowser;
import com.xworkz.inheritance.example17.Protector;
import com.xworkz.inheritance.example17.Soldire;
import com.xworkz.inheritance.example18.Farmer;
import com.xworkz.inheritance.example18.Worker;
import com.xworkz.inheritance.example19.Hp;
import com.xworkz.inheritance.example19.Laptop;
import com.xworkz.inheritance.example2.Chocolate;
import com.xworkz.inheritance.example2.DairyMilk;
import com.xworkz.inheritance.example20.Comedy;
import com.xworkz.inheritance.example20.MovieGenr;
import com.xworkz.inheritance.example21.Institution;
import com.xworkz.inheritance.example21.Xworkz;
import com.xworkz.inheritance.example22.Bgmi;
import com.xworkz.inheritance.example22.Game;
import com.xworkz.inheritance.example23.Furniture;
import com.xworkz.inheritance.example23.Table;
import com.xworkz.inheritance.example24.Actor;
import com.xworkz.inheritance.example24.VishnuVardhan;
import com.xworkz.inheritance.example25.Kannada;
import com.xworkz.inheritance.example25.Language;
import com.xworkz.inheritance.example26.Country;
import com.xworkz.inheritance.example26.India;
import com.xworkz.inheritance.example27.BusinessMan;
import com.xworkz.inheritance.example27.RathanTata;
import com.xworkz.inheritance.example28.Doctor;
import com.xworkz.inheritance.example28.Surgeon;
import com.xworkz.inheritance.example29.Guitar;
import com.xworkz.inheritance.example29.Instrument;
import com.xworkz.inheritance.example3.Cloth;
import com.xworkz.inheritance.example3.Shirt;
import com.xworkz.inheritance.example30.IndianIndices;
import com.xworkz.inheritance.example30.Nifty50;
import com.xworkz.inheritance.example31.Harbour;
import com.xworkz.inheritance.example31.NewMangalore;
import com.xworkz.inheritance.example32.Dev;
import com.xworkz.inheritance.example32.Trainer;
import com.xworkz.inheritance.example33.Google;
import com.xworkz.inheritance.example33.SearchEngine;
import com.xworkz.inheritance.example4.Cricketer;
import com.xworkz.inheritance.example4.ViratKohli;
import com.xworkz.inheritance.example5.Device;
import com.xworkz.inheritance.example5.Phone;
import com.xworkz.inheritance.example6.Bottle;
import com.xworkz.inheritance.example6.Plastic;
import com.xworkz.inheritance.example7.MantriSquare;
import com.xworkz.inheritance.example7.ShopingMall;
import com.xworkz.inheritance.example8.Cosmetic;
import com.xworkz.inheritance.example8.Lipstic;
import com.xworkz.inheritance.example9.Bata;
import com.xworkz.inheritance.example9.Brand;

public class Runner {
    public static void main(String[] args) {
        Medicine dolo=new Dolo();
        Chocolate dairyMilk=new DairyMilk();
        Cloth shirt=new Shirt();
        Cricketer virat=new ViratKohli();
        Device phone=new Phone();
        Plastic bottle=new Bottle();
        ShopingMall mall=new MantriSquare();
        Cosmetic lipstic=new Lipstic();
        Brand bata=new Bata();
        Stationary sriHari=new SriHari();
        Show show=new PodCast();
        Utensil spoone=new Spoon();
        Hospital appolo=new Apollo();
        Vegetable carrot=new Carrot();
        Flower lotus=new Lotus();
        WebBrowser fireFox=new Firefox();
        Protector soldire=new Soldire();
        Worker farmer=new Farmer();
        Laptop hp=new Hp();
        MovieGenr comedy=new Comedy();
        Institution xworkz=new Xworkz();
        Game bgmi=new Bgmi();
        Furniture table=new Table();
        Actor actor=new VishnuVardhan();
        Language kannada=new Kannada();
        Country india=new India();
        BusinessMan ratahanTata=new RathanTata();
        Doctor surgeon=new Surgeon();
        Instrument guitar=new Guitar();
        IndianIndices nifty=new Nifty50();
        Harbour mangalore=new NewMangalore();
        Trainer dev=new Dev();
        SearchEngine google=new Google();
    }
}
